{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-compose",
    "version": "3.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "paging-compose-3.3.0-alpha01-multiplatform-sources.jar",
          "url": "paging-compose-3.3.0-alpha01-multiplatform-sources.jar",
          "size": 7545,
          "sha512": "5f36cfc02f02fc3efc96d7acf8df9ec379f6b05028dd1d325ad1bd956ea2e8c8b0e169a9421acc065402f0dc9b47a5d19e9331ea08482cd9bcd1e31d4dd8c6c0",
          "sha256": "d58177c40e8673be8477bb59a218b4c32065d382b74f963e66b0a43609f2ef37",
          "sha1": "c81b3a59c0f8fd4539db966d65f0ee143e811cf5",
          "md5": "3669239cf34ba2320ce4ce74517c1bb8"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "paging-compose-3.3.0-alpha01-versionMetadata.json",
          "size": 1009,
          "sha512": "9e8e72961add9e3321de8f6860792095ac0821fdc74fca5841a18d7eef1f651c4be5f09fa7107ff3b840a12af9bcc6be9255c065f139f206c7b396a18a221d89",
          "sha256": "66277980c03ee548b9dbedfa7ca470e04fa2535dd7ee2282754e2d3b95b7dc73",
          "sha1": "f9024b9e717aecf3e7d4b381ae3fe0c407ec4f53",
          "md5": "fa764ce0eb3fb760ae7b8e6c00f9cdbc"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0-beta03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-beta03"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "paging-compose-metadata-3.3.0-alpha01.jar",
          "url": "paging-compose-3.3.0-alpha01.jar",
          "size": 708,
          "sha512": "e2957ce6974e11a185e4386cee42df00c9d4699a81960d16b816290c169fae789b4bd4035ff57413c98e1f1347ccf3b8b750a5b7f57c8d75439d0a74dc937930",
          "sha256": "525acf721cc8ac1d49d2365c2041480576be89dca90f1e0305efa14c3b95a52c",
          "sha1": "a73d359ea531a1f983dd5531ecc9ce9ac06e7370",
          "md5": "8435e46101bda42232b89929b6f5fdea"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "paging-compose-kotlin-3.3.0-alpha01-sources.jar",
          "url": "paging-compose-3.3.0-alpha01-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-compose-android/3.3.0-alpha01/paging-compose-android-3.3.0-alpha01.module",
        "group": "androidx.paging",
        "module": "paging-compose-android",
        "version": "3.3.0-alpha01"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-compose-android/3.3.0-alpha01/paging-compose-android-3.3.0-alpha01.module",
        "group": "androidx.paging",
        "module": "paging-compose-android",
        "version": "3.3.0-alpha01"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-compose-android/3.3.0-alpha01/paging-compose-android-3.3.0-alpha01.module",
        "group": "androidx.paging",
        "module": "paging-compose-android",
        "version": "3.3.0-alpha01"
      }
    }
  ]
}