{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-util/1.6.0-alpha06-topping02/ui-util-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util.klib",
          "url": "ui-util-iosx64-1.6.0-alpha06-topping02.klib",
          "size": 297231,
          "sha512": "11be328cd1719504c6c81fa549800aeb5e0214f80c82699c2e8490bf1ed02f40bbd33f9aea5169820d9ff1053be20c8a9121a396e7490119ff8e89d464e25637",
          "sha256": "4649709bcfa669fcfaa5d46cd454cf10fb6e38d58749a4745955a1f9e727eb1a",
          "sha1": "0f431f8db466aa923b0b44daec0106918fef899a",
          "md5": "07e5a53e5e4b44bb17530da8f49b56a5"
        },
        {
          "name": "ui-util-cinterop-Topping.klib",
          "url": "ui-util-iosx64-1.6.0-alpha06-topping02-cinterop-Topping.klib",
          "size": 516364,
          "sha512": "3504b02aeb489b328a072cabd479c88c34b65d925ad9f7b756c3bba7d38c54821934402f6770c2e0960c88dfb49d2b384c495c3e4a876109d1e6408a5eb1f2b5",
          "sha256": "d70e35f9c22b7de8b4087e48b62dcb56eb917dc429b89bf3550363d6b0985be2",
          "sha1": "7e7137700879f8d481246d476d3ad330c8be8c30",
          "md5": "a267c58f6a1a28c4d55c996d37fbbf73"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-util-iosx64-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-util-iosx64-1.6.0-alpha06-topping02-sources.jar",
          "size": 49437,
          "sha512": "0c7c8ac4fd8cedec0c4c481c79271dd45d3d42f467114ccf914454cbd82b15762f581c66b99f2ecd19ae3429ff05d13b9ed32e2328804f9130cbad47087d4e17",
          "sha256": "53604cf7632425556d06d35e081724f43b45e95acc7c1d08b8674ebe6dffa286",
          "sha1": "e38013e6193f863df96034694cb7e497110078dd",
          "md5": "37f03c04a674baec1f158a315ff405be"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-iosx64-1.6.0-alpha06-topping02-metadata.jar",
          "url": "ui-util-iosx64-1.6.0-alpha06-topping02-metadata.jar",
          "size": 440988,
          "sha512": "3166e321a7fa4477760f82fa296c6562831e26dbbb65a65f23803f6b2773fe1c43eee1ab47d13c275ce424655f091d770fe00a8f6e755a2e262f425129dcc96b",
          "sha256": "f7e89988de86eb1634d43310c3678760473c26fff35e8f13c613cd554df88037",
          "sha1": "1721d5bc347137a89306a2ead4a86b9296cbe97c",
          "md5": "1dbf496650be31e5355f429f39885567"
        }
      ]
    }
  ]
}