{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-graphics/1.6.0-alpha06-topping02/animation-graphics-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.animation",
    "module": "animation-graphics",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-desktop-1.6.0-alpha06-topping02.jar",
          "url": "animation-graphics-desktop-1.6.0-alpha06-topping02.jar",
          "size": 72228,
          "sha512": "36b6f51dcc84a061fbdf7d5bccb94e66a6ee85fa5a20c9582849fb2f15e4622ce4f401abb8d0642651300dbf2aecdf84049311d8210030e054a5aeacf61a4b18",
          "sha256": "be1ebb4d4a3d01dc45dfcdcb78919e1e03efb723e762a797b0b46ef56fe3b05e",
          "sha1": "87fb69145bef16e5ecf2954e4f48d902e67e6896",
          "md5": "996ea1c8d0565cd2211990dd83b95de8"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-desktop-1.6.0-alpha06-topping02.jar",
          "url": "animation-graphics-desktop-1.6.0-alpha06-topping02.jar",
          "size": 72228,
          "sha512": "36b6f51dcc84a061fbdf7d5bccb94e66a6ee85fa5a20c9582849fb2f15e4622ce4f401abb8d0642651300dbf2aecdf84049311d8210030e054a5aeacf61a4b18",
          "sha256": "be1ebb4d4a3d01dc45dfcdcb78919e1e03efb723e762a797b0b46ef56fe3b05e",
          "sha1": "87fb69145bef16e5ecf2954e4f48d902e67e6896",
          "md5": "996ea1c8d0565cd2211990dd83b95de8"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "animation-graphics-desktop-1.6.0-alpha06-topping02-sources.jar",
          "url": "animation-graphics-desktop-1.6.0-alpha06-topping02-sources.jar",
          "size": 9732,
          "sha512": "bd328e229119895064294437871b229ca1a9600c010c6681567db24fbaa9a30766de126b31a03f8b4a7b684e8d897e1d6a846048d3bf03bacec198517a2ea705",
          "sha256": "4b5199c1daeac34210b5129c35b0053e2f749b5925953566c7db3847238e4697",
          "sha1": "c40b1403d7e7531da6cede16d594869aec78384d",
          "md5": "b950d4108d2dee3e861b4a916e5be96b"
        }
      ]
    }
  ]
}