{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.13.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.13.0-alpha01.aar",
          "url": "core-1.13.0-alpha01.aar",
          "size": 1335859,
          "sha512": "9854b25b730e4ba1c2c1960a8aef3d4eaa59571f7244595679ebebee2439661f5c7eeb0f7cb8d77b118c7a0082eb86f36fc3077563f2e9b34816aa2b9da26f96",
          "sha256": "78b6d14cc433765db9d42dcc2751a4d84c52b29c6c4858ab009fb8902b3bb645",
          "sha1": "765af41be2cd1f609655b0411ce07c65af42f81e",
          "md5": "a0c4201b66288b4fcab7c5f26e48cd1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-testing",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.13.0-alpha01.aar",
          "url": "core-1.13.0-alpha01.aar",
          "size": 1335859,
          "sha512": "9854b25b730e4ba1c2c1960a8aef3d4eaa59571f7244595679ebebee2439661f5c7eeb0f7cb8d77b118c7a0082eb86f36fc3077563f2e9b34816aa2b9da26f96",
          "sha256": "78b6d14cc433765db9d42dcc2751a4d84c52b29c6c4858ab009fb8902b3bb645",
          "sha1": "765af41be2cd1f609655b0411ce07c65af42f81e",
          "md5": "a0c4201b66288b4fcab7c5f26e48cd1d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.13.0-alpha01-sources.jar",
          "url": "core-1.13.0-alpha01-sources.jar",
          "size": 947965,
          "sha512": "aa4df2234d16a05fb7e54633726ca4ff573f8aac7231213de1f454d3e66fc474336a7fd6673db8438926277a52c92b5fb2b4994da247ae11d58ac13742525b55",
          "sha256": "9f77e6157d9324729024609c03a0b97ac6b88cb55eec71469e7440f77de65085",
          "sha1": "19ebb5e6a45e9133846b6eb41429e518010ac9c6",
          "md5": "6f0092ba49f942802ef5274c323c26b3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.13.0-alpha01-versionMetadata.json",
          "url": "core-1.13.0-alpha01-versionMetadata.json",
          "size": 263576,
          "sha512": "33882cf2f6412387c1e6d5f032160d0f5e9ccc2bf224d94454c67a6be1131c245b8ba405020d269da4461bae5fe673ca78701f7e9a1dca45d8444cd54d3c64f9",
          "sha256": "9bde294319c9912d50ef62757d83707e0843e7a4b435a3cd9d30ab0d1638693f",
          "sha1": "21583d0d3ae86079f338c5be84e07de2a36c72b5",
          "md5": "2d2ac66669ce1f61bd59cf1b8a0cd970"
        }
      ]
    }
  ]
}