{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation/1.6.0-alpha06-topping01/animation-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.animation",
    "module": "animation",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation-desktop-1.6.0-alpha06-topping01.jar",
          "url": "animation-desktop-1.6.0-alpha06-topping01.jar",
          "size": 323525,
          "sha512": "6c9ad7fcd8c175c444c8fcfcf4958e036932024918871dc28bf4497cf38dc7f3ecf520a53ecd7eed525bea0918aec4c8d5eb633768002e3613f69e18d4eae2c3",
          "sha256": "a346d17890415f7d0e5cdace0453ff5b546372be3a446d3b0e6c0020b21e3be2",
          "sha1": "4c5bf18b7cf124f666ce34303e059d4913abec7d",
          "md5": "98e13b1235436a8b7a22091e262a8803"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation-desktop-1.6.0-alpha06-topping01.jar",
          "url": "animation-desktop-1.6.0-alpha06-topping01.jar",
          "size": 323525,
          "sha512": "6c9ad7fcd8c175c444c8fcfcf4958e036932024918871dc28bf4497cf38dc7f3ecf520a53ecd7eed525bea0918aec4c8d5eb633768002e3613f69e18d4eae2c3",
          "sha256": "a346d17890415f7d0e5cdace0453ff5b546372be3a446d3b0e6c0020b21e3be2",
          "sha1": "4c5bf18b7cf124f666ce34303e059d4913abec7d",
          "md5": "98e13b1235436a8b7a22091e262a8803"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "animation-desktop-1.6.0-alpha06-topping01-sources.jar",
          "url": "animation-desktop-1.6.0-alpha06-topping01-sources.jar",
          "size": 48331,
          "sha512": "30430b057f6f8218e3a921ff25bb160df84e01fa81febd1d48d35c0a10df411d16b91b4aab77bee4cc00675975d177ea298a7cff9e43ff4288cf929500873815",
          "sha256": "af81d4f4557f7fcda14398353bbbaf350b4a0f182b158aa5e1ddf45fa91824fa",
          "sha1": "c910d3dc33f2b34e4f47de7064713c398e992013",
          "md5": "dfa2f96b6b4b4ec773e669fc68310114"
        }
      ]
    }
  ]
}