{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-samples",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-test-samples-1.6.0-alpha06-topping01.aar",
          "url": "ui-test-samples-1.6.0-alpha06-topping01.aar",
          "size": 43891,
          "sha512": "399109849385fb94996519f1639feb5b3ee1af5182d34c0876b4a5c681c4bccf72a1b29fe6f6c6bbe7e2a877551cf8f46fc38ad70831c63a895b1b9beb1b132e",
          "sha256": "320a0551f5fdfebff3ffba5dfd404124fba8d7f3503bd080b0398987b6b3d8dc",
          "sha1": "50e24509fda858d724fb9d4c99477c18c01a7088",
          "md5": "936e5b365497a961f8d2378032045f83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-samples-1.6.0-alpha06-topping01.aar",
          "url": "ui-test-samples-1.6.0-alpha06-topping01.aar",
          "size": 43891,
          "sha512": "399109849385fb94996519f1639feb5b3ee1af5182d34c0876b4a5c681c4bccf72a1b29fe6f6c6bbe7e2a877551cf8f46fc38ad70831c63a895b1b9beb1b132e",
          "sha256": "320a0551f5fdfebff3ffba5dfd404124fba8d7f3503bd080b0398987b6b3d8dc",
          "sha1": "50e24509fda858d724fb9d4c99477c18c01a7088",
          "md5": "936e5b365497a961f8d2378032045f83"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-samples-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-test-samples-1.6.0-alpha06-topping01-sources.jar",
          "size": 8399,
          "sha512": "98c9cf910d98daf1c0b8b5bfdc1ebfca248618aa8c8d12233c8f7585bfe05430ec9e90c832d05c4035631ca31672f2bd7788db21b3d595c075fa630826bdd0d7",
          "sha256": "6a6edc92ff1cc3474a928fea46a4178fad6683af0c6d7bdd4959ab805cfeef8c",
          "sha1": "eca459258df2927e207df2887b12021bcee5ca3b",
          "md5": "706a417e01befa0678099e719d04a896"
        }
      ]
    }
  ]
}