{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3.material3-adaptive",
    "module": "material3-adaptive-samples",
    "version": "1.0.0-alpha01-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "material3-adaptive-samples-1.0.0-alpha01-topping02.aar",
          "url": "material3-adaptive-samples-1.0.0-alpha01-topping02.aar",
          "size": 22973,
          "sha512": "10a7baaa91675a138ea2a64432a74bcb32a45a2038e0bc8a37b953e57e28e76a1c84202a5a6863e4878da95cd4c7f6fe3350956f92d3d078ffa4a7c27d5b4667",
          "sha256": "20514d9f294334f8c3263cb0cd5643a1c023789eb5e30fc139c2c150936a9f67",
          "sha1": "5a1494bd6235926f55beb03bfd4199e6c0502f45",
          "md5": "4331d28eda11c0c2e9c549dc115954aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0-alpha08-topping02"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive",
          "version": {
            "requires": "1.0.0-alpha01-topping02"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0-alpha08-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material3-adaptive-samples-1.0.0-alpha01-topping02.aar",
          "url": "material3-adaptive-samples-1.0.0-alpha01-topping02.aar",
          "size": 22973,
          "sha512": "10a7baaa91675a138ea2a64432a74bcb32a45a2038e0bc8a37b953e57e28e76a1c84202a5a6863e4878da95cd4c7f6fe3350956f92d3d078ffa4a7c27d5b4667",
          "sha256": "20514d9f294334f8c3263cb0cd5643a1c023789eb5e30fc139c2c150936a9f67",
          "sha1": "5a1494bd6235926f55beb03bfd4199e6c0502f45",
          "md5": "4331d28eda11c0c2e9c549dc115954aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-adaptive-samples-1.0.0-alpha01-topping02-sources.jar",
          "url": "material3-adaptive-samples-1.0.0-alpha01-topping02-sources.jar",
          "size": 2165,
          "sha512": "38c22b46c19c26503577b5e31ac6826aaed32c4e7202353cd0bcc17897ed7a2e07f49d49d8e31b4641a1456ef3d2091afa6353d192529e85fa81f03c932a7ec7",
          "sha256": "73ab183f317bdeecfac18988b48e48135b04f23728b860edb84e9a026beb0689",
          "sha1": "55f8ddd0c327a0f3bfc14445e502da6834d2b591",
          "md5": "e9ccaee3af64f56d547805a06b9434da"
        }
      ]
    }
  ]
}