{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-samples",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-test-samples-1.6.0-alpha06-topping02.aar",
          "url": "ui-test-samples-1.6.0-alpha06-topping02.aar",
          "size": 43892,
          "sha512": "27cc4a14bcd7bdce66ec2d33410dc86fca9da68d478d42a0a8e3dfbee77a8214f4b3de0f891b544f03f7c0fc50bbbb6edeb1ef244c5ae0fd386a5d442bd64635",
          "sha256": "617a1ab3bc896c3da55aa4b59a20f8e7a4858fa495a72caf85821cb2c8274874",
          "sha1": "4cb3f8af8dada4e594b8c8aca28a226757ab8eca",
          "md5": "386c8d9a8c78035ef622539c662d9aba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-samples-1.6.0-alpha06-topping02.aar",
          "url": "ui-test-samples-1.6.0-alpha06-topping02.aar",
          "size": 43892,
          "sha512": "27cc4a14bcd7bdce66ec2d33410dc86fca9da68d478d42a0a8e3dfbee77a8214f4b3de0f891b544f03f7c0fc50bbbb6edeb1ef244c5ae0fd386a5d442bd64635",
          "sha256": "617a1ab3bc896c3da55aa4b59a20f8e7a4858fa495a72caf85821cb2c8274874",
          "sha1": "4cb3f8af8dada4e594b8c8aca28a226757ab8eca",
          "md5": "386c8d9a8c78035ef622539c662d9aba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-samples-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-test-samples-1.6.0-alpha06-topping02-sources.jar",
          "size": 8399,
          "sha512": "98c9cf910d98daf1c0b8b5bfdc1ebfca248618aa8c8d12233c8f7585bfe05430ec9e90c832d05c4035631ca31672f2bd7788db21b3d595c075fa630826bdd0d7",
          "sha256": "6a6edc92ff1cc3474a928fea46a4178fad6683af0c6d7bdd4959ab805cfeef8c",
          "sha1": "eca459258df2927e207df2887b12021bcee5ca3b",
          "md5": "706a417e01befa0678099e719d04a896"
        }
      ]
    }
  ]
}