{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling/1.6.0-alpha06-topping02/ui-tooling-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.ui",
    "module": "ui-tooling",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-desktop-1.6.0-alpha06-topping02.jar",
          "url": "ui-tooling-desktop-1.6.0-alpha06-topping02.jar",
          "size": 28477,
          "sha512": "a772f421f0317bcc5a908a9ce48617dea57bff3f13400c42b05729498d795de112b089117326c4b4571c006e7c060eedb18a74b80d5ff275f3ac74d7b64bd0bc",
          "sha256": "4cfc9656f41d08573d4bc2400362338ab60680bcde895b3d41f447953571293d",
          "sha1": "a4d9b64768dd7443d8faa73d82206311576e52dc",
          "md5": "0c788cd96a6610e93095b0c0fa822ba8"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-desktop-1.6.0-alpha06-topping02.jar",
          "url": "ui-tooling-desktop-1.6.0-alpha06-topping02.jar",
          "size": 28477,
          "sha512": "a772f421f0317bcc5a908a9ce48617dea57bff3f13400c42b05729498d795de112b089117326c4b4571c006e7c060eedb18a74b80d5ff275f3ac74d7b64bd0bc",
          "sha256": "4cfc9656f41d08573d4bc2400362338ab60680bcde895b3d41f447953571293d",
          "sha1": "a4d9b64768dd7443d8faa73d82206311576e52dc",
          "md5": "0c788cd96a6610e93095b0c0fa822ba8"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-tooling-desktop-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-tooling-desktop-1.6.0-alpha06-topping02-sources.jar",
          "size": 9730,
          "sha512": "62fc5729ad605eaa29a764233c85e75f7bc2f3ac9bbabde01f3ba479c5aa3d75667b6d5aa7a10a15b48efcf2633912de0a38ba4db036851fdbe8bf14cea71be0",
          "sha256": "5facb3263f14989970263e12876df2eb0dd830ecfb8cc54ce74a00177f184c9c",
          "sha1": "657649e86aa569e978ba09e03a97c13f7daa02bf",
          "md5": "29059efad2ece027bcded2afb740c694"
        }
      ]
    }
  ]
}