{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material/1.6.0-alpha06-topping02/material-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.material",
    "module": "material",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material.klib",
          "url": "material-iosx64-1.6.0-alpha06-topping02.klib",
          "size": 1217143,
          "sha512": "a2c52051ddf9ac8bcca1c0f746772c22815919cd74628c75b168d998f883b21824909bf04eea436931e790cffca13c5071f49154c69a50d6c702a3d0e1986ad5",
          "sha256": "c8e1105ebab73ed2efaad73403fe5d61add266891c244cf805a520503d7f6342",
          "sha1": "5eb6ae55148f57432b93c4f87a9f74a3068f3f81",
          "md5": "f421ae5f2d9e1443c2463ce6f41af9c7"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material-iosx64-1.6.0-alpha06-topping02-sources.jar",
          "url": "material-iosx64-1.6.0-alpha06-topping02-sources.jar",
          "size": 239824,
          "sha512": "877db1fcc700f1d178505df9e8b414cc2acf981fca126c528db106cb7eff70419e8316ed5506ce55fbee113c82aaa5e6c25c17060f8569e4a94d00bff3d76a79",
          "sha256": "f6904a95a5628cecc87d785076464dce570625dc932d0331617847505f8e2769",
          "sha1": "0956618b8dd2e07763b368a5ccb3a98c53c6f4a5",
          "md5": "e23cc058bf0b87674bd60c9d721cd63c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-iosx64-1.6.0-alpha06-topping02-metadata.jar",
          "url": "material-iosx64-1.6.0-alpha06-topping02-metadata.jar",
          "size": 9506,
          "sha512": "c81a00b93ead628a1390dc14efb0ca922a55226df7e56e5be67f97c0ff53e65e23eaf02d279099a68bc6a8bdb25aef392ac2898ad6ffe0c11a11275055f52cb8",
          "sha256": "0edf68d0fd67bfd869dd80caebc8ea90f89daafdaae36bddfc1ec439a59486e3",
          "sha1": "6fff6fa4e930298384ff6822ee6f3720df51ce65",
          "md5": "df9c2d345d741f4c9f638354ad8524ba"
        }
      ]
    }
  ]
}