{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-graphics-samples",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "animation-graphics-samples-1.6.0-alpha06-topping01.aar",
          "url": "animation-graphics-samples-1.6.0-alpha06-topping01.aar",
          "size": 7738,
          "sha512": "a615bfd1e87c94d31ddd5eac4fe02eaaaed6ddf06b2d503ffee57477fe7a11e44bb853d149c41a5b8d2bfa78b64f62d282d252daff9fffe3560c554f7d7e2a2d",
          "sha256": "1fa938890da119fd0eca70c2900291358ca513c4f4765966c60ca59364448311",
          "sha1": "beee69df003f8c94bfcac2311a43e9beae5c01f1",
          "md5": "152009bf2ae1ee9ec8241b8d76916520"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-samples-1.6.0-alpha06-topping01.aar",
          "url": "animation-graphics-samples-1.6.0-alpha06-topping01.aar",
          "size": 7738,
          "sha512": "a615bfd1e87c94d31ddd5eac4fe02eaaaed6ddf06b2d503ffee57477fe7a11e44bb853d149c41a5b8d2bfa78b64f62d282d252daff9fffe3560c554f7d7e2a2d",
          "sha256": "1fa938890da119fd0eca70c2900291358ca513c4f4765966c60ca59364448311",
          "sha1": "beee69df003f8c94bfcac2311a43e9beae5c01f1",
          "md5": "152009bf2ae1ee9ec8241b8d76916520"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-graphics-samples-1.6.0-alpha06-topping01-sources.jar",
          "url": "animation-graphics-samples-1.6.0-alpha06-topping01-sources.jar",
          "size": 1904,
          "sha512": "1de2936d87e3b1e163e6f36551f48096cc2f3bfbe799ef0828c91e5d3961c95353e0d5fbe86ef7473441c0beb9db9bb8c6f861ae4854d0e56a65de8de1e23bf5",
          "sha256": "4ad11d173c06d7e8d46dc5794d7e015d9b2e84d1fca30e10bdcd37ac89562b44",
          "sha1": "2e4b63c37e6d66a08bfdc65104248933aa0487aa",
          "md5": "ecdd0a4c90773a2a65bfedda699dfb3f"
        }
      ]
    }
  ]
}