{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text-samples",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-text-samples-1.6.0-alpha06-topping01.aar",
          "url": "ui-text-samples-1.6.0-alpha06-topping01.aar",
          "size": 83383,
          "sha512": "d77d09d7390304e78eaa46558f033a9dfa6d7fbe0ef2b1fb991bffcd1015205d3e2c5e2badedf1b1e49d5ae3eb1db25f09ef4b6d550d41cbdc69c70f1d3d9563",
          "sha256": "1e2fd8c5c1c2f3da36277dabda632c654c7f444ef1076333832fb72c367f0be4",
          "sha1": "51ffb29aaab5b5ad13ae33f7a5b3a20fb2d06a92",
          "md5": "9a5e2640ece0a16b4e5d3037c5c01a00"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-samples-1.6.0-alpha06-topping01.aar",
          "url": "ui-text-samples-1.6.0-alpha06-topping01.aar",
          "size": 83383,
          "sha512": "d77d09d7390304e78eaa46558f033a9dfa6d7fbe0ef2b1fb991bffcd1015205d3e2c5e2badedf1b1e49d5ae3eb1db25f09ef4b6d550d41cbdc69c70f1d3d9563",
          "sha256": "1e2fd8c5c1c2f3da36277dabda632c654c7f444ef1076333832fb72c367f0be4",
          "sha1": "51ffb29aaab5b5ad13ae33f7a5b3a20fb2d06a92",
          "md5": "9a5e2640ece0a16b4e5d3037c5c01a00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-text-samples-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-text-samples-1.6.0-alpha06-topping01-sources.jar",
          "size": 15616,
          "sha512": "d8be291a2736b365baba3ea57bdcadc848e08dbd78dc90071f5a00060790df319fd11ba0d34432b6b85507ffec97735813261d82ed7bfc6d2e9086705bb439b5",
          "sha256": "7275f9750f46eab08a494f0d1d6bcbd2a65e31e4443eb1aa6e9577daa21bc7ad",
          "sha1": "0bf70899d2c5df29eb7176d961b1bee4aa963b4e",
          "md5": "3183be640abf9266564ca61926698731"
        }
      ]
    }
  ]
}