{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-preferences/1.1.0-alpha05/datastore-preferences-1.1.0-alpha05.module",
    "group": "androidx.datastore",
    "module": "datastore-preferences",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-jvm-1.1.0-alpha05.jar",
          "url": "datastore-preferences-jvm-1.1.0-alpha05.jar",
          "size": 1404,
          "sha512": "08cf0c2c706957b52cf4b0c05e23795d38eeef402be5772b38eb650bd9b171b5b61235bfb6fbbf5ae4f03606867d7e331178a533478bc5a8b5d0ab0a5a808768",
          "sha256": "2c9606bbf8b2255e47aec0c0d3b020d2ba726eb26b3b406d53ea0477b6d31637",
          "sha1": "f842573b92a8dd1242b9e38691ee3cd84cc6a848",
          "md5": "064542cd9ca9d411f52d1ce09dabee74"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-jvm-1.1.0-alpha05.jar",
          "url": "datastore-preferences-jvm-1.1.0-alpha05.jar",
          "size": 1404,
          "sha512": "08cf0c2c706957b52cf4b0c05e23795d38eeef402be5772b38eb650bd9b171b5b61235bfb6fbbf5ae4f03606867d7e331178a533478bc5a8b5d0ab0a5a808768",
          "sha256": "2c9606bbf8b2255e47aec0c0d3b020d2ba726eb26b3b406d53ea0477b6d31637",
          "sha1": "f842573b92a8dd1242b9e38691ee3cd84cc6a848",
          "md5": "064542cd9ca9d411f52d1ce09dabee74"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "datastore-preferences-jvm-1.1.0-alpha05-sources.jar",
          "url": "datastore-preferences-jvm-1.1.0-alpha05-sources.jar",
          "size": 1561,
          "sha512": "660ae721dea1911b354371a961644841a65c4d3a7007db7902ed1e8fb088519e7fb0bf863c3d6b2fda2d290f94286ea03e95674fc4feeb763868d1bb040ebb52",
          "sha256": "05ccf7d85c1f5703ed47a7a6bc09a1bc589c7ca264e101a8bb03068fdbec2c77",
          "sha1": "84b6f65693f3e6af5e8e5ef0446a4e953a6ee22c",
          "md5": "3d45d8c87ab7eabc89b9d6b68ef5db5a"
        }
      ]
    }
  ]
}