{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tv",
    "module": "tv-material",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.tv",
          "module": "tv-foundation",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "tv-material-1.0.0-alpha10.aar",
          "url": "tv-material-1.0.0-alpha10.aar",
          "size": 894595,
          "sha512": "330b68d225ab184ed57ace90b693c3f181e1c347ff9e9f6299df660786d054bb27c95f5c22b837f24889fb6046c64f26a5146b07459febcff819209390ee8b57",
          "sha256": "57b2d469b1a486446575449ec104ff8c33a9b200bd287f2daaf7832266d4c806",
          "sha1": "b775950b6fddc334c9be04bae664f15e418106ac",
          "md5": "a5c34c0b9c407aa8a9f888cf740a5326"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.tv",
          "module": "tv-foundation",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "tv-material-1.0.0-alpha10.aar",
          "url": "tv-material-1.0.0-alpha10.aar",
          "size": 894595,
          "sha512": "330b68d225ab184ed57ace90b693c3f181e1c347ff9e9f6299df660786d054bb27c95f5c22b837f24889fb6046c64f26a5146b07459febcff819209390ee8b57",
          "sha256": "57b2d469b1a486446575449ec104ff8c33a9b200bd287f2daaf7832266d4c806",
          "sha1": "b775950b6fddc334c9be04bae664f15e418106ac",
          "md5": "a5c34c0b9c407aa8a9f888cf740a5326"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tv-material-1.0.0-alpha10-sources.jar",
          "url": "tv-material-1.0.0-alpha10-sources.jar",
          "size": 132874,
          "sha512": "51d80a945c9453985939006952cb1bde924d223287a05ab1fed5b63b11d5edeb93167aa125199bc955e2f1970f0e15fb4c227f40c2532048b9029bb011ddd454",
          "sha256": "d5290568b298e99da9e35244fefc0c6e2ed1aafbfe0303065c26a364c228ee27",
          "sha1": "51fde62f5bc5b66f255f1dd2a235cf5b9d22a484",
          "md5": "8a37aacf74aa88ce6d78d20f9a07451f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "tv-material-1.0.0-alpha10-versionMetadata.json",
          "url": "tv-material-1.0.0-alpha10-versionMetadata.json",
          "size": 74244,
          "sha512": "467c7dd731f1b0fd33d2213200a1544b9db036d54c76adc400f8875e634d19b16ac5eb125e1d27e6ff88cd4293b22a46598ed731c701b266a93d8a0ed06b6751",
          "sha256": "6dfc6e0967461e22a78835a8d015c3b92eda9ed9f4cee1699f0d91924eaa7fc7",
          "sha1": "77a29df7d74b25a0b25ff377bc262beae6143111",
          "md5": "52bd49d0e1eba7e356ec115cf8782783"
        }
      ]
    }
  ]
}