{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.profileinstaller",
    "module": "profileinstaller",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.4.0-alpha01.aar",
          "url": "profileinstaller-1.4.0-alpha01.aar",
          "size": 48053,
          "sha512": "a01109581901cbeed15047c9d7bec4889dc2912240e62173d7fb3eee25894d3f9cf55b668421e9c2581d517a9f9f3c4b58e828936fdadb0b18e2482139520673",
          "sha256": "46ae074297eeb7f949267371623260c6967308e21f6132bf5ff611a99c279a54",
          "sha1": "97681c2e35c0dcd1eb08623758cc661af1793186",
          "md5": "1974d1eb4e1157a70321f86aa7304765"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.4.0-alpha01.aar",
          "url": "profileinstaller-1.4.0-alpha01.aar",
          "size": 48053,
          "sha512": "a01109581901cbeed15047c9d7bec4889dc2912240e62173d7fb3eee25894d3f9cf55b668421e9c2581d517a9f9f3c4b58e828936fdadb0b18e2482139520673",
          "sha256": "46ae074297eeb7f949267371623260c6967308e21f6132bf5ff611a99c279a54",
          "sha1": "97681c2e35c0dcd1eb08623758cc661af1793186",
          "md5": "1974d1eb4e1157a70321f86aa7304765"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "profileinstaller-1.4.0-alpha01-sources.jar",
          "url": "profileinstaller-1.4.0-alpha01-sources.jar",
          "size": 39388,
          "sha512": "0703c4e2cc856b63c1a705c3898f4b857e5375ffad42223801b2dc42e88711b993f8914170ce435e6d084adcb0c200d585528f3a9270a49f43634fed2a516f2d",
          "sha256": "39006a00d44aeda94b74ef2b8630100bd428b9f2961eefe081870346a607beac",
          "sha1": "b06803e158f65dfdbadf12b91ad0547c0bdf85cd",
          "md5": "fef5eb336febede8911919cfa134066b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "profileinstaller-1.4.0-alpha01-versionMetadata.json",
          "url": "profileinstaller-1.4.0-alpha01-versionMetadata.json",
          "size": 3892,
          "sha512": "6f668ab284191e2f8ef57a28f3773fdd5b4f125049251d51f70aaa6fc4eb368f01cc4e0c6406ce4c8a4a0dd50f603eecae338b614501ff1612b9a60f0b23b3e2",
          "sha256": "e4c6ee30b3bf0b35a5f8908eabee56bff5c7a4c269e5b951745a8cbeab0f3432",
          "sha1": "0d431a9f8fd0807cd117fbdde0f853ca2c6fe3ed",
          "md5": "14aec67de1699c1fc32d4dd9716cc808"
        }
      ]
    }
  ]
}