{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-adaptive/1.0.0-alpha01-topping01/material3-adaptive-1.0.0-alpha01-topping01.module",
    "group": "androidx.compose.material3",
    "module": "material3-adaptive",
    "version": "1.0.0-alpha01-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0-alpha08-topping01"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0-alpha08-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material3-adaptive.klib",
          "url": "material3-adaptive-iossimulatorarm64-1.0.0-alpha01-topping01.klib",
          "size": 110101,
          "sha512": "2cf925300d22c6f9dca5b17d337f7badb0c8c359d40bf415e763076d36359ca37b9bf0a60e0148bdef9875538a392c4fe4438c26f07b85b24d0529643ebe18c0",
          "sha256": "ddf8a611332e17b6ddfbb827cdc33cac894117c20d37b765f32d48fc2b6087d9",
          "sha1": "ec84537436f6d50d38ec0204b36929309e603a29",
          "md5": "2eb7b40df8975a4a007e4d0b2ebec066"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material3-adaptive-iossimulatorarm64-1.0.0-alpha01-topping01-sources.jar",
          "url": "material3-adaptive-iossimulatorarm64-1.0.0-alpha01-topping01-sources.jar",
          "size": 30792,
          "sha512": "d69dfafb8ed615066206ed3d2515e0257a6c75963203b08c0d78a0dc24850aa001c64f40b3732ceab2f4bee466fd6e2598697b58f61f2b5e33049198be55d3a0",
          "sha256": "da31d1b156eb504f133b22231617bedd1979f5a7afaf979bbba382243ddfe304",
          "sha1": "dbe5953ab302442193f2be6a8856b29cad272c41",
          "md5": "b6626812cb793255de812cd8519a5ab4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0-alpha08-topping01"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0-alpha08-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material3-adaptive-iossimulatorarm64-1.0.0-alpha01-topping01-metadata.jar",
          "url": "material3-adaptive-iossimulatorarm64-1.0.0-alpha01-topping01-metadata.jar",
          "size": 6055,
          "sha512": "238bc8015d3f8604a1ac05afd12723e399e2a4c48b4c2c0800031b26102d9d77797bf3d1270d1a18ec6a432c1bef964dd13f87184dbd39bf2d1fc161bc7035c4",
          "sha256": "2cf8bd0159e3da8f52b5190e3005e9ca345df951c4ddd35338c7b131f8fd59a8",
          "sha1": "493dc01839ef00ba1f2b58e016b4d332f3b5ef73",
          "md5": "424b7eafc6e7b932a7aac9fdbf81166e"
        }
      ]
    }
  ]
}