{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tv",
    "module": "tv-samples",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tv-samples-1.0.0-alpha10.aar",
          "url": "tv-samples-1.0.0-alpha10.aar",
          "size": 240695,
          "sha512": "48e4fdc8d74877f3d299c7726c06ea34fc5403ca4baee02883930c94bb1f52d70d01fae7f3361e49f09e79e5c138f86d64d96b9e54800e1d66e352ff6556d77e",
          "sha256": "cbee02e1c1562d179e75ea26f386a0dcf1fccf197507f9b33d2207a47c1d1ca4",
          "sha1": "a45576c14c464731a75eac3c7bb7c61b6b39e3aa",
          "md5": "c6c2b1c203b86ef12c0f0f6909c9b37f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tv",
          "module": "tv-foundation",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.tv",
          "module": "tv-material",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "tv-samples-1.0.0-alpha10.aar",
          "url": "tv-samples-1.0.0-alpha10.aar",
          "size": 240695,
          "sha512": "48e4fdc8d74877f3d299c7726c06ea34fc5403ca4baee02883930c94bb1f52d70d01fae7f3361e49f09e79e5c138f86d64d96b9e54800e1d66e352ff6556d77e",
          "sha256": "cbee02e1c1562d179e75ea26f386a0dcf1fccf197507f9b33d2207a47c1d1ca4",
          "sha1": "a45576c14c464731a75eac3c7bb7c61b6b39e3aa",
          "md5": "c6c2b1c203b86ef12c0f0f6909c9b37f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tv-samples-1.0.0-alpha10-sources.jar",
          "url": "tv-samples-1.0.0-alpha10-sources.jar",
          "size": 13625,
          "sha512": "9f89d7ab98be8c9e8f102561c93b11e2dcd2001662a6acd6eff82a4dcd1b73925d1c4e946f9f3d8ddd659819277846d91d953ba022e9eb8c1c42594bbbd19247",
          "sha256": "af76d75beb7c5bf3723a7df6a18bd75e93c28344fd06300788ebd5cb49db8459",
          "sha1": "73c6c067d53a41379b4268d6fda0e8c0bdcf9197",
          "md5": "9cb793e5a8335888448ef9c42dd8f359"
        }
      ]
    }
  ]
}