{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core-samples",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "animation-core-samples-1.6.0-alpha06-topping01.aar",
          "url": "animation-core-samples-1.6.0-alpha06-topping01.aar",
          "size": 184016,
          "sha512": "a800197b96a71b618dc3cc9790890521c08f31eb38ba41bca9f02602f0b1935b75eae95d2dc5b8c142ac05ffb2f377ff0c52a0e32b3b72258a1b2f5c940596c6",
          "sha256": "7f54aa91059026f59c4f11eee6216c2695793f87abbe3c4b1cdd3e9c131e7d4a",
          "sha1": "7aeb23d122a9b2d5e695468459cf9f9982841799",
          "md5": "5e58276ab2689162ac1ae8dac5e2f154"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.6.0-alpha06-topping01.aar",
          "url": "animation-core-samples-1.6.0-alpha06-topping01.aar",
          "size": 184016,
          "sha512": "a800197b96a71b618dc3cc9790890521c08f31eb38ba41bca9f02602f0b1935b75eae95d2dc5b8c142ac05ffb2f377ff0c52a0e32b3b72258a1b2f5c940596c6",
          "sha256": "7f54aa91059026f59c4f11eee6216c2695793f87abbe3c4b1cdd3e9c131e7d4a",
          "sha1": "7aeb23d122a9b2d5e695468459cf9f9982841799",
          "md5": "5e58276ab2689162ac1ae8dac5e2f154"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-core-samples-1.6.0-alpha06-topping01-sources.jar",
          "url": "animation-core-samples-1.6.0-alpha06-topping01-sources.jar",
          "size": 17853,
          "sha512": "9fa87f2e110cff62c5048616e27425e931080991d2aed2fbc402b31834edcd43526b8496ca480ef0b3baa9d46226b98a08d7b987b13d1cfd491e28c8ad4c7d77",
          "sha256": "66a09ad9b62a455e561749e4abae94f433f0c705b9b1a9becfb67733f5bf8e97",
          "sha1": "0a7e4f32d069d9592a5eb74d5327a42a8f0f0f64",
          "md5": "2df364be663197df501b5efe31fe08bc"
        }
      ]
    }
  ]
}