{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose-samples",
    "version": "1.8.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "activity-compose-samples-1.8.0-rc01.aar",
          "url": "activity-compose-samples-1.8.0-rc01.aar",
          "size": 33538,
          "sha512": "013311ff353c31fbb5592663e9afe072d690ef9dbc37ae9e005ec29864cabaf7de3d3766bb7bf309db867fdfd5b0ba2117899830f17f51902d9f4ddd5b469174",
          "sha256": "85275d6b4621cda3cd72babec6cd2d8f45a948f7999c2fdb463b04bd9585b2e8",
          "sha1": "314d3be3a232c8c10d1fa08813ae57e918f17bbc",
          "md5": "b1d699deaf5a564154bbdc7b69d76c29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "activity-compose-samples-1.8.0-rc01.aar",
          "url": "activity-compose-samples-1.8.0-rc01.aar",
          "size": 33538,
          "sha512": "013311ff353c31fbb5592663e9afe072d690ef9dbc37ae9e005ec29864cabaf7de3d3766bb7bf309db867fdfd5b0ba2117899830f17f51902d9f4ddd5b469174",
          "sha256": "85275d6b4621cda3cd72babec6cd2d8f45a948f7999c2fdb463b04bd9585b2e8",
          "sha1": "314d3be3a232c8c10d1fa08813ae57e918f17bbc",
          "md5": "b1d699deaf5a564154bbdc7b69d76c29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-compose-samples-1.8.0-rc01-sources.jar",
          "url": "activity-compose-samples-1.8.0-rc01-sources.jar",
          "size": 3667,
          "sha512": "aab76d571fe6985d3aef7e5c17cb32210bac2f43030d628e3998678577634be3d6c254428ecfb54d7020eb41a7404421feb8826008f8cba8509a8e1691a86911",
          "sha256": "612b5c8a5f9bbeb484b22c803871063526b26031908c7be5d3c66fc1043854e9",
          "sha1": "1c1c9d07be2ffe6d70b569052cc3d3f57ebd23a9",
          "md5": "d2fa7a801c4a351250249e4eb80d4412"
        }
      ]
    }
  ]
}