{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material3-samples",
    "version": "1.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compose-material3-samples-1.3.0-alpha06.aar",
          "url": "compose-material3-samples-1.3.0-alpha06.aar",
          "size": 351436,
          "sha512": "1e9130c70fdf4774325aed719d51e8a4fee4ae66014229f77380535775f305c64c3cb88096407667cf2b799c86c1ea97ec2ec699d7300dfb82562cb5fd2c6bc8",
          "sha256": "a8dab92cdfb214e0765c0f2235ed4d51049eab2cb5acf282dd6de7d3e82386ed",
          "sha1": "52a86c9c45ef53d711a711b3e70105b72bdcf9d7",
          "md5": "a8fcc353a2a9b28bafa0a004b4093e6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0-rc01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material3-samples-1.3.0-alpha06.aar",
          "url": "compose-material3-samples-1.3.0-alpha06.aar",
          "size": 351436,
          "sha512": "1e9130c70fdf4774325aed719d51e8a4fee4ae66014229f77380535775f305c64c3cb88096407667cf2b799c86c1ea97ec2ec699d7300dfb82562cb5fd2c6bc8",
          "sha256": "a8dab92cdfb214e0765c0f2235ed4d51049eab2cb5acf282dd6de7d3e82386ed",
          "sha1": "52a86c9c45ef53d711a711b3e70105b72bdcf9d7",
          "md5": "a8fcc353a2a9b28bafa0a004b4093e6b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-material3-samples-1.3.0-alpha06-sources.jar",
          "url": "compose-material3-samples-1.3.0-alpha06-sources.jar",
          "size": 15810,
          "sha512": "35e3f19a7f4f24e72ba9dbd6b4cdb69c331a859de65376e5236bcd39c74e2d1de24f87aee225a20be74ca21159cdf78c7abf47316ffd1f3190d5cbcb33d06dea",
          "sha256": "da8dd59a581668975e9fb5c718098663d6ec7b3d7cbe398b9b1155358ebd3e65",
          "sha1": "0898768e1cc52b06a9b142afaf342b4ce2b87016",
          "md5": "ec00936fd0109ca9923bd17249c8319d"
        }
      ]
    }
  ]
}