{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable-samples",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runtime-saveable-samples-1.6.0-alpha06-topping02.aar",
          "url": "runtime-saveable-samples-1.6.0-alpha06-topping02.aar",
          "size": 56745,
          "sha512": "b920433c64a56a55c41fb7461549c321989af68844e1ac8ad5d224d7316119e678d1f178cecce9e3a46870fb8b353103239237a7d99e48199526765b78f05ed5",
          "sha256": "3348e9224eb09091b1d7b1bbfe830c2b27e99679797705337d6ebff48a397bac",
          "sha1": "b770e791d1c1b67f2a714604dcca4f7c3ddbbafb",
          "md5": "aa96c469bd3a433c3538dfbd04026fb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-samples-1.6.0-alpha06-topping02.aar",
          "url": "runtime-saveable-samples-1.6.0-alpha06-topping02.aar",
          "size": 56745,
          "sha512": "b920433c64a56a55c41fb7461549c321989af68844e1ac8ad5d224d7316119e678d1f178cecce9e3a46870fb8b353103239237a7d99e48199526765b78f05ed5",
          "sha256": "3348e9224eb09091b1d7b1bbfe830c2b27e99679797705337d6ebff48a397bac",
          "sha1": "b770e791d1c1b67f2a714604dcca4f7c3ddbbafb",
          "md5": "aa96c469bd3a433c3538dfbd04026fb9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-saveable-samples-1.6.0-alpha06-topping02-sources.jar",
          "url": "runtime-saveable-samples-1.6.0-alpha06-topping02-sources.jar",
          "size": 4242,
          "sha512": "6f6d4db74d9d093a243d76d40632b179ae90b10bcfafff0cb22cf1a0add70228345d511ca9b780f3b82872b9bb3d08a070549dc247a9b06b7893333b14b32b24",
          "sha256": "4fc8f3b7a2c215818a395dcf8f1771624a51cc8f85cfed15cb6af3b2cf8d412d",
          "sha1": "5c3a00342745e0a24d46cffcdd071a7bd59d4882",
          "md5": "457365a515cf69f8c08e71f55456913e"
        }
      ]
    }
  ]
}