{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler-daemon",
    "version": "1.5.3-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compiler-daemon-1.5.3-topping02.jar",
          "url": "compiler-daemon-1.5.3-topping02.jar",
          "size": 18777,
          "sha512": "7142f052ed37f299f78773a421945f43430cef6822f4575c7189f52e151a6393dbbd1485b0e68b928d659908ab9701b80fe9a9b7d68e166387f7ffb3a28f7c7f",
          "sha256": "a8d8fc1a7c16bfc0baed7a1e83ad7bd9d4f4ae0d8c62960e788b4ea45af27bb8",
          "sha1": "9fe6072694ac99eb9b7419ab830f92778b4d6ef2",
          "md5": "c54a063021e8f28e0b66c8c6db538093"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.3-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-daemon-1.5.3-topping02.jar",
          "url": "compiler-daemon-1.5.3-topping02.jar",
          "size": 18777,
          "sha512": "7142f052ed37f299f78773a421945f43430cef6822f4575c7189f52e151a6393dbbd1485b0e68b928d659908ab9701b80fe9a9b7d68e166387f7ffb3a28f7c7f",
          "sha256": "a8d8fc1a7c16bfc0baed7a1e83ad7bd9d4f4ae0d8c62960e788b4ea45af27bb8",
          "sha1": "9fe6072694ac99eb9b7419ab830f92778b4d6ef2",
          "md5": "c54a063021e8f28e0b66c8c6db538093"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-daemon-1.5.3-topping02-all.jar",
          "url": "compiler-daemon-1.5.3-topping02-all.jar",
          "size": 69730008,
          "sha512": "ce3637279303344234c3ed4c9ac1633ef6a53bdfa46517123fd801096402fcc43f41a3ecad15569236a91806b11b3d27ddf3bafe7cec2450ec8cfa9a4482fa50",
          "sha256": "d109df6641640be35d153d87691f20d3997b64ef3a4d9dd6d2193abcf7381c6a",
          "sha1": "7cfea5e7809aa2d195d174518529a75535b9fe03",
          "md5": "109085aea55fb22f22cbe137465b07a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-daemon-1.5.3-topping02-sources.jar",
          "url": "compiler-daemon-1.5.3-topping02-sources.jar",
          "size": 4925,
          "sha512": "7965ed55cf21b6479b60c89104d970f4a3d87f4b947c01b8c5ca953ee890f0a9ec86290ea5bb4448c080af5f63dc039c75aa17ba5722487cb42e64c0fc49053b",
          "sha256": "eabf52e548d52c31bd884dd91628ad3466e093e3d060c7009c93ce67aa3dffab",
          "sha1": "8277a88be73fd2db99d71f070d11bf4591d02e11",
          "md5": "2b5ee5e6456b137fc28f8c1d4016fe11"
        }
      ]
    }
  ]
}