{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotation/1.8.0-alpha01/annotation-1.8.0-alpha01.module",
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation.klib",
          "url": "annotation-macosarm64-1.8.0-alpha01.klib",
          "size": 17643,
          "sha512": "5e438ded670aa6eb2ab0987262fef75718447f430d2026b202d9921e5b3c70c03b40b1106cfa088c0dc288ec403ef2696303dfb99ea00902be5825773e9c4bef",
          "sha256": "db68846f7f74cd74bf9f79394280bde836bd828087070503508828f2e49c245d",
          "sha1": "9c92a023a86901656bb1f7f03c69a6c993878ffb",
          "md5": "be8062113d10596cccb96c090297b684"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "annotation-macosarm64-1.8.0-alpha01-sources.jar",
          "url": "annotation-macosarm64-1.8.0-alpha01-sources.jar",
          "size": 24319,
          "sha512": "a11e56e4d8a5d42398d5a203490a9bd86e64243e01786afb94036a48a614e8af98760f869d9e7ab0eb28749eca1b170d07222955f1990f5223c801fc03a9e2a2",
          "sha256": "06955bd27a452daf423fc87e6bae4dd723daae95ae1ae81a0fe673fd134f6058",
          "sha1": "44fd07cb2577ddf9e80f21742849cbff9ba93835",
          "md5": "3b2ee89aa98b4b065e7fa82930917c38"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-macosarm64-1.8.0-alpha01-metadata.jar",
          "url": "annotation-macosarm64-1.8.0-alpha01-metadata.jar",
          "size": 3785,
          "sha512": "c7cecf28374db4037b5c292cfae7926e2f2479e84c968810f34cc901d3117f7a656fe7f5aeba566b2b4c53d1e4ac0a54d88ba95e14e98357c59fc81616bb79cd",
          "sha256": "969349a47e999a7f66a1e5e862ae99950135d093f651179b5858b0bb5ebbbc79",
          "sha1": "87c59f5ce6bc9fc35c7775cfa17c8b8e9483b9fd",
          "md5": "cdf576f22010cfac56f4dbef83314bf3"
        }
      ]
    }
  ]
}