{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-test/1.6.0-alpha06-topping02/ui-test-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.ui",
    "module": "ui-test",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-desktop-1.6.0-alpha06-topping02.jar",
          "url": "ui-test-desktop-1.6.0-alpha06-topping02.jar",
          "size": 314380,
          "sha512": "39b027c276d3fc604724ae30d4f80d1c1494397c3379bf6080b3fc3304b9d337f6a9c5021ca552bc77123310d090a0b19027df796c106d249b03e07ed953695d",
          "sha256": "fd52f80a444c83e833d2391748146b645508165265e395165b6bd5f9128dc86c",
          "sha1": "09795046119ffec11149c28cc6436d8a060bf0d9",
          "md5": "ffd9439be03b9a3446e3df341d2d0053"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko-awt",
          "version": {
            "requires": "0.7.81"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-desktop-1.6.0-alpha06-topping02.jar",
          "url": "ui-test-desktop-1.6.0-alpha06-topping02.jar",
          "size": 314380,
          "sha512": "39b027c276d3fc604724ae30d4f80d1c1494397c3379bf6080b3fc3304b9d337f6a9c5021ca552bc77123310d090a0b19027df796c106d249b03e07ed953695d",
          "sha256": "fd52f80a444c83e833d2391748146b645508165265e395165b6bd5f9128dc86c",
          "sha1": "09795046119ffec11149c28cc6436d8a060bf0d9",
          "md5": "ffd9439be03b9a3446e3df341d2d0053"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-test-desktop-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-test-desktop-1.6.0-alpha06-topping02-sources.jar",
          "size": 97601,
          "sha512": "90158d3a084b0ba49328c187ec30df9f1e1d69b1a1292a9aad02dbd2d3b0ba4d56e2d996e56789279e06f39bc09fea8f412f4957ed8e6826d4b78a4ae5a00e4d",
          "sha256": "67a818cd00763fa443517129a20626db86e0e2017a69009c0db562629640161d",
          "sha1": "61f33d7b47a5a78a44a4648ec359f25215bb1207",
          "md5": "8a11811bd2d07689aacfa37c8084f206"
        }
      ]
    }
  ]
}