{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.8.0-alpha01.aar",
          "url": "navigation-runtime-ktx-2.8.0-alpha01.aar",
          "size": 2148,
          "sha512": "12daef3593a7cf5142df09137aa85fe31ae23fa6f92f73ff37c60cbd7993307c62b4480ca7386486be5e952d9f186503187e7fec02e41ff6dd16d1d41d511152",
          "sha256": "783bc038f503c26b0d100a3bc355619bbf592bf2d094269c25c45f48dc748e7e",
          "sha1": "ef87534ff95d09c5af55de2ee0e8bf2a419e6cce",
          "md5": "41881c20b774b113e609e07e0a4d781b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.8.0-alpha01.aar",
          "url": "navigation-runtime-ktx-2.8.0-alpha01.aar",
          "size": 2148,
          "sha512": "12daef3593a7cf5142df09137aa85fe31ae23fa6f92f73ff37c60cbd7993307c62b4480ca7386486be5e952d9f186503187e7fec02e41ff6dd16d1d41d511152",
          "sha256": "783bc038f503c26b0d100a3bc355619bbf592bf2d094269c25c45f48dc748e7e",
          "sha1": "ef87534ff95d09c5af55de2ee0e8bf2a419e6cce",
          "md5": "41881c20b774b113e609e07e0a4d781b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.8.0-alpha01-sources.jar",
          "url": "navigation-runtime-ktx-2.8.0-alpha01-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.8.0-alpha01-versionMetadata.json",
          "url": "navigation-runtime-ktx-2.8.0-alpha01-versionMetadata.json",
          "size": 2839,
          "sha512": "7217a5c665e4d0a448aed41692f2864d65cdaa3e8ff6ad3b60830069ffa5ceef900e245a2b5e8405489b7d84a400df6cabca2ea06f913833ee7414182e179dbd",
          "sha256": "974a7ade0887f9b1a8142ac91041d064dd0792183a6a19ceb77a51215fc5f302",
          "sha1": "3002de81bae1156c51ab2e1a935b5becc7fb81c1",
          "md5": "20d32ff0cd1696e8714c00d84df9aedd"
        }
      ]
    }
  ]
}