{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-extended/1.6.0-alpha06-topping02/material-icons-extended-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.material",
    "module": "material-icons-extended",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-release.aar",
          "url": "material-icons-extended-android-1.6.0-alpha06-topping02.aar",
          "size": 36089334,
          "sha512": "f61680064868e102218222f9e3c92db19e4053fb4fe0f07699c38374ff86c80b64b5a7c85f895ccb71a84ffe79b11faef75798ffcb5df668ed9c4453ef05d65d",
          "sha256": "76948444c7985e74fd9482323797bb37645230ade48528fded8aefa431934cb0",
          "sha1": "c0cb288ab1f48dce2d7f81d4ee49e0ef1237c022",
          "md5": "64d48a009e6a6dd32dd93f524eb262d6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-release.aar",
          "url": "material-icons-extended-android-1.6.0-alpha06-topping02.aar",
          "size": 36089334,
          "sha512": "f61680064868e102218222f9e3c92db19e4053fb4fe0f07699c38374ff86c80b64b5a7c85f895ccb71a84ffe79b11faef75798ffcb5df668ed9c4453ef05d65d",
          "sha256": "76948444c7985e74fd9482323797bb37645230ade48528fded8aefa431934cb0",
          "sha1": "c0cb288ab1f48dce2d7f81d4ee49e0ef1237c022",
          "md5": "64d48a009e6a6dd32dd93f524eb262d6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "material-icons-extended-android-1.6.0-alpha06-topping02-sources.jar",
          "url": "material-icons-extended-android-1.6.0-alpha06-topping02-sources.jar",
          "size": 12080783,
          "sha512": "5d0b09db16bf09809f582f749d1b93543b3c47b55bc2a65b67a36120e8758b0ab24f322a6f307441e0cefba3d12f14573575afebafae480466f1ec04a4534d22",
          "sha256": "35289e3d5752507a4acb790db571f23c0d58c1490522bf7c656df06cf7e25981",
          "sha1": "6f4948306bce90951b9a3f2158e2d158b0a997e6",
          "md5": "e5e9865cbb276c8d128a772e52b830cc"
        }
      ]
    }
  ]
}