{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-extended/1.6.0-alpha06-topping01/material-icons-extended-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.material",
    "module": "material-icons-extended",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-release.aar",
          "url": "material-icons-extended-android-1.6.0-alpha06-topping01.aar",
          "size": 36089334,
          "sha512": "1770b30a8e257ef3e9c60ae2b5655452a63a4a503b4577f2e6e27988037e181740a4671acb72f13cad67e273c1d2259a7340f4d65391dfb11593003ce96e9881",
          "sha256": "b662ab709238ad0f25eb36aa026a9b1cb11dcd5832a39f569b3bca4e83527fa3",
          "sha1": "f31f11412f466a7e7c735db18cc1901de7a1a1c0",
          "md5": "e1066c88a8e6d32033c3dbb9e792d07a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-release.aar",
          "url": "material-icons-extended-android-1.6.0-alpha06-topping01.aar",
          "size": 36089334,
          "sha512": "1770b30a8e257ef3e9c60ae2b5655452a63a4a503b4577f2e6e27988037e181740a4671acb72f13cad67e273c1d2259a7340f4d65391dfb11593003ce96e9881",
          "sha256": "b662ab709238ad0f25eb36aa026a9b1cb11dcd5832a39f569b3bca4e83527fa3",
          "sha1": "f31f11412f466a7e7c735db18cc1901de7a1a1c0",
          "md5": "e1066c88a8e6d32033c3dbb9e792d07a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "material-icons-extended-android-1.6.0-alpha06-topping01-sources.jar",
          "url": "material-icons-extended-android-1.6.0-alpha06-topping01-sources.jar",
          "size": 12080783,
          "sha512": "5d0b09db16bf09809f582f749d1b93543b3c47b55bc2a65b67a36120e8758b0ab24f322a6f307441e0cefba3d12f14573575afebafae480466f1ec04a4534d22",
          "sha256": "35289e3d5752507a4acb790db571f23c0d58c1490522bf7c656df06cf7e25981",
          "sha1": "6f4948306bce90951b9a3f2158e2d158b0a997e6",
          "md5": "e5e9865cbb276c8d128a772e52b830cc"
        }
      ]
    }
  ]
}