{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-viewbinding",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-viewbinding-1.6.0-alpha06-topping01.aar",
          "url": "ui-viewbinding-1.6.0-alpha06-topping01.aar",
          "size": 17988,
          "sha512": "0321ba9bcba027037e58e6a9e318341bb9d9688a09e872c0dbbb6f9e8914294a84bfed3cb641bdb286526e9dcffb2723d570998ef1bfbe8ce9e68042ef80b745",
          "sha256": "4c742a3a4c57d009a94a531e43a62a612f41df19ede651e2be36b9bf0c305bdc",
          "sha1": "a0a50c9a3a983ed8c3707a59e3f45cefbf87a20a",
          "md5": "0ecc60c8306629eb861d01c494734e24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-viewbinding-1.6.0-alpha06-topping01.aar",
          "url": "ui-viewbinding-1.6.0-alpha06-topping01.aar",
          "size": 17988,
          "sha512": "0321ba9bcba027037e58e6a9e318341bb9d9688a09e872c0dbbb6f9e8914294a84bfed3cb641bdb286526e9dcffb2723d570998ef1bfbe8ce9e68042ef80b745",
          "sha256": "4c742a3a4c57d009a94a531e43a62a612f41df19ede651e2be36b9bf0c305bdc",
          "sha1": "a0a50c9a3a983ed8c3707a59e3f45cefbf87a20a",
          "md5": "0ecc60c8306629eb861d01c494734e24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-viewbinding-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-viewbinding-1.6.0-alpha06-topping01-sources.jar",
          "size": 4544,
          "sha512": "55413dd610614314828023d9b9828512c7818791cfa0927b839ff7169111a3803f7cbb06b15fba9fd4345221da054fa94833f08adb54b5caaa5d4950fec1eaf6",
          "sha256": "b499af98f42ca96df7efe0216ca1e1d8d5a8a7bd64c6344eb5566b7b0e165489",
          "sha1": "b0c811d5f9903513697808065eb41af8952b2d86",
          "md5": "0280c4576ac10d0bf525aa56cf2dd711"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "ui-viewbinding-1.6.0-alpha06-topping01-versionMetadata.json",
          "url": "ui-viewbinding-1.6.0-alpha06-topping01-versionMetadata.json",
          "size": 846,
          "sha512": "6c62500da82cc410a8a9805c3c9da0f4ce092d409b416d3687bda06c4ccc291f550969e6a887b58214e78f4170eca9f0063ef55998ea9696abc9b625915bf7e7",
          "sha256": "e4f0314f2fe5fd3a4393f7289126c4af201e334091509efa462e0476ad056897",
          "sha1": "f79dd0f6d6d2e6e2bd20857e878f5f3c39232fdc",
          "md5": "9207ec3d11b75b36aebb617d9b1323db"
        }
      ]
    }
  ]
}