{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material-core",
    "version": "1.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.3.0-alpha06.aar",
          "url": "compose-material-core-1.3.0-alpha06.aar",
          "size": 173886,
          "sha512": "d8b963677d7c1a4388d92b7dccd61b50ec4472a00ff92349e055b39c71d2b172a07d0eacfd220c17088964aad566181129439414f3e6aa09cc40681fd3a8ce31",
          "sha256": "3dd0395e69766abda0f4330695f0b0eb37a1e00a8314b38cd04e9c40067c60ef",
          "sha1": "8bda3afa875d28783380fa0adf7bd297e4e570ec",
          "md5": "a1412d45d666ccabb8bb385acec0725a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.3.0-alpha06.aar",
          "url": "compose-material-core-1.3.0-alpha06.aar",
          "size": 173886,
          "sha512": "d8b963677d7c1a4388d92b7dccd61b50ec4472a00ff92349e055b39c71d2b172a07d0eacfd220c17088964aad566181129439414f3e6aa09cc40681fd3a8ce31",
          "sha256": "3dd0395e69766abda0f4330695f0b0eb37a1e00a8314b38cd04e9c40067c60ef",
          "sha1": "8bda3afa875d28783380fa0adf7bd297e4e570ec",
          "md5": "a1412d45d666ccabb8bb385acec0725a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-material-core-1.3.0-alpha06-sources.jar",
          "url": "compose-material-core-1.3.0-alpha06-sources.jar",
          "size": 33036,
          "sha512": "78772bc69c119518a42431390230530bf59e5a8e18555bdc272830abaafc9155e2c5d46ce6f6e82c9f7226772e8076aebe34679366dacb0c2710f759f261117d",
          "sha256": "32b71c705a5020756168f8d9a9d8e7af243b872517a46196367c9f90624d2315",
          "sha1": "e9e162d9c4b059f505d8acbc0f2f767bdec9953b",
          "md5": "fc8f59968a3535055dca8ed4afc4483d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "compose-material-core-1.3.0-alpha06-versionMetadata.json",
          "url": "compose-material-core-1.3.0-alpha06-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}