{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-core/1.6.0-alpha06-topping01/material-icons-core-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core.klib",
          "url": "material-icons-core-iosx64-1.6.0-alpha06-topping01.klib",
          "size": 353179,
          "sha512": "a3907f2fdc761e7b7e64de6fc8c0a9132b0634d34a2584b025191e80d313a63e185bdfe89cca137b613ac6388766a7a3986006fa48873fd0c5c96f968c75099a",
          "sha256": "26b8391e1e9303148cf24ce580ca7dd6e46b6ea4bc1829d7ad121a5af97093e9",
          "sha1": "c5abd5feaa64641b43f4607488bfafd1af3ad2b6",
          "md5": "24b0efa97c34adf9d56b994717fde651"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material-icons-core-iosx64-1.6.0-alpha06-topping01-sources.jar",
          "url": "material-icons-core-iosx64-1.6.0-alpha06-topping01-sources.jar",
          "size": 283974,
          "sha512": "02d465292fe52dead7601c1ee5f5823f267fb2aeff6e6252c86e42f68a4810fd00cede92c047182a475041f1ef077358bbdfa9ed13a1fe3cce5d7713a485c704",
          "sha256": "38663dc3908f433c7704b02fe77e26179319d9a36a632df238fa5bbdfbe07710",
          "sha1": "f6d8ca49ccaa1ac695f9156ffc6a4e43b8b221b2",
          "md5": "f034303c181015a75e68965be14aca8e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-iosx64-1.6.0-alpha06-topping01-metadata.jar",
          "url": "material-icons-core-iosx64-1.6.0-alpha06-topping01-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}