{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout-samples",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "foundation-layout-samples-1.6.0-alpha06-topping02.aar",
          "url": "foundation-layout-samples-1.6.0-alpha06-topping02.aar",
          "size": 257393,
          "sha512": "06ee11068d51f9c3c1403b901168b6dd086623d16cb39bf6ceaec508093cc349cf6ab0a48e11ad0044c9d09451acf1d545a1daf7240b94d96f31d149d36279e6",
          "sha256": "662af7a0153a24614d37653003e0da08cd727caa045ca0e9c8f3ed0585c10d26",
          "sha1": "7a6234dc4891e80413a1caed101ac3c7b0e06d2e",
          "md5": "cb94067957c0f80b8358da5c0d96a5c1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.6.0-alpha06-topping02.aar",
          "url": "foundation-layout-samples-1.6.0-alpha06-topping02.aar",
          "size": 257393,
          "sha512": "06ee11068d51f9c3c1403b901168b6dd086623d16cb39bf6ceaec508093cc349cf6ab0a48e11ad0044c9d09451acf1d545a1daf7240b94d96f31d149d36279e6",
          "sha256": "662af7a0153a24614d37653003e0da08cd727caa045ca0e9c8f3ed0585c10d26",
          "sha1": "7a6234dc4891e80413a1caed101ac3c7b0e06d2e",
          "md5": "cb94067957c0f80b8358da5c0d96a5c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-layout-samples-1.6.0-alpha06-topping02-sources.jar",
          "url": "foundation-layout-samples-1.6.0-alpha06-topping02-sources.jar",
          "size": 20582,
          "sha512": "6b054d6d895522c8a7733b13cfc778779b25c212e86f183633f88faa7f6b10626c98794a13efbaf142e1feb8e0cff2fb9ecfa15b66da6d23f16d838053adf7e7",
          "sha256": "ccfcd98ecc12bf9e2029170817af13ec3ebd83272a1d663e25fd7887b77773aa",
          "sha1": "3cc027732a2dd20211d0965d321a3288e0a02eab",
          "md5": "2fc34ea21b9d8c892a1ac21203ac8bb3"
        }
      ]
    }
  ]
}