{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01.aar",
          "url": "recyclerview-1.4.0-alpha01.aar",
          "size": 423734,
          "sha512": "0acf2437bda0e7cc3cd77728c68446b4efcfcb0632746abf69dbb74f55ce943fa55cf900aee1891c7517dee14be29266732fe431f59175d01a766f38b33a3f86",
          "sha256": "83057689e2928040fc45bc6e7d4360a2b581fd34c2fcc18b7a6940f6b3cb1a5e",
          "sha1": "5f5a8f0d325b82baf8ba7c323877f8d62ce16796",
          "md5": "6bcb39a15126f658c8ef85733e676a6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01.aar",
          "url": "recyclerview-1.4.0-alpha01.aar",
          "size": 423734,
          "sha512": "0acf2437bda0e7cc3cd77728c68446b4efcfcb0632746abf69dbb74f55ce943fa55cf900aee1891c7517dee14be29266732fe431f59175d01a766f38b33a3f86",
          "sha256": "83057689e2928040fc45bc6e7d4360a2b581fd34c2fcc18b7a6940f6b3cb1a5e",
          "sha1": "5f5a8f0d325b82baf8ba7c323877f8d62ce16796",
          "md5": "6bcb39a15126f658c8ef85733e676a6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01-sources.jar",
          "url": "recyclerview-1.4.0-alpha01-sources.jar",
          "size": 338240,
          "sha512": "0ec8b583742194df8980ef600ecf72c5143470f5f86aeeae142e70bef283f75a587e5c07e55353fb4e3eac9e5b31afcb5478fd4b20054b713a306da6dc36cb35",
          "sha256": "72685f9ad9adb0bc112843f72ac3528e9197b0010b9037eff534fdd09aff50cc",
          "sha1": "958e7d143640e38e6d81a6d54e7242ef56841d91",
          "md5": "da7744e64d139b0cb561e035759b7e56"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01-versionMetadata.json",
          "url": "recyclerview-1.4.0-alpha01-versionMetadata.json",
          "size": 93562,
          "sha512": "ae1b4073dafc10fbe3efe310ded2d9e6c998eeacfeaa15d09269dcaaf8bc5496e54b3782a7e92a245034470547a1824b674d2be5a2e9f869a00cd4e0ec74c132",
          "sha256": "2b684c773e5903f4024b162967ae75586f57c1c43b8e71a278071f8892d6e099",
          "sha1": "d21bdda0fba4bde71e1744bdbbe6ac25de2d8784",
          "md5": "6e8213775ffef3bb672b50372a4a9d98"
        }
      ]
    }
  ]
}