{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "runtime-1.6.0-alpha06-topping02-multiplatform-sources.jar",
          "url": "runtime-1.6.0-alpha06-topping02-multiplatform-sources.jar",
          "size": 382455,
          "sha512": "05f7235f0096c0480af8f1d147dff6f9be20d4a98ded14d677eea155e78a7a4c98b16444683ad381f6f543eb7ab3797ccbe0442760f9d1fb8b0a60ae14897187",
          "sha256": "514cf5b8ead92f20a255f8eb85460aac77711815704666ba312c2a826afbdca5",
          "sha1": "5e8d9ec53504144296b89919178b957e67132ffd",
          "md5": "8a29f39f18969da0268a6de355212ba4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "runtime-1.6.0-alpha06-topping02-versionMetadata.json",
          "size": 62920,
          "sha512": "1dc979f9836aefc065601fd6d7a6bfc6cfe50f4bd17e08fd96164fcec934fcebf5ab0c8f13bd17dbda7f096b48fd579150c197b14c3e679bdca74a0c4ebba5b5",
          "sha256": "05b5e4f007ba7a64e14541b2e7c0c9fb862aec28c9439281a3cb15d6ff3ceb29",
          "sha1": "effad33f6be34926021b66895e14799b9eaad755",
          "md5": "789b3765c2571e0e94873fcc67c7884b"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-metadata-1.6.0-alpha06-topping02.jar",
          "url": "runtime-1.6.0-alpha06-topping02.jar",
          "size": 91923,
          "sha512": "28032c44fdc97e22648461b7be1d92dadeb99b8f10b2da6c9362a6312b43b9a6eb9eb829e1ea8c62f209cc42ea1964d18479952fecc905e179707ccda4d5f98b",
          "sha256": "5c1ba695d0c9f2349f7c927e9ced3edda15c51aa36291543016979eac2fe52fa",
          "sha1": "f8cd342850380d5ee183ed826ad91cebf0b9e16c",
          "md5": "b69b7c398ac6afd37d02abe54d17d8c6"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-kotlin-1.6.0-alpha06-topping02-sources.jar",
          "url": "runtime-1.6.0-alpha06-topping02-sources.jar",
          "size": 367562,
          "sha512": "cc515a35567a5670f0d7a7241dd77181bcb8cc5339a299f751830dcabaa5add9575eb7ba92d3a7063b6efb918c5425346510a436c1a3416d460d5b714bf832b3",
          "sha256": "7d937da5ce78f8c159fe245863e9e0160243f942b9115355a706fb22e9003b56",
          "sha1": "cb435edba775085e5c3d8c4b5214184c3d68bb6b",
          "md5": "a2de8e4c23413ea7d86d70fd935d24df"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-android/1.6.0-alpha06-topping02/runtime-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-android/1.6.0-alpha06-topping02/runtime-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-android/1.6.0-alpha06-topping02/runtime-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-desktop/1.6.0-alpha06-topping02/runtime-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-desktop/1.6.0-alpha06-topping02/runtime-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-desktop/1.6.0-alpha06-topping02/runtime-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/1.6.0-alpha06-topping02/runtime-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/1.6.0-alpha06-topping02/runtime-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosarm64/1.6.0-alpha06-topping02/runtime-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/1.6.0-alpha06-topping02/runtime-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/1.6.0-alpha06-topping02/runtime-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iossimulatorarm64/1.6.0-alpha06-topping02/runtime-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/1.6.0-alpha06-topping02/runtime-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/1.6.0-alpha06-topping02/runtime-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-iosx64/1.6.0-alpha06-topping02/runtime-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    }
  ]
}