{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose-samples",
    "version": "2.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "navigation-compose-samples-2.8.0-alpha01.aar",
          "url": "navigation-compose-samples-2.8.0-alpha01.aar",
          "size": 119723,
          "sha512": "3e2fc51e70067e7b555edfa75c59301b4e207317695325929cd73cffda41b826736e2544b698343b119367bdcf8e807db3a998c6a5634e990ce50bc25ca2f613",
          "sha256": "7499e7284ebe2a96e8410dd7b60b8627d3cb7f669b6caedcb8df878fae935e36",
          "sha1": "d080ac9189aa8557856fb5ad1ebbd3bd20fe3f08",
          "md5": "e0515eba99eff5ebf76616569b8b7636"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-samples-2.8.0-alpha01.aar",
          "url": "navigation-compose-samples-2.8.0-alpha01.aar",
          "size": 119723,
          "sha512": "3e2fc51e70067e7b555edfa75c59301b4e207317695325929cd73cffda41b826736e2544b698343b119367bdcf8e807db3a998c6a5634e990ce50bc25ca2f613",
          "sha256": "7499e7284ebe2a96e8410dd7b60b8627d3cb7f669b6caedcb8df878fae935e36",
          "sha1": "d080ac9189aa8557856fb5ad1ebbd3bd20fe3f08",
          "md5": "e0515eba99eff5ebf76616569b8b7636"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-compose-samples-2.8.0-alpha01-sources.jar",
          "url": "navigation-compose-samples-2.8.0-alpha01-sources.jar",
          "size": 3989,
          "sha512": "6b5e353a91f55c7aed9c82c20e1b4218bbaa020a319dc31428b5b0a52bd571223a15e66bda1b0c56aa76960ce096b6867db064415883d38db6651844c5707e66",
          "sha256": "c90698cb38e14a6ba019fcf4460ae944c0083db440e22021015e7f85455dbcb9",
          "sha1": "4feb29b624f685c301e5801e571dece548b631b8",
          "md5": "7efffd5e0c15a7b7fa54a250c6482a99"
        }
      ]
    }
  ]
}