{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-samples",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "material-samples-1.6.0-alpha06-topping02.aar",
          "url": "material-samples-1.6.0-alpha06-topping02.aar",
          "size": 1043565,
          "sha512": "e6db2c3086cbdf2a5cbbbeb92b7780a2aa722d7e65105963c2395a1de784392564b77ae29fba0a863052a27385647421a609c08f94ecc240c76db2df6f490af5",
          "sha256": "bd1572a435e3a330cdc23cc85e6e9141b36ec679d693f6655603b812ade51156",
          "sha1": "961bab2ab3097debf763d3bd310e9701b6e5510c",
          "md5": "09f733b84c2803e4fb4aa7ff109f7bdd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-samples-1.6.0-alpha06-topping02.aar",
          "url": "material-samples-1.6.0-alpha06-topping02.aar",
          "size": 1043565,
          "sha512": "e6db2c3086cbdf2a5cbbbeb92b7780a2aa722d7e65105963c2395a1de784392564b77ae29fba0a863052a27385647421a609c08f94ecc240c76db2df6f490af5",
          "sha256": "bd1572a435e3a330cdc23cc85e6e9141b36ec679d693f6655603b812ade51156",
          "sha1": "961bab2ab3097debf763d3bd310e9701b6e5510c",
          "md5": "09f733b84c2803e4fb4aa7ff109f7bdd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-samples-1.6.0-alpha06-topping02-sources.jar",
          "url": "material-samples-1.6.0-alpha06-topping02-sources.jar",
          "size": 43989,
          "sha512": "f134b5f61af477fe5dc505b99599feffd98b75705ae2ad2a6537aa341ad042c69d1703f720f15d0c140be4325a7d2b80f18cebce5a90cfa9ee272601d072ee75",
          "sha256": "534cf349f15199c647d8aedbfc1304326b7f4ca0d769aed759c94baae6daa655",
          "sha1": "bb333d2cae028b8c19692cb78bc2397ebbacdb25",
          "md5": "2ce2c5e0856c22bdc49d799090616579"
        }
      ]
    }
  ]
}