{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-navigation-samples",
    "version": "1.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compose-navigation-samples-1.3.0-alpha06.aar",
          "url": "compose-navigation-samples-1.3.0-alpha06.aar",
          "size": 40835,
          "sha512": "a6ada542ae40271f9e4912d7d27285e0ea10559019d6614b964a859b3c0cbcf436178a228419aa7d0114864da288abed9d2e5a106931ae7931f4cd38c26f36de",
          "sha256": "5f88c283549ceb2b5d5d9eb15d2a69a1e1dfe9a4cabef0d9835e60325d40ccc9",
          "sha1": "1372b58895294faf609998a2d080a041e1cac5f1",
          "md5": "5da55e8d80c23c10826e871bb19819e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "compose-navigation-samples-1.3.0-alpha06.aar",
          "url": "compose-navigation-samples-1.3.0-alpha06.aar",
          "size": 40835,
          "sha512": "a6ada542ae40271f9e4912d7d27285e0ea10559019d6614b964a859b3c0cbcf436178a228419aa7d0114864da288abed9d2e5a106931ae7931f4cd38c26f36de",
          "sha256": "5f88c283549ceb2b5d5d9eb15d2a69a1e1dfe9a4cabef0d9835e60325d40ccc9",
          "sha1": "1372b58895294faf609998a2d080a041e1cac5f1",
          "md5": "5da55e8d80c23c10826e871bb19819e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-navigation-samples-1.3.0-alpha06-sources.jar",
          "url": "compose-navigation-samples-1.3.0-alpha06-sources.jar",
          "size": 2364,
          "sha512": "065b0152bf897358488b8b2f8edf2ef7a8c14bfa1ded5817f146ee73573f5829337147bfc8e9c97a4fde94cda0adb42b45219cfb5bf1c1eaee3eaba66348a5e3",
          "sha256": "43def87d57521a97147191bc7d994774e052c5732b3931002bdde96d38e3c265",
          "sha1": "ea021b01343e577df1b4babda03816c02ceeb131",
          "md5": "778163b513fc6800f0fb0274441e5869"
        }
      ]
    }
  ]
}