{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-geometry/1.6.0-alpha06-topping01/ui-geometry-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.ui",
    "module": "ui-geometry",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry.klib",
          "url": "ui-geometry-iossimulatorarm64-1.6.0-alpha06-topping01.klib",
          "size": 52824,
          "sha512": "fdb8c32760ebbaa64e54d1ae6e6c9f35b87ea4786a331a2fc90d76e93d2aeaf6537e9214a0ab4a8717df043d18b913ad387ff8ddae8ae130b7dac5573e3c27f8",
          "sha256": "24c9bd8203d1e08ce25e7722931e97c2b51bbe74d1da2c20c2f5419f876e3c2d",
          "sha1": "f8a877b879f8ffa6d0a6defcaf28895e4273a250",
          "md5": "a523242bb1809029f7f41912caad3c36"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-geometry-iossimulatorarm64-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-geometry-iossimulatorarm64-1.6.0-alpha06-topping01-sources.jar",
          "size": 18278,
          "sha512": "9ea87e8be182c050396a1db751a23fd5e1aebede9e8ecfbc812801a831aa9f5106ce9a2a751eb2714b03e60fceffd2b55d5cbea57d83c58e1f0530d36b04c8d6",
          "sha256": "1cdb444bb73105531a91ef3b12098ada9392653e9ffc3d8d79ded19caa19253e",
          "sha1": "52669a9505a8bbcfa60523b6c52000050e3000d9",
          "md5": "13d5ab5d38f1f14f28c5ac635ebdccb5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-iossimulatorarm64-1.6.0-alpha06-topping01-metadata.jar",
          "url": "ui-geometry-iossimulatorarm64-1.6.0-alpha06-topping01-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}