{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling-preview/1.6.0-alpha06-topping01/ui-tooling-preview-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-desktop-1.6.0-alpha06-topping01.jar",
          "url": "ui-tooling-preview-desktop-1.6.0-alpha06-topping01.jar",
          "size": 1863,
          "sha512": "8b5d5d8711a001052b1e132e3de7f477295817b54431bb6f6ccbca28cd8fd6c8196cf0d43fcea8038b3ac3d1e45045f057c370ba468e7fc48b278107f2a65819",
          "sha256": "1b531c5ec345d60ff880895988e065c39b4d42c3e2cf57f811c2daa7fb2c7322",
          "sha1": "16e8e3a0dd0d52b5e4877a54bc345668ba23428d",
          "md5": "90fb251bf3b708b5c6ef36ea9591a46f"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-desktop-1.6.0-alpha06-topping01.jar",
          "url": "ui-tooling-preview-desktop-1.6.0-alpha06-topping01.jar",
          "size": 1863,
          "sha512": "8b5d5d8711a001052b1e132e3de7f477295817b54431bb6f6ccbca28cd8fd6c8196cf0d43fcea8038b3ac3d1e45045f057c370ba468e7fc48b278107f2a65819",
          "sha256": "1b531c5ec345d60ff880895988e065c39b4d42c3e2cf57f811c2daa7fb2c7322",
          "sha1": "16e8e3a0dd0d52b5e4877a54bc345668ba23428d",
          "md5": "90fb251bf3b708b5c6ef36ea9591a46f"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-tooling-preview-desktop-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-tooling-preview-desktop-1.6.0-alpha06-topping01-sources.jar",
          "size": 1968,
          "sha512": "9df0d11e29b1bd1e14e68f401e7722bda9eec2f69c460c6c009a6d50159ad1bcf89ebf7cae92fc207eb46d004809d49198d79d00bdcc8d5074b55443bda78a26",
          "sha256": "11ed81a47f7a9e5d009e7cc654ae2917c301d0588d0ad3c2d195dc6c5aef0fa5",
          "sha1": "e6e2e2150e90e79dfe3e60571eca99211941f24a",
          "md5": "d7347c6976ae21958dba13ac8bede40a"
        }
      ]
    }
  ]
}