{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotation/1.8.0-alpha01/annotation-1.8.0-alpha01.module",
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation.klib",
          "url": "annotation-iosx64-1.8.0-alpha01.klib",
          "size": 17608,
          "sha512": "a9782df4a1e8ca39ad0fb1230b908ef330328fdbacf8df390d0bb7e4c1a52f07f61d67c4792205efb77cc070770fa38f588f76e11b7986a2015bdbc2fc2068a6",
          "sha256": "ce1c00ecae40ac9c8cc490a4d885f48887d791fd823c83667740346f3172891f",
          "sha1": "2c5624aee2df516a6b6917646f3678a7fceb153f",
          "md5": "250fff89c7be8959a31d023cc4b83496"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "annotation-iosx64-1.8.0-alpha01-sources.jar",
          "url": "annotation-iosx64-1.8.0-alpha01-sources.jar",
          "size": 24319,
          "sha512": "a11e56e4d8a5d42398d5a203490a9bd86e64243e01786afb94036a48a614e8af98760f869d9e7ab0eb28749eca1b170d07222955f1990f5223c801fc03a9e2a2",
          "sha256": "06955bd27a452daf423fc87e6bae4dd723daae95ae1ae81a0fe673fd134f6058",
          "sha1": "44fd07cb2577ddf9e80f21742849cbff9ba93835",
          "md5": "3b2ee89aa98b4b065e7fa82930917c38"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-iosx64-1.8.0-alpha01-metadata.jar",
          "url": "annotation-iosx64-1.8.0-alpha01-metadata.jar",
          "size": 3785,
          "sha512": "c7cecf28374db4037b5c292cfae7926e2f2479e84c968810f34cc901d3117f7a656fe7f5aeba566b2b4c53d1e4ac0a54d88ba95e14e98357c59fc81616bb79cd",
          "sha256": "969349a47e999a7f66a1e5e862ae99950135d093f651179b5858b0bb5ebbbc79",
          "sha1": "87c59f5ce6bc9fc35c7775cfa17c8b8e9483b9fd",
          "md5": "cdf576f22010cfac56f4dbef83314bf3"
        }
      ]
    }
  ]
}