{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-unit/1.6.0-alpha06-topping01/ui-unit-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit.klib",
          "url": "ui-unit-iosx64-1.6.0-alpha06-topping01.klib",
          "size": 101157,
          "sha512": "c8c60f7a6e3ab06756b43936e73db3043129347df173a45ee0e89c43c64403936c567eeb162908324cdc0d4f97787e04ff20bd838dcc726770ffe960d09387d3",
          "sha256": "de4daedb517beba93066589b08e2f470261c3de42edbe62d103eb3d951a8c7d8",
          "sha1": "1ff55b3bd575235ba0e7e38dc7901f8eb72dc5ff",
          "md5": "5954468e0bede2e78277f57f3e385ebd"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-unit-iosx64-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-unit-iosx64-1.6.0-alpha06-topping01-sources.jar",
          "size": 36722,
          "sha512": "c148bbbdb075468d05fdd4a51e4f1301b563b975906a1a6688c8a1196f0411e58be4e858cc14f4c2137aceafd9c8ba0e29c7c4d467776cdb2105b3692f7f0732",
          "sha256": "cc05fa5292fcd5bc2d2ff4d84e7a218306f54a736c18e45bc3f0a7a181f7e7f7",
          "sha1": "aa53c2a79cc878f8be41544d41c05e722b44ff57",
          "md5": "d8f287b2fb3ca118a4948e609bf97bed"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-iosx64-1.6.0-alpha06-topping01-metadata.jar",
          "url": "ui-unit-iosx64-1.6.0-alpha06-topping01-metadata.jar",
          "size": 7354,
          "sha512": "6e173550faf544621348248e5cb0bf1e16da49971e1ce4a3cb2ec63636e556d2a5f6dcfef2743b28eedbd5e67052e837a235a4e7f6358527925f68a175cdb2e4",
          "sha256": "772353767002950d5a0f6cb902ea6c0e04fdcf692b60ffdac6965b2f8b022e65",
          "sha1": "44894d9b431177b075b822ffabebcc603817bc3b",
          "md5": "f4708f6dd484bc823d2215339c7ea6a7"
        }
      ]
    }
  ]
}