{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences-core",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-metadata-1.1.0-alpha05.jar",
          "url": "datastore-preferences-core-1.1.0-alpha05.jar",
          "size": 6464,
          "sha512": "179e4f151dea3788166275eaeb3b96e8bc0ad953a57e55698d46bdeb6fa0d858e5aed7984337e24521891c7dd891105de09a8444a54452e61ef2f1414dbdcab6",
          "sha256": "010ae8df6332be8c6d00c411489faf6fd2e6ccdb1f467fe005b86ea7e1f64d29",
          "sha1": "0d21d136daa8d6ee7660d31bd9fcd28daf73aee5",
          "md5": "fec392aa541092c8ad96659de7b05754"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "datastore-preferences-core-kotlin-1.1.0-alpha05-sources.jar",
          "url": "datastore-preferences-core-1.1.0-alpha05-sources.jar",
          "size": 15659,
          "sha512": "e7e59b7b8ecd68cbb45e9a9b4ad53eeeaa136cb6e4d2914accb9af38fb2ed21fa1e348b6d17a1a655c774865b5e71a784a94afb36c18d0d33c3c921756b5d983",
          "sha256": "eed57aef4e634afd7711cd67e5ac6740597fbd784d592b8f0cf0b1b4962f4fc9",
          "sha1": "236eb2d3b8275b61416080b6e59e2250b210cde6",
          "md5": "c69df6a8f7f9d84507b274df8e18d70c"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosarm64/1.1.0-alpha05/datastore-preferences-core-iosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosarm64/1.1.0-alpha05/datastore-preferences-core-iosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosarm64/1.1.0-alpha05/datastore-preferences-core-iosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iossimulatorarm64/1.1.0-alpha05/datastore-preferences-core-iossimulatorarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iossimulatorarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iossimulatorarm64/1.1.0-alpha05/datastore-preferences-core-iossimulatorarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iossimulatorarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iossimulatorarm64/1.1.0-alpha05/datastore-preferences-core-iossimulatorarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iossimulatorarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosx64/1.1.0-alpha05/datastore-preferences-core-iosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosx64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosx64/1.1.0-alpha05/datastore-preferences-core-iosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosx64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosx64/1.1.0-alpha05/datastore-preferences-core-iosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosx64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-jvm/1.1.0-alpha05/datastore-preferences-core-jvm-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-jvm",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-jvm/1.1.0-alpha05/datastore-preferences-core-jvm-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-jvm",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-jvm/1.1.0-alpha05/datastore-preferences-core-jvm-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-jvm",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosarm64/1.1.0-alpha05/datastore-preferences-core-macosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosarm64/1.1.0-alpha05/datastore-preferences-core-macosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosarm64/1.1.0-alpha05/datastore-preferences-core-macosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosx64/1.1.0-alpha05/datastore-preferences-core-macosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosx64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosx64/1.1.0-alpha05/datastore-preferences-core-macosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosx64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosx64/1.1.0-alpha05/datastore-preferences-core-macosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosx64",
        "version": "1.1.0-alpha05"
      }
    }
  ]
}