{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-unit/1.6.0-alpha06-topping02/ui-unit-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit.klib",
          "url": "ui-unit-iossimulatorarm64-1.6.0-alpha06-topping02.klib",
          "size": 101260,
          "sha512": "8cd9b6ce5d7b3d1fcfb168b63e43d0dd6c3751487d6168d7b9b9a29dcf0469c27c84e9b4e46bfe03edb8522c044b99c2a27e818516e3f1be8e0690653e44802b",
          "sha256": "e5e0a9b81954c67dfac0d4ffdf1b0290c7a4a994df7f8e0f00bfbfc52e3af375",
          "sha1": "548abfc12485c3f8103ac03c763b8ea2c2bc7d99",
          "md5": "b81bf0d9c3d75f9a090cb80ae1697935"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-unit-iossimulatorarm64-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-unit-iossimulatorarm64-1.6.0-alpha06-topping02-sources.jar",
          "size": 36722,
          "sha512": "c148bbbdb075468d05fdd4a51e4f1301b563b975906a1a6688c8a1196f0411e58be4e858cc14f4c2137aceafd9c8ba0e29c7c4d467776cdb2105b3692f7f0732",
          "sha256": "cc05fa5292fcd5bc2d2ff4d84e7a218306f54a736c18e45bc3f0a7a181f7e7f7",
          "sha1": "aa53c2a79cc878f8be41544d41c05e722b44ff57",
          "md5": "d8f287b2fb3ca118a4948e609bf97bed"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-iossimulatorarm64-1.6.0-alpha06-topping02-metadata.jar",
          "url": "ui-unit-iossimulatorarm64-1.6.0-alpha06-topping02-metadata.jar",
          "size": 7354,
          "sha512": "6e173550faf544621348248e5cb0bf1e16da49971e1ce4a3cb2ec63636e556d2a5f6dcfef2743b28eedbd5e67052e837a235a4e7f6358527925f68a175cdb2e4",
          "sha256": "772353767002950d5a0f6cb902ea6c0e04fdcf692b60ffdac6965b2f8b022e65",
          "sha1": "44894d9b431177b075b822ffabebcc603817bc3b",
          "md5": "f4708f6dd484bc823d2215339c7ea6a7"
        }
      ]
    }
  ]
}