{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kruth/1.1.0-alpha01/kruth-1.1.0-alpha01.module",
    "group": "androidx.kruth",
    "module": "kruth",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "kruth.klib",
          "url": "kruth-iosx64-1.1.0-alpha01.klib",
          "size": 86932,
          "sha512": "8f30dd0383c2a9ad7e098452a873bda785f0adbd8697455bf97b5d14f03cf058116774bc8c77e1d4c744f7ec908113d465abcfbc102d6a8b4e17ab07de338298",
          "sha256": "108b558c1e3e13e85e5b2125becb22a688a1af35990ce535e29201cc7eb45d1d",
          "sha1": "e17d26984dac628a544175b1fb21f47b68443a30",
          "md5": "0c9599abd67f238dd09c5177126d8f5c"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kruth-iosx64-1.1.0-alpha01-sources.jar",
          "url": "kruth-iosx64-1.1.0-alpha01-sources.jar",
          "size": 33159,
          "sha512": "5c2fc091f98c2c9dbb7a0d7dae8bc76b66ba2cf7989888632852ca149f55da14f562b899024afb3dc038510f580edd93eb903b81154957068195672197718d26",
          "sha256": "0b9d6eef9ca0280d0996faba25e86e3933e58ed1e9a7d0046f7366a0a92216fa",
          "sha1": "fc3ba1dc474d0db46cfb991196a688af078fd114",
          "md5": "ee832023af7fc44d2688188b06d275d4"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "kruth-iosx64-1.1.0-alpha01-metadata.jar",
          "url": "kruth-iosx64-1.1.0-alpha01-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}