{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-unit/1.6.0-alpha06-topping02/ui-unit-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-release.aar",
          "url": "ui-unit-android-1.6.0-alpha06-topping02.aar",
          "size": 84098,
          "sha512": "2e3b6236820c79a4b61fb35c0ab48e5559359d6b577a24bdcacf903a871b9c6801e3da4491b85c7cb2770380cd868f7387271cfd1d13b61194c344a6d29176d8",
          "sha256": "8edde2f3a12b370baf463514bb76ed618c4d953521ba2cd2636f5901ceaf1be4",
          "sha1": "7bb370708342d77b4c41b4dd1c7e4212acb24207",
          "md5": "abb33af4e80fefd82c1aab197a2b5260"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ui-unit-release.aar",
          "url": "ui-unit-android-1.6.0-alpha06-topping02.aar",
          "size": 84098,
          "sha512": "2e3b6236820c79a4b61fb35c0ab48e5559359d6b577a24bdcacf903a871b9c6801e3da4491b85c7cb2770380cd868f7387271cfd1d13b61194c344a6d29176d8",
          "sha256": "8edde2f3a12b370baf463514bb76ed618c4d953521ba2cd2636f5901ceaf1be4",
          "sha1": "7bb370708342d77b4c41b4dd1c7e4212acb24207",
          "md5": "abb33af4e80fefd82c1aab197a2b5260"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ui-unit-android-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-unit-android-1.6.0-alpha06-topping02-sources.jar",
          "size": 37412,
          "sha512": "5f5a752fbd746cf29e68cafaab54e1b20e3fc13bd80a150d09d16c7ee5107f890c0e401ca264a937ec8f05533b928c0d8d4e403e8f496448f235ab86e33e5f04",
          "sha256": "2b787af712f1de22c00cc16ef7c66cc0a6221dbe740c7f6c189dd322cfa10c9d",
          "sha1": "47d02b9ae75e6aacc2d86196c1c488f567c13a35",
          "md5": "288eaa07ef1e92bb8893b39802850567"
        }
      ]
    }
  ]
}