{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-util/1.6.0-alpha06-topping01/ui-util-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-util-desktop-1.6.0-alpha06-topping01.jar",
          "url": "ui-util-desktop-1.6.0-alpha06-topping01.jar",
          "size": 15695,
          "sha512": "ca7738bb281cfbd22994f87fc3bf582037430a4c7c0d58793e4948eaebd54a2c206b2fb7d5fa5b2df6b24537f21c10e3ac588a0782e3f797244cfbe52030eaf9",
          "sha256": "257b7346b8716dfef63aa2090ddd52a15db38b7afcb1221ca21e8b8222044713",
          "sha1": "6e872427b9a5e18735dc79c36da7524fe76444f6",
          "md5": "a8914285aad52a78e46349bddce930ed"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-desktop-1.6.0-alpha06-topping01.jar",
          "url": "ui-util-desktop-1.6.0-alpha06-topping01.jar",
          "size": 15695,
          "sha512": "ca7738bb281cfbd22994f87fc3bf582037430a4c7c0d58793e4948eaebd54a2c206b2fb7d5fa5b2df6b24537f21c10e3ac588a0782e3f797244cfbe52030eaf9",
          "sha256": "257b7346b8716dfef63aa2090ddd52a15db38b7afcb1221ca21e8b8222044713",
          "sha1": "6e872427b9a5e18735dc79c36da7524fe76444f6",
          "md5": "a8914285aad52a78e46349bddce930ed"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-util-desktop-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-util-desktop-1.6.0-alpha06-topping01-sources.jar",
          "size": 14285,
          "sha512": "e9dcb45af03cb40fbcb1b8e04b5a79ec222b95808494bfa323856ffbdef90231617999aae16aa9ab28345e27f851db4bd3813298bce30fe748630975ffcd9faf",
          "sha256": "0d7bd97932919f204dff16ee03e2e1cc7d916d85e145c73cc0612ebdad5325c4",
          "sha1": "f75395361fd31deedf94613543f7abccfce429a6",
          "md5": "fcbe0c8522f2c3e9fba123d99bf06cd3"
        }
      ]
    }
  ]
}