{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-graphics/1.6.0-alpha06-topping02/ui-graphics-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-release.aar",
          "url": "ui-graphics-android-1.6.0-alpha06-topping02.aar",
          "size": 1494111,
          "sha512": "7b172587e9321fd01c6bc0708526e4f3a17477007e5c82bfa40994d7301895dabe7411aa265a78fcef1c7dd6fcd7407f7b35944727f0c68cd4c32d577f801de1",
          "sha256": "c8ba18a04ee46400f3318d719175b0ad4205130ff63b26651aa3c8f6fbb0f37d",
          "sha1": "f73ca5496de6d75c03655ffd3fdd13652a9bd5ab",
          "md5": "51d23f88bbe86352163573d1549fbc36"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ui-graphics-release.aar",
          "url": "ui-graphics-android-1.6.0-alpha06-topping02.aar",
          "size": 1494111,
          "sha512": "7b172587e9321fd01c6bc0708526e4f3a17477007e5c82bfa40994d7301895dabe7411aa265a78fcef1c7dd6fcd7407f7b35944727f0c68cd4c32d577f801de1",
          "sha256": "c8ba18a04ee46400f3318d719175b0ad4205130ff63b26651aa3c8f6fbb0f37d",
          "sha1": "f73ca5496de6d75c03655ffd3fdd13652a9bd5ab",
          "md5": "51d23f88bbe86352163573d1549fbc36"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ui-graphics-android-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-graphics-android-1.6.0-alpha06-topping02-sources.jar",
          "size": 190474,
          "sha512": "8e0852aaf4d800f4c966741d7e2ac10327dfd7d2dae630fc536b36188901f5a0996d4b24628dd8e2e14ee4f6383d17fc7ed4631e6e59931153ce6d21fd75e13a",
          "sha256": "17fb5d19079620f79723e467bbc87e05a0bdde4f07ad733deabe378a1e9898cb",
          "sha1": "5c0ff9f641c7d160be493bd6681c3b113aa2d1ae",
          "md5": "d24d892726aa9c34978a86626d5854fb"
        }
      ]
    }
  ]
}