{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-manifest",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.6.0-alpha06-topping01.aar",
          "url": "ui-test-manifest-1.6.0-alpha06-topping01.aar",
          "size": 9402,
          "sha512": "32d838ad24301662e1c3133bb560a6174ab04bb6ea2e9cc860b8db80b544ac1ba0aedaa869512128421c030f776e39e9557c1f282062d59ab924cbbb32ae0084",
          "sha256": "c0e5b17c1889304b611025d0734a0d8c739260f03de6ba77760296dfcb66a99f",
          "sha1": "c050ed89bbd40b9c625a28b38754b642d3948d68",
          "md5": "b644694db3f14c6e235cf8458d26f277"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.6.0-alpha06-topping01.aar",
          "url": "ui-test-manifest-1.6.0-alpha06-topping01.aar",
          "size": 9402,
          "sha512": "32d838ad24301662e1c3133bb560a6174ab04bb6ea2e9cc860b8db80b544ac1ba0aedaa869512128421c030f776e39e9557c1f282062d59ab924cbbb32ae0084",
          "sha256": "c0e5b17c1889304b611025d0734a0d8c739260f03de6ba77760296dfcb66a99f",
          "sha1": "c050ed89bbd40b9c625a28b38754b642d3948d68",
          "md5": "b644694db3f14c6e235cf8458d26f277"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-manifest-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-test-manifest-1.6.0-alpha06-topping01-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "ui-test-manifest-1.6.0-alpha06-topping01-versionMetadata.json",
          "url": "ui-test-manifest-1.6.0-alpha06-topping01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}