{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/1.6.0-alpha06-topping01/material-ripple-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple.klib",
          "url": "material-ripple-iosarm64-1.6.0-alpha06-topping01.klib",
          "size": 42352,
          "sha512": "73f440a50a2b630f0ede09fd5286aadb32739a63366ad434d652e65842a7f605ff461afb6c3b0265bfc252479f7da35441ab77c1bdaedce2c23b598f75a92439",
          "sha256": "c66d0ecc1ee32e8ae66c06529e45a44228d89f51f4d747317946ef6cadab0833",
          "sha1": "a197d4860fb12d7460d7d9718ef40b5539fcbe6c",
          "md5": "290b8bb4aaa5d0163a91a700a991e443"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material-ripple-iosarm64-1.6.0-alpha06-topping01-sources.jar",
          "url": "material-ripple-iosarm64-1.6.0-alpha06-topping01-sources.jar",
          "size": 12374,
          "sha512": "3bfc833078586218ebd54d6422c35b579d28df07e66b52bc0ce154d023ab7a16be8159160a119951c5574341e483ee723c360ae0265770a449cf002714af781c",
          "sha256": "37c61ee00e6e0fa74c5fd7b50ae2abccfa65fe6571eb41132c5d5b416eb107fc",
          "sha1": "3d9e912c89f9fe8a07979dfdaedc2935673def9b",
          "md5": "b2ff47b69a3c93878af7b64ffe16c4ae"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-iosarm64-1.6.0-alpha06-topping01-metadata.jar",
          "url": "material-ripple-iosarm64-1.6.0-alpha06-topping01-metadata.jar",
          "size": 4102,
          "sha512": "a71ac1e6598c60ecb8b95438efe1ee24ac1c6cf5b5c573e4ae5d25e9e9ee36d00fc9efe0fe8598e39c4a1253f0863bd48c5b4728de824b559af2806318c05fbc",
          "sha256": "664c4e5459d7bacd12edbc5533a04124e7e0a61d19c44a4f5ee375f8a5ffef10",
          "sha1": "4123963ce2fc84d54b8d9e28c84723b718ec3496",
          "md5": "7ff95bee9bf88675f5039b462c4ffe6d"
        }
      ]
    }
  ]
}