{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-livedata-samples",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runtime-livedata-samples-1.6.0-alpha06-topping01.aar",
          "url": "runtime-livedata-samples-1.6.0-alpha06-topping01.aar",
          "size": 6413,
          "sha512": "62a2e95d277958eb649621cab66d66187392be2a86e8377e7dcb01a637ec8a05dc5b222281a4e7ce68b9d563b667784dbed3195024bf58afa0d740b03545b3ec",
          "sha256": "5316c5463879fd1eaccbcc59eb54b4973235198bf7fc3fb0c1aa6c1e99ae99d1",
          "sha1": "9e835be9d1570542a97b6c317d9a650bec8bd844",
          "md5": "94a240a428e9a6c96173cc4ae9c02f59"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-samples-1.6.0-alpha06-topping01.aar",
          "url": "runtime-livedata-samples-1.6.0-alpha06-topping01.aar",
          "size": 6413,
          "sha512": "62a2e95d277958eb649621cab66d66187392be2a86e8377e7dcb01a637ec8a05dc5b222281a4e7ce68b9d563b667784dbed3195024bf58afa0d740b03545b3ec",
          "sha256": "5316c5463879fd1eaccbcc59eb54b4973235198bf7fc3fb0c1aa6c1e99ae99d1",
          "sha1": "9e835be9d1570542a97b6c317d9a650bec8bd844",
          "md5": "94a240a428e9a6c96173cc4ae9c02f59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-livedata-samples-1.6.0-alpha06-topping01-sources.jar",
          "url": "runtime-livedata-samples-1.6.0-alpha06-topping01-sources.jar",
          "size": 1663,
          "sha512": "df61b16d35a620cd57828cc45aa134a5dc4d565d6bcff8dfc4d2e8e65d4ac3a60bfe2521ed0b91e8c20eb1a41038a983a11e7ae9ecf1ce0b6687572a2ccd13cc",
          "sha256": "d679ddb3e7ba8c487f164709e1fac318252736b07cbde1b776d1da62ff38fce4",
          "sha1": "7b149410df9f2639deb7fe8a2d0992494783d9d2",
          "md5": "2eaf58136b5d03371ebcbbf8c6eeac13"
        }
      ]
    }
  ]
}