{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.constraintlayout",
    "module": "constraintlayout-compose",
    "version": "1.1.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "constraintlayout-compose-1.1.0-alpha13-multiplatform-sources.jar",
          "url": "constraintlayout-compose-1.1.0-alpha13-multiplatform-sources.jar",
          "size": 103545,
          "sha512": "0c55605a63f7d248ac6f5eb500f29d1665ad95be393bf13518488154a25061b2446214d29d8aa709bca6902156e95f171d64c327318e944222d9767f8e75f433",
          "sha256": "393072ac7b09feb003111d6e25a805f83d80d13087e39d339402a255d1d82ead",
          "sha1": "ea784232c01330e1ea04ad57dc514e22359f5909",
          "md5": "b771a793590707a0112edba2cd22203e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "constraintlayout-compose-1.1.0-alpha13-versionMetadata.json",
          "size": 56003,
          "sha512": "b4c8aca9ebcf2329fdb229c0d8250d6b9cec6b62a2342f82fe7507ad626c8ae9f2034e9c1fa4b012c92e8303163e65e9871036da83872946b955f9ed35e4e97b",
          "sha256": "2c9f5b43cd5fa8855b6b8956690235bb3e9e343a0606b2fea8854338942a92b3",
          "sha1": "272b1841cf4ecdec421f0186de2754491ccf4872",
          "md5": "3d8789341d385c4c75f4311b6c636219"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "constraintlayout-compose-metadata-1.1.0-alpha13.jar",
          "url": "constraintlayout-compose-1.1.0-alpha13.jar",
          "size": 660,
          "sha512": "b2f9847ad3b9e240fe027dd4b7bae0977964c709907294254b4906a8a4786c1c7b4d1d191aa7593985c5baac302772dcbf2933dc7173324ab645131182260d53",
          "sha256": "1dd30ce8cca076140ed92ee748c1d35a4ac46b9da435406e353208a07267996d",
          "sha1": "b5c589b0e46d99e25aebe48839215aaec925ae55",
          "md5": "ba41245ca2b526249e40016327115655"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "constraintlayout-compose-kotlin-1.1.0-alpha13-sources.jar",
          "url": "constraintlayout-compose-1.1.0-alpha13-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../constraintlayout-compose-android/1.1.0-alpha13/constraintlayout-compose-android-1.1.0-alpha13.module",
        "group": "androidx.constraintlayout",
        "module": "constraintlayout-compose-android",
        "version": "1.1.0-alpha13"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../constraintlayout-compose-android/1.1.0-alpha13/constraintlayout-compose-android-1.1.0-alpha13.module",
        "group": "androidx.constraintlayout",
        "module": "constraintlayout-compose-android",
        "version": "1.1.0-alpha13"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../constraintlayout-compose-android/1.1.0-alpha13/constraintlayout-compose-android-1.1.0-alpha13.module",
        "group": "androidx.constraintlayout",
        "module": "constraintlayout-compose-android",
        "version": "1.1.0-alpha13"
      }
    }
  ]
}