{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-common",
    "version": "2.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-metadata-2.7.0-alpha01.jar",
          "url": "room-common-2.7.0-alpha01.jar",
          "size": 8060,
          "sha512": "f208d4e9683340e2131194fe105af1aba7ffcc84bc07b6fecb4e45557879d2ef0ee9e1d341a07696724c14a8b33933bdc7ce377796db1073f9702611d4545a09",
          "sha256": "47b261e0a6bf23f4c1907f4d573e37f5b1fdbd593ac357ffb59960bb105d038f",
          "sha1": "5d6ba1c1715e4a99636406e93152b9fabc4a63f6",
          "md5": "d0bfae7694bf239666863669435941f6"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "room-common-kotlin-2.7.0-alpha01-sources.jar",
          "url": "room-common-2.7.0-alpha01-sources.jar",
          "size": 62370,
          "sha512": "87e3c9b99a8d0fe419254eb488fea29748fb8f6b0067a7b986d494e31fda075635ccb7969d09d2fa5f19333426edf6c9371b2c8ecf0c5c85006183dbec84e5be",
          "sha256": "81f5a20dc6f332417207aed3eac7158a1419652dc5443db1edc52fdcaa500d59",
          "sha1": "0686dd10dd1d17030d417f89b2bb1a7f5b774eba",
          "md5": "5c37de5bedceef8d413465c560430ff4"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-iosarm64/2.7.0-alpha01/room-common-iosarm64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-iosarm64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-iosarm64/2.7.0-alpha01/room-common-iosarm64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-iosarm64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-iosarm64/2.7.0-alpha01/room-common-iosarm64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-iosarm64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-iossimulatorarm64/2.7.0-alpha01/room-common-iossimulatorarm64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-iossimulatorarm64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-iossimulatorarm64/2.7.0-alpha01/room-common-iossimulatorarm64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-iossimulatorarm64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-iossimulatorarm64/2.7.0-alpha01/room-common-iossimulatorarm64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-iossimulatorarm64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-iosx64/2.7.0-alpha01/room-common-iosx64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-iosx64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-iosx64/2.7.0-alpha01/room-common-iosx64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-iosx64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-iosx64/2.7.0-alpha01/room-common-iosx64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-iosx64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-common-jvm/2.7.0-alpha01/room-common-jvm-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-jvm",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-common-jvm/2.7.0-alpha01/room-common-jvm-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-jvm",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../room-common-jvm/2.7.0-alpha01/room-common-jvm-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-jvm",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-macosarm64/2.7.0-alpha01/room-common-macosarm64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-macosarm64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-macosarm64/2.7.0-alpha01/room-common-macosarm64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-macosarm64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-macosarm64/2.7.0-alpha01/room-common-macosarm64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-macosarm64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-macosx64/2.7.0-alpha01/room-common-macosx64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-macosx64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-macosx64/2.7.0-alpha01/room-common-macosx64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-macosx64",
        "version": "2.7.0-alpha01"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../room-common-macosx64/2.7.0-alpha01/room-common-macosx64-2.7.0-alpha01.module",
        "group": "androidx.room",
        "module": "room-common-macosx64",
        "version": "2.7.0-alpha01"
      }
    }
  ]
}