{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-preferences/1.1.0-alpha05/datastore-preferences-1.1.0-alpha05.module",
    "group": "androidx.datastore",
    "module": "datastore-preferences",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences.klib",
          "url": "datastore-preferences-iossimulatorarm64-1.1.0-alpha05.klib",
          "size": 5759,
          "sha512": "679067f714376133df8a61b82df4fe1b752adec8cde8c6211f0899dc64cab2563352f1184eab584d6b2a41372f255db307bc71e2d889bac90cbceb6403370f58",
          "sha256": "601339c491cc7cf0970a9c81ae973fcf94b03bcf0c0e9ce1e995168379b03001",
          "sha1": "783f1d80b777a3df728ba3d580efc0e28f17491a",
          "md5": "2af38b17bf8256001b5d9536c2b5f93e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "datastore-preferences-iossimulatorarm64-1.1.0-alpha05-sources.jar",
          "url": "datastore-preferences-iossimulatorarm64-1.1.0-alpha05-sources.jar",
          "size": 1561,
          "sha512": "660ae721dea1911b354371a961644841a65c4d3a7007db7902ed1e8fb088519e7fb0bf863c3d6b2fda2d290f94286ea03e95674fc4feeb763868d1bb040ebb52",
          "sha256": "05ccf7d85c1f5703ed47a7a6bc09a1bc589c7ca264e101a8bb03068fdbec2c77",
          "sha1": "84b6f65693f3e6af5e8e5ef0446a4e953a6ee22c",
          "md5": "3d45d8c87ab7eabc89b9d6b68ef5db5a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-iossimulatorarm64-1.1.0-alpha05-metadata.jar",
          "url": "datastore-preferences-iossimulatorarm64-1.1.0-alpha05-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}