{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.6.0-alpha06-topping01/runtime-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-release.aar",
          "url": "runtime-android-1.6.0-alpha06-topping01.aar",
          "size": 2335585,
          "sha512": "f8593252e520ee5b274c6a7f5c3288c98f088f32787c5698241f7ca4fa42e41114e93d3e9d8f0338147941b9e25148766217fa52b36a86ba1114f2e717d6b85f",
          "sha256": "d1b516f805d3b0ae648c2ce7a4babc12be5ac751ecd70be183043ca08c11bc52",
          "sha1": "fb01d6d98b3eb6372e60978e24cde059b8c14ecc",
          "md5": "61cb2e178f0f09b9f10abd6421a2cf02"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-release.aar",
          "url": "runtime-android-1.6.0-alpha06-topping01.aar",
          "size": 2335585,
          "sha512": "f8593252e520ee5b274c6a7f5c3288c98f088f32787c5698241f7ca4fa42e41114e93d3e9d8f0338147941b9e25148766217fa52b36a86ba1114f2e717d6b85f",
          "sha256": "d1b516f805d3b0ae648c2ce7a4babc12be5ac751ecd70be183043ca08c11bc52",
          "sha1": "fb01d6d98b3eb6372e60978e24cde059b8c14ecc",
          "md5": "61cb2e178f0f09b9f10abd6421a2cf02"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "runtime-android-1.6.0-alpha06-topping01-sources.jar",
          "url": "runtime-android-1.6.0-alpha06-topping01-sources.jar",
          "size": 368041,
          "sha512": "4cc897f9ef7402254f5f2cc6e627d0f8e0f7b2eae1c5fd8375635b0ce115b6c057cd711df0b2039d0d0b09b8639b5b188daa975f18ff7e61b91bd79e4285b13a",
          "sha256": "7811f5febcd95d0d88ee46a067d5d911ab7f475531efbbcfba6e0d7ae7dcb138",
          "sha1": "f8806b43b4582330b79c7a66a3c60d6fe8cb090f",
          "md5": "d56b6f27afc9372cfaa422ccdfa2d645"
        }
      ]
    }
  ]
}