{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.6.0-alpha06-topping02/foundation-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "foundation.klib",
          "url": "foundation-iosx64-1.6.0-alpha06-topping02.klib",
          "size": 2354910,
          "sha512": "594cca772c94cec48029fa687abe46792b9ab374e07d1e951a88a0050996d812b57c98f171790590bb367dd64e34e5995eeeb2af7c6898cda46bdb098d476dd8",
          "sha256": "0afe8ab4429d63ffc6322c8a8bad17da83ac0422ec5a7ee70c0a8dae2436a18d",
          "sha1": "36be6e8dca7199376ae28a285bc52fe3f8668982",
          "md5": "9c87d1cc5aba64bba3dcae2d2cbd27cf"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "foundation-iosx64-1.6.0-alpha06-topping02-sources.jar",
          "url": "foundation-iosx64-1.6.0-alpha06-topping02-sources.jar",
          "size": 697694,
          "sha512": "d90323541fdd4d98fe0a4c521277604958b025686c4cbf3f0b746abe1a30be0f1f5316cccdb92a025c652cd9e29f31f7f92683ef21066c1cc4d56a099ee1c5f6",
          "sha256": "d87db2400fe035bc4c9c3bda30c188950e07c72c50c95f96ff5b9dbdd8126d43",
          "sha1": "d9ed85db984d16b380ce8c29d6ee9bd6109d7c8f",
          "md5": "db6597796fb1b0676d1fd893aa61292e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-iosx64-1.6.0-alpha06-topping02-metadata.jar",
          "url": "foundation-iosx64-1.6.0-alpha06-topping02-metadata.jar",
          "size": 23344,
          "sha512": "4886897a2587ddad709ae2cbfde1b41798d77eb52d4cb1bf1739f3622ea5206ce6ce2d0dd9d94913899d27bb830f923950779c508cd582fd08430ce540d20b8a",
          "sha256": "169405a73ec976c5af57e946fbfc963a10d37d76f9fa5ac4739d3e5eb697b372",
          "sha1": "98c94104b177efafc3d4cf600810ba53f8b9b291",
          "md5": "8719417535d9fdfcbf6665accb214d13"
        }
      ]
    }
  ]
}