{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-java",
    "version": "1.2.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "window-java-1.2.0-beta03.aar",
          "url": "window-java-1.2.0-beta03.aar",
          "size": 11555,
          "sha512": "e72c67f5ca7d1336370a2ee871f8a691c2d7612e70a64c21d8396d6705f0bcbe04c16372e94153e63be22c4d03dab5bfb35d54e15e91484e0ae7f029ec83eb6d",
          "sha256": "0bab0341b1a42623f2f1a65ea7e0c3b554d9f1811402fc5256d99aa1ff72169a",
          "sha1": "6bfea95a1fa881c1d0411cf86bf87926524fff7a",
          "md5": "641aecc69b60a38d77b683d3d8d851d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "window-java-1.2.0-beta03.aar",
          "url": "window-java-1.2.0-beta03.aar",
          "size": 11555,
          "sha512": "e72c67f5ca7d1336370a2ee871f8a691c2d7612e70a64c21d8396d6705f0bcbe04c16372e94153e63be22c4d03dab5bfb35d54e15e91484e0ae7f029ec83eb6d",
          "sha256": "0bab0341b1a42623f2f1a65ea7e0c3b554d9f1811402fc5256d99aa1ff72169a",
          "sha1": "6bfea95a1fa881c1d0411cf86bf87926524fff7a",
          "md5": "641aecc69b60a38d77b683d3d8d851d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "window-java-1.2.0-beta03-sources.jar",
          "url": "window-java-1.2.0-beta03-sources.jar",
          "size": 6191,
          "sha512": "0c8e3ed4e19449eef07a2ddfabf15a2c720f4b51f78226f97b408a2d8c1a898cfe5b78afd966bb22d5b46e4fc0ee1040d86ea31c6bb3e30a722d143c8ec0ecee",
          "sha256": "604f9b31e735cc9a38931191ee03edcdbe04c621f954a88aade82cbe238c3cb3",
          "sha1": "40d2e663b216aed281d546ff1e2476cf16d943ce",
          "md5": "f76ef44c3af8381c913c916142ea9284"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "window-java-1.2.0-beta03-versionMetadata.json",
          "url": "window-java-1.2.0-beta03-versionMetadata.json",
          "size": 1825,
          "sha512": "aca20d8341d20da9f7f49f847ed3fe117b0f31945c4a6b22eb56d84228f03c4b2dfe539e4b48855f6632f09c74cbe606e6804029330340130a70967de26e48c7",
          "sha256": "09c0a20f141d9c6ec760c6b9f87d2605f13c7cbd8081c8a67287f8f34644181b",
          "sha1": "1157cc5f64af5cdcaad06a2cc3233dfb31be18c4",
          "md5": "3b05f2a2015b190e9b0476ab7665cf99"
        }
      ]
    }
  ]
}