{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.4.0-alpha01/collection-1.4.0-alpha01.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.4.0-alpha01.jar",
          "url": "collection-jvm-1.4.0-alpha01.jar",
          "size": 761632,
          "sha512": "7a8ff25853e94cb6866c62b29ee450610068681d1e7479be7bf9f61d1e954b1dad7c895f602b2dc69353a7ed0f10b1dee59320e1236ebfdd85bfd7b6ebf0e3c0",
          "sha256": "09a2070d25fb0fc5fb3e6d9aa70e6316b9fc195b0c60beea0bbc443f80d11829",
          "sha1": "72cb5e68b9ddc74e1379602530c88a78bc0a9a8a",
          "md5": "5a92ab8bd39f2259d6783fca147131f3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.4.0-alpha01.jar",
          "url": "collection-jvm-1.4.0-alpha01.jar",
          "size": 761632,
          "sha512": "7a8ff25853e94cb6866c62b29ee450610068681d1e7479be7bf9f61d1e954b1dad7c895f602b2dc69353a7ed0f10b1dee59320e1236ebfdd85bfd7b6ebf0e3c0",
          "sha256": "09a2070d25fb0fc5fb3e6d9aa70e6316b9fc195b0c60beea0bbc443f80d11829",
          "sha1": "72cb5e68b9ddc74e1379602530c88a78bc0a9a8a",
          "md5": "5a92ab8bd39f2259d6783fca147131f3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "collection-jvm-1.4.0-alpha01-sources.jar",
          "url": "collection-jvm-1.4.0-alpha01-sources.jar",
          "size": 230809,
          "sha512": "f008a8c6adcd7b0d0ac9138e4562fe77b45b5f69df479ddce6aefbd735d9111efb847b22ad37b2487c7307a8806aaf0ddfd6859af36ddf506947bd941294eee8",
          "sha256": "a86420be4a448c6b9b0744ccc543141637d1e7364bef15b3a3f564983b4bc7c2",
          "sha1": "bfa9099fe693084adf2551faf8363a40af564ce4",
          "md5": "4eaaa5eebbbbb7326cbc68c12517ef19"
        }
      ]
    }
  ]
}