{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3-window-size-class-samples",
    "version": "1.2.0-alpha08-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "material3-window-size-class-samples-1.2.0-alpha08-topping01.aar",
          "url": "material3-window-size-class-samples-1.2.0-alpha08-topping01.aar",
          "size": 7231,
          "sha512": "35d96d5df6825f15c78528743d9a77efd5de8baff51222b3b3cabc3cdfc5d5e531611b0a5b8b1497e51963292102113f60f4acf1215b97787ee21a1db0d94570",
          "sha256": "525c07290181ede6114cbca3228c23b53f71c8459b124103c3fadb5724eb5c84",
          "sha1": "bb395e110538762dfa20f3581c6320b6c6e76c43",
          "md5": "af9ed0c108102d18094a48c4445d671c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0-alpha08-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-samples-1.2.0-alpha08-topping01.aar",
          "url": "material3-window-size-class-samples-1.2.0-alpha08-topping01.aar",
          "size": 7231,
          "sha512": "35d96d5df6825f15c78528743d9a77efd5de8baff51222b3b3cabc3cdfc5d5e531611b0a5b8b1497e51963292102113f60f4acf1215b97787ee21a1db0d94570",
          "sha256": "525c07290181ede6114cbca3228c23b53f71c8459b124103c3fadb5724eb5c84",
          "sha1": "bb395e110538762dfa20f3581c6320b6c6e76c43",
          "md5": "af9ed0c108102d18094a48c4445d671c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-window-size-class-samples-1.2.0-alpha08-topping01-sources.jar",
          "url": "material3-window-size-class-samples-1.2.0-alpha08-topping01-sources.jar",
          "size": 2091,
          "sha512": "c4ac844ea57ede2735c4cb0b65f7918d85a3a7477f8adc7ffdab162e5bc24a92fbfce59387b94788a8ef6fd7f8a95ff4230e977c79ba40e9d785f5589015809d",
          "sha256": "c7cbdf095e517a6c5ac11ed66768a6e7fe5cd15ff63b8c6e8648bd443cebf201",
          "sha1": "f75d5997f0ca689a6f23cfd6691159e3d730a8f7",
          "md5": "1920115e5c0b725089bd50f1d7b01fc0"
        }
      ]
    }
  ]
}