{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-testing",
    "version": "1.2.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0-beta03"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "window-testing-1.2.0-beta03.aar",
          "url": "window-testing-1.2.0-beta03.aar",
          "size": 35309,
          "sha512": "a058d8680c5eab905caecb0df0c423ab9f88d9fa19232b9a3e591ae268f6d2b1c795fd85c7f71682132b315298361b604c85ab66db884e3e747d3e8a0299ed17",
          "sha256": "e87d5c54d4ba79ba5fc978c17adb6cd361f445e99c35f8225e6b34c8983817ff",
          "sha1": "1b9b68260c592a9b39d58009704dcb8b8b2a62d5",
          "md5": "d79bf4ae8525fb43451a5246ff5e986f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0-beta03"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "window-testing-1.2.0-beta03.aar",
          "url": "window-testing-1.2.0-beta03.aar",
          "size": 35309,
          "sha512": "a058d8680c5eab905caecb0df0c423ab9f88d9fa19232b9a3e591ae268f6d2b1c795fd85c7f71682132b315298361b604c85ab66db884e3e747d3e8a0299ed17",
          "sha256": "e87d5c54d4ba79ba5fc978c17adb6cd361f445e99c35f8225e6b34c8983817ff",
          "sha1": "1b9b68260c592a9b39d58009704dcb8b8b2a62d5",
          "md5": "d79bf4ae8525fb43451a5246ff5e986f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "window-testing-1.2.0-beta03-sources.jar",
          "url": "window-testing-1.2.0-beta03-sources.jar",
          "size": 18529,
          "sha512": "42cebfe917c4637c739805c2bbb715c3c5a7084b35ccfb8ab88893449c695240aed2b3f219bc5aec79d8893cb30b9d11490530d76e31a33f2d2e6d1bb40e1a75",
          "sha256": "6c941c582c989debee5f1fe1613242dc0802dfd09e525e2d696d781b3282f232",
          "sha1": "cc274adc15949a90f9af28c08d6d71b2326615c3",
          "md5": "4df007b1535359c366610176340e0dc5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "window-testing-1.2.0-beta03-versionMetadata.json",
          "url": "window-testing-1.2.0-beta03-versionMetadata.json",
          "size": 5373,
          "sha512": "b1089051fe047f97d8d2ddea196d65570d02a415a32485d37d827d5a0bad960ab6b16995dc3e67dfae8d696d8d5cd062b26bac55e252af6bd6bfc41d2bbf6e26",
          "sha256": "3b5cbb657ea2f8b9ab51c8a36f4aeeb6da280a1ae7f0bb260ebe6e491e51ae13",
          "sha1": "a3ee199acbf3f4af28dbeb29b786ea3f33bd3bf4",
          "md5": "6f953fe80db5c82bbbe8887884ec0740"
        }
      ]
    }
  ]
}