{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-viewbinding-samples",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-viewbinding-samples-1.6.0-alpha06-topping01.aar",
          "url": "ui-viewbinding-samples-1.6.0-alpha06-topping01.aar",
          "size": 18590,
          "sha512": "d4dcf5cce5d18454a18d68594258425a59c0da5d35a472f57be6d422441147ca2b2b6cf2f0b64d21e735870a73d9778c106ce001a13d4a84897cea2fd60086e4",
          "sha256": "e977e535c805dfcd93ebc82d77d8540e51c229b53349879639b581402ec8db6f",
          "sha1": "4740eb5af5735e4bb33f01bf5ff26a621e7b3dee",
          "md5": "7a9481d30296ec46783cc3e630a0a72b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.0-alpha02"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-viewbinding-samples-1.6.0-alpha06-topping01.aar",
          "url": "ui-viewbinding-samples-1.6.0-alpha06-topping01.aar",
          "size": 18590,
          "sha512": "d4dcf5cce5d18454a18d68594258425a59c0da5d35a472f57be6d422441147ca2b2b6cf2f0b64d21e735870a73d9778c106ce001a13d4a84897cea2fd60086e4",
          "sha256": "e977e535c805dfcd93ebc82d77d8540e51c229b53349879639b581402ec8db6f",
          "sha1": "4740eb5af5735e4bb33f01bf5ff26a621e7b3dee",
          "md5": "7a9481d30296ec46783cc3e630a0a72b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-viewbinding-samples-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-viewbinding-samples-1.6.0-alpha06-topping01-sources.jar",
          "size": 1721,
          "sha512": "7b4970947f7e385f2999460f28453e942162d44649eaa9c230d8fba1919c8fed423486c91e46910d3fc4c7de1bcf67f8342b06a1ce9899dd48e71ade844a9e8d",
          "sha256": "9460ea9ba436ceabf49fac72506af140fe15352fbcd751af65cd4076a0d1b1ca",
          "sha1": "283954afe3edb9f9ec7fb8aa35bbcfb2edaa3571",
          "md5": "a746e41733eb592fd93a2c1e64c2f133"
        }
      ]
    }
  ]
}