{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material-samples",
    "version": "1.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compose-material-samples-1.3.0-alpha06.aar",
          "url": "compose-material-samples-1.3.0-alpha06.aar",
          "size": 668971,
          "sha512": "fbb236886a4598987cfae2539ead060439ea2c286a256757bb2add0df3f67ec30127f301d3c4c0c623b1fce0847265b977069dcf76cb16193d7fc6f8f7bf9d4f",
          "sha256": "e251789493efc51e38d9412739ebf1a6c0c002a9bc45fda9682a52b0c868b632",
          "sha1": "94ccdbf2027e5f5f3936f1151858a738bf13158f",
          "md5": "fdd296e2edc04f7a5116033e261f1ff7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-samples-1.3.0-alpha06.aar",
          "url": "compose-material-samples-1.3.0-alpha06.aar",
          "size": 668971,
          "sha512": "fbb236886a4598987cfae2539ead060439ea2c286a256757bb2add0df3f67ec30127f301d3c4c0c623b1fce0847265b977069dcf76cb16193d7fc6f8f7bf9d4f",
          "sha256": "e251789493efc51e38d9412739ebf1a6c0c002a9bc45fda9682a52b0c868b632",
          "sha1": "94ccdbf2027e5f5f3936f1151858a738bf13158f",
          "md5": "fdd296e2edc04f7a5116033e261f1ff7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-material-samples-1.3.0-alpha06-sources.jar",
          "url": "compose-material-samples-1.3.0-alpha06-sources.jar",
          "size": 30752,
          "sha512": "9f4a85ec2286ca40b1890433501462015fe9010b7d408140f9ec0ae755f0aeeebf250580f25ccd76ab5049ae61d94a090436c70a31ea7a4235b582f81f2f2b03",
          "sha256": "d2c02d6ea8f393228474ec99121d151f864364a2734a696dc296ed54c16f0fab",
          "sha1": "a67b89bf88383aae0924ee221ee93a57447fa480",
          "md5": "00d6d7ddeb03a57132e654bb9c7459ab"
        }
      ]
    }
  ]
}