{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-geometry/1.6.0-alpha06-topping01/ui-geometry-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.ui",
    "module": "ui-geometry",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-release.aar",
          "url": "ui-geometry-android-1.6.0-alpha06-topping01.aar",
          "size": 36633,
          "sha512": "8c73405ab6deaa2d72ad84386e406e720267b776a1f1b9bc4e03c338f7cb52ea74bde7b4b6459447b59b5184ba984cad6dd9fc6eb0d111f0356e7e6413ce8040",
          "sha256": "1b0103449af8d8b4817d963066c512fb4c4832ede4fa29116ae68932fa2596f0",
          "sha1": "f22ead190fbd8c3e8560ffb60acaace6c28f39ef",
          "md5": "63c031f968d73dac4de105cd4c0b6722"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ui-geometry-release.aar",
          "url": "ui-geometry-android-1.6.0-alpha06-topping01.aar",
          "size": 36633,
          "sha512": "8c73405ab6deaa2d72ad84386e406e720267b776a1f1b9bc4e03c338f7cb52ea74bde7b4b6459447b59b5184ba984cad6dd9fc6eb0d111f0356e7e6413ce8040",
          "sha256": "1b0103449af8d8b4817d963066c512fb4c4832ede4fa29116ae68932fa2596f0",
          "sha1": "f22ead190fbd8c3e8560ffb60acaace6c28f39ef",
          "md5": "63c031f968d73dac4de105cd4c0b6722"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ui-geometry-android-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-geometry-android-1.6.0-alpha06-topping01-sources.jar",
          "size": 18278,
          "sha512": "9ea87e8be182c050396a1db751a23fd5e1aebede9e8ecfbc812801a831aa9f5106ce9a2a751eb2714b03e60fceffd2b55d5cbea57d83c58e1f0530d36b04c8d6",
          "sha256": "1cdb444bb73105531a91ef3b12098ada9392653e9ffc3d8d79ded19caa19253e",
          "sha1": "52669a9505a8bbcfa60523b6c52000050e3000d9",
          "md5": "13d5ab5d38f1f14f28c5ac635ebdccb5"
        }
      ]
    }
  ]
}