{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-samples",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "foundation-samples-1.6.0-alpha06-topping01.aar",
          "url": "foundation-samples-1.6.0-alpha06-topping01.aar",
          "size": 1049976,
          "sha512": "3224d82a2b577b4abedb4e6a35e2519b63638780882527da3566b0a3c22df33e3a3c46a79d989d6d24853fd077f240d271a04efcd1d4a7f84b65839e24bff330",
          "sha256": "7d212ef4810e144ab7e2b520178891adbc1b48dc03154b65719f6b897fe46eb7",
          "sha1": "ab6f8343c854df6e5deba663e5f5e2de5b1ea247",
          "md5": "31f6f1dc84331b37e17616fd2be1e9ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-samples-1.6.0-alpha06-topping01.aar",
          "url": "foundation-samples-1.6.0-alpha06-topping01.aar",
          "size": 1049976,
          "sha512": "3224d82a2b577b4abedb4e6a35e2519b63638780882527da3566b0a3c22df33e3a3c46a79d989d6d24853fd077f240d271a04efcd1d4a7f84b65839e24bff330",
          "sha256": "7d212ef4810e144ab7e2b520178891adbc1b48dc03154b65719f6b897fe46eb7",
          "sha1": "ab6f8343c854df6e5deba663e5f5e2de5b1ea247",
          "md5": "31f6f1dc84331b37e17616fd2be1e9ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-samples-1.6.0-alpha06-topping01-sources.jar",
          "url": "foundation-samples-1.6.0-alpha06-topping01-sources.jar",
          "size": 61339,
          "sha512": "9305e71dac5b6f366328c5c01af8848def95e492014b9fddc1f71df6e904b1447b334f39e75af668b42b5feb7876dd11b7ea1215033839b893cee4674df3635d",
          "sha256": "9a09f3d6a8586ad59019d6135ff0fac6b8e2af4633b0b9840205bad3ac97ee39",
          "sha1": "23150775f477cba8da8670cc2f9152641a0e4d3c",
          "md5": "05035c5dc7ff2c2df907166e45ae8900"
        }
      ]
    }
  ]
}