{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava2",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-1.6.0-alpha06-topping02.aar",
          "url": "runtime-rxjava2-1.6.0-alpha06-topping02.aar",
          "size": 26569,
          "sha512": "a3d2e6369e8bf473b10b49b1be88bdc9bdf1bc5c9b977d970dca9deac303c5317c3f16b9368dd10572ccdcedd0ea03d5c9d8af38bd20deecfdf7df3b9f9c1c25",
          "sha256": "b2f4cef5478e31bee3372c388219d9342c682dd6fc7c1d0ed244747da302a4aa",
          "sha1": "4ed818eff12047d8e2bc6213de2b009f6e97bc92",
          "md5": "9d2809761cfd3682e266971a584c04c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-1.6.0-alpha06-topping02.aar",
          "url": "runtime-rxjava2-1.6.0-alpha06-topping02.aar",
          "size": 26569,
          "sha512": "a3d2e6369e8bf473b10b49b1be88bdc9bdf1bc5c9b977d970dca9deac303c5317c3f16b9368dd10572ccdcedd0ea03d5c9d8af38bd20deecfdf7df3b9f9c1c25",
          "sha256": "b2f4cef5478e31bee3372c388219d9342c682dd6fc7c1d0ed244747da302a4aa",
          "sha1": "4ed818eff12047d8e2bc6213de2b009f6e97bc92",
          "md5": "9d2809761cfd3682e266971a584c04c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-rxjava2-1.6.0-alpha06-topping02-sources.jar",
          "url": "runtime-rxjava2-1.6.0-alpha06-topping02-sources.jar",
          "size": 2227,
          "sha512": "55b0eeb15c4f660bbefa8598e2358adc9f84719bab5ff755497e82d8f29dd44228ebf36bf3ef6e0142462301aa0a183648bcf7a8a68c84cd7bcbe2488c877985",
          "sha256": "133c8b6dc1bafe3ab3b70f7f1db6d2fe3c4304d7b9304450a17c24eb87c74b9d",
          "sha1": "2ac58cd9ad8dd8130cad34c250deb9f5826303ff",
          "md5": "9f85d844d7504a7c664908827a9b9aee"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "runtime-rxjava2-1.6.0-alpha06-topping02-versionMetadata.json",
          "url": "runtime-rxjava2-1.6.0-alpha06-topping02-versionMetadata.json",
          "size": 544,
          "sha512": "06b3a5223d9b09b93eef1f2d54abdfe9617f2cf9601ea7673b1e17e84bbc68735b1c00307abe390ae7fe509ae7219f65e39d5099f160a590071b94dc8df93fe2",
          "sha256": "1e8ec918c3ffd0dc0c99286e36da9938544340ddbb24859d4c149c54be6af3cc",
          "sha1": "94a88b9df26a59bacd7a4f33436fe5ce6aba482d",
          "md5": "e3ca3605db80e0d7615ed7752cc58c77"
        }
      ]
    }
  ]
}