{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto-binary",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0-beta03.aar",
          "url": "tracing-perfetto-binary-1.0.0-beta03.aar",
          "size": 4340412,
          "sha512": "b0906d2d4f6fe0ec2b2585e6ab573c5e138e0f75c60892e18d8c15f23d486853e01aa8bfb0a1cba222e08fae0588bee0999b6019158a9e8b8869e1f62ba61bee",
          "sha256": "0de4c3e80f214de146502d5be67f8c5a57704222be0676ca01a86baf7718923f",
          "sha1": "afca3b9605c2377d867015e8ab142851b5eadb93",
          "md5": "d31de25dad50e311a5f5640841a062fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0-beta03.aar",
          "url": "tracing-perfetto-binary-1.0.0-beta03.aar",
          "size": 4340412,
          "sha512": "b0906d2d4f6fe0ec2b2585e6ab573c5e138e0f75c60892e18d8c15f23d486853e01aa8bfb0a1cba222e08fae0588bee0999b6019158a9e8b8869e1f62ba61bee",
          "sha256": "0de4c3e80f214de146502d5be67f8c5a57704222be0676ca01a86baf7718923f",
          "sha1": "afca3b9605c2377d867015e8ab142851b5eadb93",
          "md5": "d31de25dad50e311a5f5640841a062fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0-beta03-sources.jar",
          "url": "tracing-perfetto-binary-1.0.0-beta03-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "tracing-perfetto-binary-1.0.0-beta03-versionMetadata.json",
          "url": "tracing-perfetto-binary-1.0.0-beta03-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}