{
  "formatVersion": "1.1",
  "component": {
    "url": "../../room-common/2.7.0-alpha01/room-common-2.7.0-alpha01.module",
    "group": "androidx.room",
    "module": "room-common",
    "version": "2.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "room-common.klib",
          "url": "room-common-macosarm64-2.7.0-alpha01.klib",
          "size": 60257,
          "sha512": "0eaa164225aaa71f20a8a879f6b70a37d95e485fc54ce76d7e76a5504bb7a4537ff2224fd72340273ca34072474a4807fbfad5a2e7dcc6c40a1661c283a13d5f",
          "sha256": "48b22d9a798de514daa2292d84230108ba1c0145f01e3560197018b9dc4cb0b4",
          "sha1": "8e818fff913b90a42a3ae2a0e6218b7b7d8ed6f6",
          "md5": "91264c67124cba422fcf6e844220b967"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "room-common-macosarm64-2.7.0-alpha01-sources.jar",
          "url": "room-common-macosarm64-2.7.0-alpha01-sources.jar",
          "size": 62370,
          "sha512": "87e3c9b99a8d0fe419254eb488fea29748fb8f6b0067a7b986d494e31fda075635ccb7969d09d2fa5f19333426edf6c9371b2c8ecf0c5c85006183dbec84e5be",
          "sha256": "81f5a20dc6f332417207aed3eac7158a1419652dc5443db1edc52fdcaa500d59",
          "sha1": "0686dd10dd1d17030d417f89b2bb1a7f5b774eba",
          "md5": "5c37de5bedceef8d413465c560430ff4"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-macosarm64-2.7.0-alpha01-metadata.jar",
          "url": "room-common-macosarm64-2.7.0-alpha01-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}