{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.7.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.7.0-alpha02.aar",
          "url": "lifecycle-viewmodel-2.7.0-alpha02.aar",
          "size": 39826,
          "sha512": "e9b477c33b2ae6d4d8fd221fa9a0a3f6ef244237bea5733789fb790cd8564a4d8f486c5d5d214a32d1de9575862e67d101a7b0cd26e6332f95a5d47cdc51db56",
          "sha256": "0744f6482e1ce6ad62df641e06b0448b727e1dd90cc9a2fec8bb4431dca453c4",
          "sha1": "cf8926d8ce4d500b64fb26bb80eb142c018395a1",
          "md5": "e3c10275001814255fb1502b8adcc255"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.7.0-alpha02.aar",
          "url": "lifecycle-viewmodel-2.7.0-alpha02.aar",
          "size": 39826,
          "sha512": "e9b477c33b2ae6d4d8fd221fa9a0a3f6ef244237bea5733789fb790cd8564a4d8f486c5d5d214a32d1de9575862e67d101a7b0cd26e6332f95a5d47cdc51db56",
          "sha256": "0744f6482e1ce6ad62df641e06b0448b727e1dd90cc9a2fec8bb4431dca453c4",
          "sha1": "cf8926d8ce4d500b64fb26bb80eb142c018395a1",
          "md5": "e3c10275001814255fb1502b8adcc255"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-2.7.0-alpha02-sources.jar",
          "url": "lifecycle-viewmodel-2.7.0-alpha02-sources.jar",
          "size": 17068,
          "sha512": "7d4675a314c267f60de2b4f4eb02163d43ed56820e87ed73f8d5d5a4224546a3f9bf3d40aaea75776f81ad6eb8db5040c0f1c492fcfd033ab307a426aa696b6a",
          "sha256": "fa80252702903df73d152d957239e28c03fa2c639f3518c0dbc0d4eeecca45c5",
          "sha1": "d968f7fa5db53ac88d496fd6ad9cd86bdde2cbb1",
          "md5": "a9ba11e64a00c336e78dadd97ce097ac"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-2.7.0-alpha02-versionMetadata.json",
          "url": "lifecycle-viewmodel-2.7.0-alpha02-versionMetadata.json",
          "size": 7803,
          "sha512": "2e9f2018903510d9f59ab6e3ccef0ef8af5889b84f573aff30c0455987739cfdcf02f40f36eacea12b5c651ac75408598ac9848b382fcd8891dec98828d93c0d",
          "sha256": "b9a1136fe2ae7c152aeda343d80b8ccb6fae6b7d03acb7b3c20a34a208305363",
          "sha1": "4f92a6461bc1fed4462530744ae8b42395db7613",
          "md5": "81a3e585bdc237dc798d8425468b7317"
        }
      ]
    }
  ]
}