{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "datastore-1.1.0-alpha05-multiplatform-sources.jar",
          "url": "datastore-1.1.0-alpha05-multiplatform-sources.jar",
          "size": 8380,
          "sha512": "7b591a45a292bdcde3e343e69c197b6b01183c31058128b35d19c0a7c5a813b0e474de7123b961763bb71d6b3dce560762a9122979757e07eabd692a7b0d60d8",
          "sha256": "0443bba059acf59a2e98c783e38b90848d7b6fb54b0539eafc3039888c7849db",
          "sha1": "9edc2640ee1cf077386656166331848bd4af7dfa",
          "md5": "b94db8ea71c451eb9cda4ddab87ec10e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "datastore-1.1.0-alpha05-versionMetadata.json",
          "size": 3720,
          "sha512": "b7dd6f53e8691483c2d316429cf8fb8712a579d58e0df49b732f4aaf9e4ee474972b6b2cad86bb2abe21d4d935e6fc98cc803802bd2d85635f2159fcd22b17e5",
          "sha256": "e4f911ef82ed8de486f12d5c66350912b8539646a708375aa728c4ee7782863f",
          "sha1": "1a5e67f6a7ed12b647b44664760ddbbddeb0bcbd",
          "md5": "af92f7cb2e3d7e4a46271fab2178718b"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-metadata-1.1.0-alpha05.jar",
          "url": "datastore-1.1.0-alpha05.jar",
          "size": 3029,
          "sha512": "7af373b87dc46342bcb7c9d1365191d7bfcbda1effbe983071133fafe80c495a514560267bd009e54e22fbfc0d4894178f96b72193301b08c421c964c99048cb",
          "sha256": "9cd0828ec07e60b15c3eacf503b0eba326397aea82185275f594ae707a1563b3",
          "sha1": "08569898b6f3ce2bd4fc6f987f5ff24c69c44f4e",
          "md5": "78ed3bad871ce3d3ad72f107eadf0dbb"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "datastore-kotlin-1.1.0-alpha05-sources.jar",
          "url": "datastore-1.1.0-alpha05-sources.jar",
          "size": 1341,
          "sha512": "eab270f4091bd2aec5e4d32f1086186713c77bc914165c1045ac75e2f16f3470cee287e8286d7025dda724fc71158294c72abcaacdb89578713648c09841c76e",
          "sha256": "a72f12ea4109692cb5a60d961b2cbf25ffc611c3995dc645c9010f249a5db291",
          "sha1": "697a77e86cf0f0f4597fdf283224f63791cb29c3",
          "md5": "3cc4d627507697ca341bd6c1dd3ee8b4"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../datastore-android/1.1.0-alpha05/datastore-android-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-android",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../datastore-android/1.1.0-alpha05/datastore-android-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-android",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../datastore-android/1.1.0-alpha05/datastore-android-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-android",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-iosarm64/1.1.0-alpha05/datastore-iosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-iosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-iosarm64/1.1.0-alpha05/datastore-iosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-iosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-iosarm64/1.1.0-alpha05/datastore-iosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-iosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-iossimulatorarm64/1.1.0-alpha05/datastore-iossimulatorarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-iossimulatorarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-iossimulatorarm64/1.1.0-alpha05/datastore-iossimulatorarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-iossimulatorarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-iossimulatorarm64/1.1.0-alpha05/datastore-iossimulatorarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-iossimulatorarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-iosx64/1.1.0-alpha05/datastore-iosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-iosx64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-iosx64/1.1.0-alpha05/datastore-iosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-iosx64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-iosx64/1.1.0-alpha05/datastore-iosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-iosx64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-jvm/1.1.0-alpha05/datastore-jvm-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-jvm",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-jvm/1.1.0-alpha05/datastore-jvm-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-jvm",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-jvm/1.1.0-alpha05/datastore-jvm-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-jvm",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-macosarm64/1.1.0-alpha05/datastore-macosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-macosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-macosarm64/1.1.0-alpha05/datastore-macosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-macosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-macosarm64/1.1.0-alpha05/datastore-macosarm64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-macosarm64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-macosx64/1.1.0-alpha05/datastore-macosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-macosx64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-macosx64/1.1.0-alpha05/datastore-macosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-macosx64",
        "version": "1.1.0-alpha05"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-macosx64/1.1.0-alpha05/datastore-macosx64-1.1.0-alpha05.module",
        "group": "androidx.datastore",
        "module": "datastore-macosx64",
        "version": "1.1.0-alpha05"
      }
    }
  ]
}