{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-preferences-core/1.1.0-alpha05/datastore-preferences-core-1.1.0-alpha05.module",
    "group": "androidx.datastore",
    "module": "datastore-preferences-core",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core.klib",
          "url": "datastore-preferences-core-iossimulatorarm64-1.1.0-alpha05.klib",
          "size": 48673,
          "sha512": "64f01686c896d1535d075145835262d801cc672ca0fa3bcd3a70ca00269236c0472ef02fbea37297d3c38840da52fa473ce38dbc88fc4309b93d3e09bee8dcc2",
          "sha256": "37a8fa694f164fdd317f51ba84eb9e0b9a9ee2b76e2f9ef184890343c0720c8d",
          "sha1": "f515537dcca2b6baadc2246bb3fb3e559b90ea89",
          "md5": "2c31cfe11b829df3756f2e525be7c213"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "datastore-preferences-core-iossimulatorarm64-1.1.0-alpha05-sources.jar",
          "url": "datastore-preferences-core-iossimulatorarm64-1.1.0-alpha05-sources.jar",
          "size": 15659,
          "sha512": "136e5ab746a04492295037d4106c4fbbfc752e69d96e5bffbbe4e388c5e6da474268e085f63d3ea5476912712e814e1daa955d8165cc35f2465053c44a1cf0b8",
          "sha256": "5df773bdbaae7e8cd9eb978b953a8a6018f55c567214bdf6c044dc513ff87edb",
          "sha1": "e1e38e6d297d8f63e1aa5f4ba708623c14dd04ea",
          "md5": "b6a08f485e60ec00ac5650dc0959f0f1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-iossimulatorarm64-1.1.0-alpha05-metadata.jar",
          "url": "datastore-preferences-core-iossimulatorarm64-1.1.0-alpha05-metadata.jar",
          "size": 6667,
          "sha512": "7a50f5c51d2672e0e4ef684d55575a8d5256eff94b50cb692858f762d55b6f6f5f819e61ed798f7a7bd532a2103b974cc599d41824b610d595846b72f9395aea",
          "sha256": "84694755ae4f941982645931618a2dab8886d0a937117c09f55ec0b531935ffa",
          "sha1": "0a6e5d99062c61d1f85982b7410828a9776c4093",
          "md5": "4d12f19b6149cf055f3def935dae3de4"
        }
      ]
    }
  ]
}