{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-metadata-1.8.0-alpha01.jar",
          "url": "annotation-1.8.0-alpha01.jar",
          "size": 4702,
          "sha512": "92c062d14b32b25e5150fb84c0feb73e95fc17c75c73cd8b7fff0ed16ae81d97aa85521f2ab61632055f53c166935c02a17a83d8123bd5e5c75f12647ab05848",
          "sha256": "5c4e873345b85bde4ccc8df62baa00d38aaab65bb21334d125778cc97ac21cfe",
          "sha1": "ec20fe484222d722ccec851163f13cb04472a381",
          "md5": "504661ab183e305b75546d092daa2b95"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "annotation-kotlin-1.8.0-alpha01-sources.jar",
          "url": "annotation-1.8.0-alpha01-sources.jar",
          "size": 24319,
          "sha512": "ddb3a27e8ca34fb7cafa76eddf082c388ca04b2d462b81c8cabfab223539437e6fc02e593b4e031579b3b71d8222bc7672e1a091e5be5488a4f7925965809f72",
          "sha256": "85b0796ad295dedf7b2a54fcb3730b307b08df8770273a2d58a31570f15c6249",
          "sha1": "c0acd77de8bce33234e57e4596196cc14a81a9f1",
          "md5": "0522c2ec0c435bba7fba3c46f212bb39"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/1.8.0-alpha01/annotation-iosarm64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-iosarm64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/1.8.0-alpha01/annotation-iosarm64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-iosarm64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/1.8.0-alpha01/annotation-iosarm64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-iosarm64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/1.8.0-alpha01/annotation-iossimulatorarm64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-iossimulatorarm64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/1.8.0-alpha01/annotation-iossimulatorarm64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-iossimulatorarm64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/1.8.0-alpha01/annotation-iossimulatorarm64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-iossimulatorarm64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/1.8.0-alpha01/annotation-iosx64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-iosx64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/1.8.0-alpha01/annotation-iosx64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-iosx64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/1.8.0-alpha01/annotation-iosx64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-iosx64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../annotation-jvm/1.8.0-alpha01/annotation-jvm-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-jvm",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../annotation-jvm/1.8.0-alpha01/annotation-jvm-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-jvm",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../annotation-jvm/1.8.0-alpha01/annotation-jvm-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-jvm",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosarm64/1.8.0-alpha01/annotation-macosarm64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-macosarm64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosarm64/1.8.0-alpha01/annotation-macosarm64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-macosarm64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosarm64/1.8.0-alpha01/annotation-macosarm64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-macosarm64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosx64/1.8.0-alpha01/annotation-macosx64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-macosx64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosx64/1.8.0-alpha01/annotation-macosx64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-macosx64",
        "version": "1.8.0-alpha01"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosx64/1.8.0-alpha01/annotation-macosx64-1.8.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-macosx64",
        "version": "1.8.0-alpha01"
      }
    }
  ]
}