{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.8.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.8.0-rc01.aar",
          "url": "activity-1.8.0-rc01.aar",
          "size": 169593,
          "sha512": "7eb86d441f973d0bc05251aa212cc47cb37baaafc882ff946eda26c8d5cc2655e088b5543a2b23c6e9a8d51b729b577c741e8a782e454ae181a2290cc0038aac",
          "sha256": "e384e208a429cfc89926ebcdc2fd1e57bc8125501ca1f0736853ed68204893a6",
          "sha1": "06a3608ed83358cccbf1df073fd279553bfbdca4",
          "md5": "b6a46f5c645b86bd682733178e1557cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.8.0-rc01.aar",
          "url": "activity-1.8.0-rc01.aar",
          "size": 169593,
          "sha512": "7eb86d441f973d0bc05251aa212cc47cb37baaafc882ff946eda26c8d5cc2655e088b5543a2b23c6e9a8d51b729b577c741e8a782e454ae181a2290cc0038aac",
          "sha256": "e384e208a429cfc89926ebcdc2fd1e57bc8125501ca1f0736853ed68204893a6",
          "sha1": "06a3608ed83358cccbf1df073fd279553bfbdca4",
          "md5": "b6a46f5c645b86bd682733178e1557cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.8.0-rc01-sources.jar",
          "url": "activity-1.8.0-rc01-sources.jar",
          "size": 54468,
          "sha512": "51a6982bcd7d750dd0fd7955d83fb7df5fb3f50fb507de5694954c3cde130c4d03ca368bf747ac01fb7e586850f86e7ec2a6098de114f19b7790a228aa27bdd5",
          "sha256": "7a85ab1f22c26d5dd18034a7ddde6c3e853efdf5d0c7d753c79179a3c20307f7",
          "sha1": "0eb069c377197578a95400c91de76e84612e869c",
          "md5": "4760aa02eab6b88b670bfc3a8b948caf"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "activity-1.8.0-rc01-versionMetadata.json",
          "url": "activity-1.8.0-rc01-versionMetadata.json",
          "size": 29217,
          "sha512": "0731a429307b555c190110818541f2290183064ceb40da6bbe40c7a87a4fd04a4d80e7b2f20f3cce06b905b5ca3208aad706807a811241019df575b044742734",
          "sha256": "cc12ce8224cdb61b9382db4a36c33078f3d02e498fc49598b515a2aa10ea626a",
          "sha1": "abe90d625a6f3dcd62f8db84482a5e3606d9cbe1",
          "md5": "17f57aaaeb76810482da3bdeac1a4e3a"
        }
      ]
    }
  ]
}