{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx",
    "module": "internal-testutils-paging",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "internal-testutils-paging-metadata.jar",
          "url": "internal-testutils-paging-unspecified.jar",
          "size": 4927,
          "sha512": "cb0e2e40d71e2421bc264b9d86b49e4b0cd1e881feb51368e86030feff157ca5fa8bc701c2b2fda6cbcf58f140750df2422423756fa6531bf741b8f27a225502",
          "sha256": "3b4bd86c68d2224f91316fb0a312d1b2185e8e7b3a8da60d51fd6ceb27c4df54",
          "sha1": "7afc555f96e7518cac07274ee919d19402a2421d",
          "md5": "d5655a1416c98238689c6ec33d875bd8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "internal-testutils-paging-kotlin-sources.jar",
          "url": "internal-testutils-paging-unspecified-sources.jar",
          "size": 6810,
          "sha512": "c778af08f46297219fd9a9adbeba17984c64f100ba0f16277a5c4448d7e12480af7e96cc9618474ebb48a1281b348151d67d3f34df405ece5e399ad79a4ea8c4",
          "sha256": "108189f5e8ee0f633d32745178dad93771a746f9c5163dbc1bffbab20c18d574",
          "sha1": "af245c416605d47f65c83286705ff2b7d0a8232d",
          "md5": "937437a8da6ca80b1c890f9aefce8b32"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-iosarm64/unspecified/internal-testutils-paging-iosarm64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-iosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-iosarm64/unspecified/internal-testutils-paging-iosarm64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-iosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-iosarm64/unspecified/internal-testutils-paging-iosarm64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-iosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-iossimulatorarm64/unspecified/internal-testutils-paging-iossimulatorarm64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-iossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-iossimulatorarm64/unspecified/internal-testutils-paging-iossimulatorarm64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-iossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-iossimulatorarm64/unspecified/internal-testutils-paging-iossimulatorarm64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-iossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-iosx64/unspecified/internal-testutils-paging-iosx64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-iosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-iosx64/unspecified/internal-testutils-paging-iosx64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-iosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-iosx64/unspecified/internal-testutils-paging-iosx64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-iosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-jvm/unspecified/internal-testutils-paging-jvm-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-jvm",
        "version": "unspecified"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-jvm/unspecified/internal-testutils-paging-jvm-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-jvm",
        "version": "unspecified"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-jvm/unspecified/internal-testutils-paging-jvm-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-jvm",
        "version": "unspecified"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-macosarm64/unspecified/internal-testutils-paging-macosarm64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-macosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-macosarm64/unspecified/internal-testutils-paging-macosarm64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-macosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-macosarm64/unspecified/internal-testutils-paging-macosarm64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-macosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-macosx64/unspecified/internal-testutils-paging-macosx64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-macosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-macosx64/unspecified/internal-testutils-paging-macosx64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-macosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../internal-testutils-paging-macosx64/unspecified/internal-testutils-paging-macosx64-unspecified.module",
        "group": "androidx",
        "module": "internal-testutils-paging-macosx64",
        "version": "unspecified"
      }
    }
  ]
}
