{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-guava",
    "version": "3.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "paging-guava-3.3.0-alpha01.aar",
          "url": "paging-guava-3.3.0-alpha01.aar",
          "size": 22381,
          "sha512": "0be39ae05041b5fd2a12979d834c12d885410ecb506e62ff017fe9b29b3c71b737869a833cba962f386b389b78a8eac7e7cf673d85cc96e73337acf2186cbeaf",
          "sha256": "69c95ba86b9a75fd0db82ab5b9da60d4cf9208c7bb468a8084f3111be54c6c01",
          "sha1": "2652bf00b055d4d716d571247c75923d3d0c3068",
          "md5": "328e31cfe25577cf2392d38230dd2aff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "paging-guava-3.3.0-alpha01.aar",
          "url": "paging-guava-3.3.0-alpha01.aar",
          "size": 22381,
          "sha512": "0be39ae05041b5fd2a12979d834c12d885410ecb506e62ff017fe9b29b3c71b737869a833cba962f386b389b78a8eac7e7cf673d85cc96e73337acf2186cbeaf",
          "sha256": "69c95ba86b9a75fd0db82ab5b9da60d4cf9208c7bb468a8084f3111be54c6c01",
          "sha1": "2652bf00b055d4d716d571247c75923d3d0c3068",
          "md5": "328e31cfe25577cf2392d38230dd2aff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-guava-3.3.0-alpha01-sources.jar",
          "url": "paging-guava-3.3.0-alpha01-sources.jar",
          "size": 4805,
          "sha512": "4929186626eb9b3805af6d41b54953666b08d5a4012b18343194dfcb4f2a9a60dd2034e03b06c2b325c05cb9bc53eda114b1b94a110299e790d9b090dfb54072",
          "sha256": "12a52a877971fcd0dff7363cd77ef02d1cb33e4213c6e782d673487735d4904f",
          "sha1": "ec2fa1066c2e9df947eb0029eaf56a20972345f6",
          "md5": "eeee7f818a45ac444896ec6703cc96a3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "paging-guava-3.3.0-alpha01-versionMetadata.json",
          "url": "paging-guava-3.3.0-alpha01-versionMetadata.json",
          "size": 2377,
          "sha512": "6e9c9b677572eb187bc287a8206e512279670f2e2ebff66453446007d9264add636ccab7cf339642600be395e8d5556781d2d5eae058dbd9085c9e07219baa80",
          "sha256": "489e6220d251aa12171e221009f2c6a4ea8ef2c07f55e1d73b3b415ccfb0ca58",
          "sha1": "2ffc85479263706c03c2eee05f34f1515ad12d16",
          "md5": "2ec9767ca945cd1bd4ea049abefe9406"
        }
      ]
    }
  ]
}