{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-tracing",
    "version": "1.0.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-tracing-1.0.0-alpha05.aar",
          "url": "runtime-tracing-1.0.0-alpha05.aar",
          "size": 4851,
          "sha512": "ab2fbafaf4b9bc5196e2ceb759a8fac5011aafdcb0601bc2009c21c357bf3d202b19802fddf95b2a9eda1dfc88ad36c6c157e90dcd8bc022420029c1c9620fd0",
          "sha256": "2e166ad0dd4a88eab4d823cac8846b3257333246c8069f42d511727c12fc96fd",
          "sha1": "ab42f583aac186aaf4bce140ca710fd6d4e82fa5",
          "md5": "c0791b65ee13f8719696f088b8a28ac4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-tracing-1.0.0-alpha05.aar",
          "url": "runtime-tracing-1.0.0-alpha05.aar",
          "size": 4851,
          "sha512": "ab2fbafaf4b9bc5196e2ceb759a8fac5011aafdcb0601bc2009c21c357bf3d202b19802fddf95b2a9eda1dfc88ad36c6c157e90dcd8bc022420029c1c9620fd0",
          "sha256": "2e166ad0dd4a88eab4d823cac8846b3257333246c8069f42d511727c12fc96fd",
          "sha1": "ab42f583aac186aaf4bce140ca710fd6d4e82fa5",
          "md5": "c0791b65ee13f8719696f088b8a28ac4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-tracing-1.0.0-alpha05-sources.jar",
          "url": "runtime-tracing-1.0.0-alpha05-sources.jar",
          "size": 1715,
          "sha512": "3c033e907ce51527bbd05e8bf23092c6e9d2d522f8df68c3c8a5b02786c7f05dc65d481a2bde4ff5c23e671a85c8cbb29b5429b0b733b3d51b9ae45334c54d0a",
          "sha256": "7cbe20aca5bfeae5db756b7ee459450c10c1922116e9ef202241cd654e8f5210",
          "sha1": "e76baef0579a7d353ee4ef2519f097a7bd6e4f06",
          "md5": "e0ceeebdc36d21a48613ea463defd29b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "runtime-tracing-1.0.0-alpha05-versionMetadata.json",
          "url": "runtime-tracing-1.0.0-alpha05-versionMetadata.json",
          "size": 314,
          "sha512": "2a172f2bb88b34338a193c4044b0d43f7e41b381dea6948d7436b623510d09cab2e179e46977367fbebc6a1d8718136f7a4620f53963509bf1bec3a3a1c50028",
          "sha256": "1f91fa9c1cd6b9a12bed608f1a6ce9adbebf5a18dbfb7de532af7e2ffe104a16",
          "sha1": "f8ad59282490f4d2251a6a06586536895f667530",
          "md5": "874ff9476c2135da62844857f5c75688"
        }
      ]
    }
  ]
}