{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material",
    "version": "1.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-1.3.0-alpha06.aar",
          "url": "compose-material-1.3.0-alpha06.aar",
          "size": 1140534,
          "sha512": "610372e347503b907c5f66a775c0c853a9c73049da632fd6cc1eaf566abccada6a2accb430813e10722ec4627fdf378bced5b22dcc19b4d8a093ced71a22c8c1",
          "sha256": "d89fe8df71dd77a80c67cb0a584155ba659e397aede91f2f1acfcc0dd3e8bfdc",
          "sha1": "31c80d2ae0744d674284ef2a68554dc204907e15",
          "md5": "d5f518c0cd4242d4f10d6b388ebf611d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-1.3.0-alpha06.aar",
          "url": "compose-material-1.3.0-alpha06.aar",
          "size": 1140534,
          "sha512": "610372e347503b907c5f66a775c0c853a9c73049da632fd6cc1eaf566abccada6a2accb430813e10722ec4627fdf378bced5b22dcc19b4d8a093ced71a22c8c1",
          "sha256": "d89fe8df71dd77a80c67cb0a584155ba659e397aede91f2f1acfcc0dd3e8bfdc",
          "sha1": "31c80d2ae0744d674284ef2a68554dc204907e15",
          "md5": "d5f518c0cd4242d4f10d6b388ebf611d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-material-1.3.0-alpha06-sources.jar",
          "url": "compose-material-1.3.0-alpha06-sources.jar",
          "size": 165999,
          "sha512": "65fdd845d194ef29b47057fca79149f6cdfbfdbc950fcde4fffc1baa36ccc4382e652e87f547f55a7bc4505de7de6b2ef9d41651a3c3d173a06c76438d67d970",
          "sha256": "7638c6b0b08eab5556fac9bce6b29383303caec2b82ed5f5e34f4783d9637674",
          "sha1": "52533bf2be62a3df1fd26871a52f4689f21ec753",
          "md5": "e3d9af66b27fd0c8bdd4ced4534c37fa"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "compose-material-1.3.0-alpha06-versionMetadata.json",
          "url": "compose-material-1.3.0-alpha06-versionMetadata.json",
          "size": 76249,
          "sha512": "470ce030f4f1e8cb18f0a77a667f94f414163dc4f380359c19fec268b6c9a305c5a943e1078725d90b40a5ac1ad2eca685d8f2e4420f27d8032e5f8f49b5aaad",
          "sha256": "fbba27d20a02e5a62ea535b799935d976c4ea3730241fb747251d3083fe166f6",
          "sha1": "d0b2e2a6a36a4e0b0f04beec3553bd8c140c6f78",
          "md5": "6aa6665668e1e51c0619f7c398a02cfc"
        }
      ]
    }
  ]
}