{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-beta03.aar",
          "url": "tracing-perfetto-1.0.0-beta03.aar",
          "size": 36789,
          "sha512": "6656e27664fafa5444cdb4943629a928bc8da989059112dbb5a376236b853b4ba5fd6f92813b9161fb4d9695bc25059d80cb6756a2e5d2c2d5a3186423dedc37",
          "sha256": "583ca06abdb8e515f4ef5033983984bf3c6a2225f3601c4bc6531f93400e5b5e",
          "sha1": "9b7205856ff7c3f7a0cbb7be13147cddb9e8763f",
          "md5": "6f471969818967f53dac752e0da2cada"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-beta03.aar",
          "url": "tracing-perfetto-1.0.0-beta03.aar",
          "size": 36789,
          "sha512": "6656e27664fafa5444cdb4943629a928bc8da989059112dbb5a376236b853b4ba5fd6f92813b9161fb4d9695bc25059d80cb6756a2e5d2c2d5a3186423dedc37",
          "sha256": "583ca06abdb8e515f4ef5033983984bf3c6a2225f3601c4bc6531f93400e5b5e",
          "sha1": "9b7205856ff7c3f7a0cbb7be13147cddb9e8763f",
          "md5": "6f471969818967f53dac752e0da2cada"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-beta03-sources.jar",
          "url": "tracing-perfetto-1.0.0-beta03-sources.jar",
          "size": 18677,
          "sha512": "2ff3eae6c9f380f25b6c792fc8c0b927d52082ac12944f269c267ab3ac9bf4635809842145fc2f912cb8ea342ee9af0937b1d0138031a56a2cf2686000852fe5",
          "sha256": "360864b23e51a5e4f4815137b3f33fb2c9f7c1608a0137066b7a736405f5f34d",
          "sha1": "5f9c422c4d326462b011a7e9b5990a975d29e2b9",
          "md5": "f07fd0d91d09a00ed165f8fe8a3e284d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-beta03-versionMetadata.json",
          "url": "tracing-perfetto-1.0.0-beta03-versionMetadata.json",
          "size": 622,
          "sha512": "35791e37098bd7fc6938013931ce30ef3846b4426275a78cb9f54aada18f4dd110ce03f16566db840b9a60c84eb7d1aafccc1e5ee528eb3e7f2becfb27a18578",
          "sha256": "53aaf80a83d2fc12f26079f5f3d6fd44e5d171e4299787b2fcd81a5233c15bd5",
          "sha1": "8681633d0f8dfac5dd5a5995b5df7e2bd1b98619",
          "md5": "985ba6d2dbf69d0c878093dbc2601590"
        }
      ]
    }
  ]
}