{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "ui-graphics-1.6.0-alpha06-topping02-multiplatform-sources.jar",
          "url": "ui-graphics-1.6.0-alpha06-topping02-multiplatform-sources.jar",
          "size": 251737,
          "sha512": "007dda9e3a23255a1de8d6057c11fc49891ecc231170c8835780ab991a5cb6546d69ea1f56ba573bf50e85147bb9d5530faddc598310b9d50ac8d7892b91a004",
          "sha256": "b48e40ca3db4441386141e4db51e3fd5d613bdca137da5b590554fd7be09ef9b",
          "sha1": "64e222981b2eac09b14166f2b319022b27e09e80",
          "md5": "f1f8043d6cd2ebd797b5f882772ce267"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-graphics-1.6.0-alpha06-topping02-versionMetadata.json",
          "size": 102493,
          "sha512": "d7a9be8330d4bca8d45bf2ed182c864e7c8b2e9fef6543405ea437f7ef6e1fc4be8a7180bdf93c120700ab33233871bbfe2628a189df60262b7a4c714fd98460",
          "sha256": "5ecfc66ca1081b8603d3a40d2ad1f06ff6d8ce2baf6ab2a1c21caf596c9a8102",
          "sha1": "879a102bd4d8b54bc9204232bdd99a6e5db81304",
          "md5": "62cf5c2dffc2262d4453b67833895498"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-metadata-1.6.0-alpha06-topping02.jar",
          "url": "ui-graphics-1.6.0-alpha06-topping02.jar",
          "size": 33486,
          "sha512": "3edce036d25d32109324aec5e175f7c2f796a904a22dc1d6df754bf559a56f06e709001de2c172db22d5f9929c59ecfc8162c13e4a709440bed0aa6d21c719fc",
          "sha256": "f69466392eda4a0135cc186cb8347c11eb70beed4b728fb5eaae36b959d86439",
          "sha1": "3faf5cb3444e9b8ca3c251aea9247c1cc7536eb3",
          "md5": "26d7df06de072a86027e57c764c75182"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ui-graphics-kotlin-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-graphics-1.6.0-alpha06-topping02-sources.jar",
          "size": 194891,
          "sha512": "fe5d9c87c67a10b0a24fee0a8cfa59362fecbf253b21fbcc7f8cf4eab220bf9f95b79970f3ebd97d069091a5ed6f13c130dcb17450aabe97604c06e60c9fecb4",
          "sha256": "c5daac2ed9a391a5634e97c79fb53b4e0968463344f50548e06c3c15ccedbd92",
          "sha1": "c70e89482d18c8da6a784c747c09bf6ee7f2614c",
          "md5": "5d82037d54893d29471d50624f715fa8"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-graphics-android/1.6.0-alpha06-topping02/ui-graphics-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-graphics-android/1.6.0-alpha06-topping02/ui-graphics-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-graphics-android/1.6.0-alpha06-topping02/ui-graphics-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-graphics-desktop/1.6.0-alpha06-topping02/ui-graphics-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-graphics-desktop/1.6.0-alpha06-topping02/ui-graphics-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-graphics-desktop/1.6.0-alpha06-topping02/ui-graphics-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-iosarm64/1.6.0-alpha06-topping02/ui-graphics-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-iosarm64/1.6.0-alpha06-topping02/ui-graphics-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-iosarm64/1.6.0-alpha06-topping02/ui-graphics-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-iossimulatorarm64/1.6.0-alpha06-topping02/ui-graphics-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-iossimulatorarm64/1.6.0-alpha06-topping02/ui-graphics-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-iossimulatorarm64/1.6.0-alpha06-topping02/ui-graphics-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-iosx64/1.6.0-alpha06-topping02/ui-graphics-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-iosx64/1.6.0-alpha06-topping02/ui-graphics-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-iosx64/1.6.0-alpha06-topping02/ui-graphics-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    }
  ]
}