{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotation/1.8.0-alpha01/annotation-1.8.0-alpha01.module",
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation.klib",
          "url": "annotation-iossimulatorarm64-1.8.0-alpha01.klib",
          "size": 17713,
          "sha512": "449a5cf86901e68b630790de6b3625afc2d5f99b9dfbd6e6f371aa585bcf85f839da02ed0398a157a6a260ba9c153eee1ea02249d259d246a72bf44f6cdb8b34",
          "sha256": "9aaa0ebb4e87349bb04b9a3fa14e48e37b35f322d410ff2e0171146334ff2212",
          "sha1": "766d70e0afe2b66f98cb114cb325a9f7ed8b19c0",
          "md5": "21e7d4d3d5b924ff660bbd443b1b763d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "annotation-iossimulatorarm64-1.8.0-alpha01-sources.jar",
          "url": "annotation-iossimulatorarm64-1.8.0-alpha01-sources.jar",
          "size": 24319,
          "sha512": "a11e56e4d8a5d42398d5a203490a9bd86e64243e01786afb94036a48a614e8af98760f869d9e7ab0eb28749eca1b170d07222955f1990f5223c801fc03a9e2a2",
          "sha256": "06955bd27a452daf423fc87e6bae4dd723daae95ae1ae81a0fe673fd134f6058",
          "sha1": "44fd07cb2577ddf9e80f21742849cbff9ba93835",
          "md5": "3b2ee89aa98b4b065e7fa82930917c38"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-iossimulatorarm64-1.8.0-alpha01-metadata.jar",
          "url": "annotation-iossimulatorarm64-1.8.0-alpha01-metadata.jar",
          "size": 3785,
          "sha512": "c7cecf28374db4037b5c292cfae7926e2f2479e84c968810f34cc901d3117f7a656fe7f5aeba566b2b4c53d1e4ac0a54d88ba95e14e98357c59fc81616bb79cd",
          "sha256": "969349a47e999a7f66a1e5e862ae99950135d093f651179b5858b0bb5ebbbc79",
          "sha1": "87c59f5ce6bc9fc35c7775cfa17c8b8e9483b9fd",
          "md5": "cdf576f22010cfac56f4dbef83314bf3"
        }
      ]
    }
  ]
}