{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/1.6.0-alpha06-topping01/material-ripple-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.6.0-alpha06-topping01.aar",
          "size": 72703,
          "sha512": "38f06d459cd45d8a6da3e37522384c13245647c71d72974a063f4462faab74ab82a1c6e38cceffdd035f7667f5b04e3fa8cf6b493726572e51f5cf9f476a2814",
          "sha256": "029e95e2af81de2f22816dcd4d2e0491942d567007c14051e72833c3c2f420f1",
          "sha1": "83eda42c4aa83c537730807f2d889735b69cbca2",
          "md5": "83c78dd7851ef6bc1968e38282701862"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.6.0-alpha06-topping01.aar",
          "size": 72703,
          "sha512": "38f06d459cd45d8a6da3e37522384c13245647c71d72974a063f4462faab74ab82a1c6e38cceffdd035f7667f5b04e3fa8cf6b493726572e51f5cf9f476a2814",
          "sha256": "029e95e2af81de2f22816dcd4d2e0491942d567007c14051e72833c3c2f420f1",
          "sha1": "83eda42c4aa83c537730807f2d889735b69cbca2",
          "md5": "83c78dd7851ef6bc1968e38282701862"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "material-ripple-android-1.6.0-alpha06-topping01-sources.jar",
          "url": "material-ripple-android-1.6.0-alpha06-topping01-sources.jar",
          "size": 23206,
          "sha512": "f6426df97edac266493871eaffc791ed6f7cde582b784cca18597e3fd3982353399adabb983255c8b2d24c4e10663997d7b3381c49ebef10907381c714e70cce",
          "sha256": "f06ce878da3eea5a917288ec95095f07d496fe6593f231a8ffcdf9631cd81525",
          "sha1": "58b3cb3adf6ee58a526d90582cd67acfa2469ad6",
          "md5": "3b33cdff7c6efd91aa8e276866bd020e"
        }
      ]
    }
  ]
}