{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.8.0-alpha01.aar",
          "url": "navigation-runtime-2.8.0-alpha01.aar",
          "size": 129003,
          "sha512": "1de9bff298d4b5ae3068ed50274e7eafa2612cd886f6ea463cc4a63713fdf77b4488abf0bf7125ef2e22f7fd9cbebdabc32b5d55939c5038432dc3ed9074c6eb",
          "sha256": "7e7fa8c7e3c17a91e50ecabc3bb19c2ca716ed8ca30ed60a4f06ef02a4ac01da",
          "sha1": "a832bae85336c6ab008c92d715e9de0025d681d2",
          "md5": "4c84b8af78ea081e30a32a1766f9381e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.8.0-alpha01.aar",
          "url": "navigation-runtime-2.8.0-alpha01.aar",
          "size": 129003,
          "sha512": "1de9bff298d4b5ae3068ed50274e7eafa2612cd886f6ea463cc4a63713fdf77b4488abf0bf7125ef2e22f7fd9cbebdabc32b5d55939c5038432dc3ed9074c6eb",
          "sha256": "7e7fa8c7e3c17a91e50ecabc3bb19c2ca716ed8ca30ed60a4f06ef02a4ac01da",
          "sha1": "a832bae85336c6ab008c92d715e9de0025d681d2",
          "md5": "4c84b8af78ea081e30a32a1766f9381e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.8.0-alpha01-sources.jar",
          "url": "navigation-runtime-2.8.0-alpha01-sources.jar",
          "size": 48255,
          "sha512": "580786176d902282933d85b7aeb81245aedf4c4eded2831ceafbfdbc64f1a714c1b10f4fb96d2f6566abd75f5a24086c2b0a3ef5472e3a0046550d4f98b14037",
          "sha256": "465d887bd8aa57b4fd559ec34dc6793c30d54b5a82a62924e9cd7f3777f749c2",
          "sha1": "05f60c5a204b3b8a2c48bb4828b27a1b8c171421",
          "md5": "a5743b22c828a51992f383c0c4990596"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "navigation-runtime-2.8.0-alpha01-versionMetadata.json",
          "url": "navigation-runtime-2.8.0-alpha01-versionMetadata.json",
          "size": 13466,
          "sha512": "cda998d9e52b31ab28c3b143a11f2b16cce9c8209ced178e4e867cb4105addf131f2154e31534549b3d8329b2e5300c66830306288772eacf26e2c7b66f68e32",
          "sha256": "6ade7ed4ed68fea38a0000db0e89c0240ae72fb56c449afa0dbe7ba909853916",
          "sha1": "cd246da22b3edda9e998bb7905b13db83b0d99d3",
          "md5": "95e87bb4d5ecabc3ca4729d87d4e8542"
        }
      ]
    }
  ]
}