{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation-layout/1.6.0-alpha06-topping02/foundation-layout-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout.klib",
          "url": "foundation-layout-iossimulatorarm64-1.6.0-alpha06-topping02.klib",
          "size": 298963,
          "sha512": "7dda7f1e1996def003e58183017a52756797ce9a3668a0add951e6354857b175beddb01261cbce9aa9ce0ff68fe73cc290678dc3e3be4c7c305c15195683d0f9",
          "sha256": "9fd93df5260679243550e37cd27638bf47791afc2bee75bc4846bd9bdf62f3ef",
          "sha1": "58d26a31104cb9be01fd9e1d397b4c82f62836f7",
          "md5": "fc2887e7bc1a0fcb729e2318e1355304"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "foundation-layout-iossimulatorarm64-1.6.0-alpha06-topping02-sources.jar",
          "url": "foundation-layout-iossimulatorarm64-1.6.0-alpha06-topping02-sources.jar",
          "size": 64565,
          "sha512": "54d9b5551cf532d57a64e0889b0887c2512cc07d69e671c2c79d594dca7b09f3d99597e390a3045036be92b326eeffb9f2f7ddf753510d561652dc2f5f868cd1",
          "sha256": "3a95b61691eec10731b845f0d9e34f2f1014b0895417753ed6c513696aa06808",
          "sha1": "5bad8be255aa7618710e50d4700db9f158e09f83",
          "md5": "64c796dd54b9247d3c369a2e1be091aa"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-iossimulatorarm64-1.6.0-alpha06-topping02-metadata.jar",
          "url": "foundation-layout-iossimulatorarm64-1.6.0-alpha06-topping02-metadata.jar",
          "size": 5129,
          "sha512": "eab968576056a5a124a040468eacb7f1b45d6dde251d5bcc8b949215bf3687c68259dbdfd34185168925715fdcb3572f6b594a5e9338890d6d8d7a688cf0c29f",
          "sha256": "8e98112574d3850f272d53e1c671028273bd083aac82659047d34a1fd02f4d14",
          "sha1": "c9121aa462a893fc1e0c318437d8ccf0a9035334",
          "md5": "384a792e6548e430215d3dc1a82690a4"
        }
      ]
    }
  ]
}