{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-saveable/1.6.0-alpha06-topping01/runtime-saveable-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-release.aar",
          "url": "runtime-saveable-android-1.6.0-alpha06-topping01.aar",
          "size": 1113075,
          "sha512": "c55e6100d53d383e992031c2a62151f45a8777c0351cfe949e8ac905d231e53e9251a7e89f389b6f1cbd98a469e38727318f604646a559b9b4fc298887b70e3e",
          "sha256": "cd439265e96df8908ac834a0fa53192b2f76171e8efad417d45e9f458debb6e7",
          "sha1": "10306390e2ff2109809b9d4d8ba672ee39c6bd80",
          "md5": "56960cd3874ad7715b863c9632e77143"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-release.aar",
          "url": "runtime-saveable-android-1.6.0-alpha06-topping01.aar",
          "size": 1113075,
          "sha512": "c55e6100d53d383e992031c2a62151f45a8777c0351cfe949e8ac905d231e53e9251a7e89f389b6f1cbd98a469e38727318f604646a559b9b4fc298887b70e3e",
          "sha256": "cd439265e96df8908ac834a0fa53192b2f76171e8efad417d45e9f458debb6e7",
          "sha1": "10306390e2ff2109809b9d4d8ba672ee39c6bd80",
          "md5": "56960cd3874ad7715b863c9632e77143"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "runtime-saveable-android-1.6.0-alpha06-topping01-sources.jar",
          "url": "runtime-saveable-android-1.6.0-alpha06-topping01-sources.jar",
          "size": 11533,
          "sha512": "f83659f1298dd8837cf5a0d7345e9704aaa6998191efb1602e9cd3ddd746f9f33dc34b86dfe1c2663ab7ee79e94b3536279ee5624c60bcd8d8b4368f78e7c595",
          "sha256": "d957fd3d4f67875cc990daa62c15ac1beebf0220c090c93db8ae04fad64bdafa",
          "sha1": "abf68b835dfdf24a970b8444c5067ffda33a37ca",
          "md5": "32c68128cbc35f49d91a14546b3d744c"
        }
      ]
    }
  ]
}