{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-lifecycle",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "ui-lifecycle-1.6.0-alpha06-topping01-multiplatform-sources.jar",
          "url": "ui-lifecycle-1.6.0-alpha06-topping01-multiplatform-sources.jar",
          "size": 30676,
          "sha512": "93a52c83f8d919b480b318f4998f9c2b4dbadb836e4c7c7b4df8da38eb9c38d5517be9d276a46ac05eb52c875c7371be236cf1db90f27793c153ee64f4022bbb",
          "sha256": "8ffebe423157cd170ce9b6228c48c95f9abed860ac88f2431186be508c99cd3e",
          "sha1": "b4080cb21ea6e81ce4951822bf9827a57c0aa603",
          "md5": "4206b41ec32cc1fa124af82a2399455d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-lifecycle-1.6.0-alpha06-topping01-versionMetadata.json",
          "size": 10670,
          "sha512": "499df3a560fa579e8a16afef75728aa2fa25b2ddf1c887e473530150e2f412abb594a56575000730acd13730afd9bfd501a7b90dde5b0e6934ef07c11c8cf861",
          "sha256": "fa6be5a591e8e41f0c7ae45e3d15b3a89b483c37adc61682ee13a1041a11f7e0",
          "sha1": "2df30a456052ade39c73c4d586debc220741b3aa",
          "md5": "8c8be2dd21420a439ba13e9a296e704e"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-lifecycle-metadata-1.6.0-alpha06-topping01.jar",
          "url": "ui-lifecycle-1.6.0-alpha06-topping01.jar",
          "size": 5834,
          "sha512": "1433894a36269d708734a8682a0a908a532eae0f8f64f7ea082bfd61be3a06b3f4121a4a2a04930b8e7aa495a9666723c9b438b223c1c4f1ebc325dc065ecbf9",
          "sha256": "68e9b0c4a290921f5b07d4141f3a61985d748f03dead48eab729de636ac73d48",
          "sha1": "095113f9932bc721a619e38378d9b6f1c30b8646",
          "md5": "a64aba91ce7f7401345e4815a3704ca6"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ui-lifecycle-kotlin-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-lifecycle-1.6.0-alpha06-topping01-sources.jar",
          "size": 17071,
          "sha512": "9f12c44d3790139ee6feb8800823902cadd3505f71b4b615ca1f53dc9b406163066e8ae53c9803ff95aff503edf2e0e571ec3479752defc183a28fef142eab67",
          "sha256": "e3e3aab3cd0ace0c7eab9c6969a181cd474606da0d2c17f8b66cc3ca814acabc",
          "sha1": "dec1c3f36a3bd6440b403dd332ac3ca77ff621d2",
          "md5": "5e30a3e67608f199cbf5e1e5451c0885"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-lifecycle-android/1.6.0-alpha06-topping01/ui-lifecycle-android-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-android",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-lifecycle-android/1.6.0-alpha06-topping01/ui-lifecycle-android-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-android",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-lifecycle-android/1.6.0-alpha06-topping01/ui-lifecycle-android-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-android",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-lifecycle-desktop/1.6.0-alpha06-topping01/ui-lifecycle-desktop-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-desktop",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-lifecycle-desktop/1.6.0-alpha06-topping01/ui-lifecycle-desktop-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-desktop",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-lifecycle-desktop/1.6.0-alpha06-topping01/ui-lifecycle-desktop-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-desktop",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-lifecycle-iosarm64/1.6.0-alpha06-topping01/ui-lifecycle-iosarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-iosarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-lifecycle-iosarm64/1.6.0-alpha06-topping01/ui-lifecycle-iosarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-iosarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-lifecycle-iosarm64/1.6.0-alpha06-topping01/ui-lifecycle-iosarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-iosarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-lifecycle-iossimulatorarm64/1.6.0-alpha06-topping01/ui-lifecycle-iossimulatorarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-lifecycle-iossimulatorarm64/1.6.0-alpha06-topping01/ui-lifecycle-iossimulatorarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-lifecycle-iossimulatorarm64/1.6.0-alpha06-topping01/ui-lifecycle-iossimulatorarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-lifecycle-iosx64/1.6.0-alpha06-topping01/ui-lifecycle-iosx64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-iosx64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-lifecycle-iosx64/1.6.0-alpha06-topping01/ui-lifecycle-iosx64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-iosx64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-lifecycle-iosx64/1.6.0-alpha06-topping01/ui-lifecycle-iosx64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-lifecycle-iosx64",
        "version": "1.6.0-alpha06-topping01"
      }
    }
  ]
}