{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-window-size-class/1.2.0-alpha08-topping01/material3-window-size-class-1.2.0-alpha08-topping01.module",
    "group": "androidx.compose.material3",
    "module": "material3-window-size-class",
    "version": "1.2.0-alpha08-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-release.aar",
          "url": "material3-window-size-class-android-1.2.0-alpha08-topping01.aar",
          "size": 18027,
          "sha512": "d0b881e0592db3e060b0665de0c1b57d5e462304137f04e6bfe68279f2de33a540274613b250fde804faacb1e7e528c0435e4dfb8701e6cdc78c735aa9c86539",
          "sha256": "ba3db362f5e59adc86a76868551d81244bedeffaaff005d19600a1be71a00813",
          "sha1": "9b2cbe32772bf4373f982e135a4c42c2096c5839",
          "md5": "dfb32982efae7cf3ac5a1c25802c4a43"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-release.aar",
          "url": "material3-window-size-class-android-1.2.0-alpha08-topping01.aar",
          "size": 18027,
          "sha512": "d0b881e0592db3e060b0665de0c1b57d5e462304137f04e6bfe68279f2de33a540274613b250fde804faacb1e7e528c0435e4dfb8701e6cdc78c735aa9c86539",
          "sha256": "ba3db362f5e59adc86a76868551d81244bedeffaaff005d19600a1be71a00813",
          "sha1": "9b2cbe32772bf4373f982e135a4c42c2096c5839",
          "md5": "dfb32982efae7cf3ac5a1c25802c4a43"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "material3-window-size-class-android-1.2.0-alpha08-topping01-sources.jar",
          "url": "material3-window-size-class-android-1.2.0-alpha08-topping01-sources.jar",
          "size": 8655,
          "sha512": "44d543c0db9cdf242e2cd611f09cf723d1594a1d601bf1ac95182ee5b80ff82773f5301fdbea3d751278fcc943ec5ceda885c877a37675a51c01511914e73210",
          "sha256": "6807b298b91575f0ab03aed20c835ab3307d516098e0c1431e830aa4f39ee138",
          "sha1": "9f42d14cc99a3f4d268c313799ee19436e01c0a9",
          "md5": "aeedbf063ad287a0b087846214190507"
        }
      ]
    }
  ]
}