{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-util/1.6.0-alpha06-topping01/ui-util-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ui-util-release.aar",
          "url": "ui-util-android-1.6.0-alpha06-topping01.aar",
          "size": 15718,
          "sha512": "b2abd7debd4d2ef0b67344c8cd4a27f5ffec4414b558aaec2e46149bc024973f6cf6944a9d4bfec582a7173826a71ca0822a25cce3be685fd3e7b7508f73271f",
          "sha256": "e9e47c1f1d5db2cbaa99e3c5c4fc7b2ff21277959155ccfde248d2589866e377",
          "sha1": "c478e8b079b39ea668b7fcc8ac4cde16122b831a",
          "md5": "4ee8daa106a8582190be5e633243e65d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ui-util-release.aar",
          "url": "ui-util-android-1.6.0-alpha06-topping01.aar",
          "size": 15718,
          "sha512": "b2abd7debd4d2ef0b67344c8cd4a27f5ffec4414b558aaec2e46149bc024973f6cf6944a9d4bfec582a7173826a71ca0822a25cce3be685fd3e7b7508f73271f",
          "sha256": "e9e47c1f1d5db2cbaa99e3c5c4fc7b2ff21277959155ccfde248d2589866e377",
          "sha1": "c478e8b079b39ea668b7fcc8ac4cde16122b831a",
          "md5": "4ee8daa106a8582190be5e633243e65d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ui-util-android-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-util-android-1.6.0-alpha06-topping01-sources.jar",
          "size": 14403,
          "sha512": "0c6537b96bf9ec0e56116bdf87651ee6414b88967665af1edb38831891eecf646e7e9547d4d279d2f688d2c778aeffc20c850a1ea394e4a0ddb8db11a1dc53c2",
          "sha256": "5d0d83361929f12aae60db2f040cac31a584671744df85b45fb9c46d1202d926",
          "sha1": "0475db7bd9ce5569e2a64dce5e519d2715d3cacb",
          "md5": "3a5b352abd07471d47effdbe7886393d"
        }
      ]
    }
  ]
}