{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kruth/1.1.0-alpha01/kruth-1.1.0-alpha01.module",
    "group": "androidx.kruth",
    "module": "kruth",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "kruth.klib",
          "url": "kruth-macosx64-1.1.0-alpha01.klib",
          "size": 86949,
          "sha512": "7ad17988bd26cb4e3fd93ecdfa8c60e771ada2339254f20c25ceda5b04d2b91cc0de404aad3408c186902559d07ad6612b866d20b26f86f5eab74b5a2ca0068b",
          "sha256": "60fd2b3c689ba960e46427f2a9c618424d072a7e9d1dabd6f2a6e61b909fa587",
          "sha1": "1af1d07aad5877217c5a462d22806a115dbf70b8",
          "md5": "eb110cc25c6766cb6b8728403c786629"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kruth-macosx64-1.1.0-alpha01-sources.jar",
          "url": "kruth-macosx64-1.1.0-alpha01-sources.jar",
          "size": 33159,
          "sha512": "5c2fc091f98c2c9dbb7a0d7dae8bc76b66ba2cf7989888632852ca149f55da14f562b899024afb3dc038510f580edd93eb903b81154957068195672197718d26",
          "sha256": "0b9d6eef9ca0280d0996faba25e86e3933e58ed1e9a7d0046f7366a0a92216fa",
          "sha1": "fc3ba1dc474d0db46cfb991196a688af078fd114",
          "md5": "ee832023af7fc44d2688188b06d275d4"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "kruth-macosx64-1.1.0-alpha01-metadata.jar",
          "url": "kruth-macosx64-1.1.0-alpha01-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}