{
  "formatVersion": "1.1",
  "component": {
    "url": "../../paging-common/3.3.0-alpha01/paging-common-3.3.0-alpha01.module",
    "group": "androidx.paging",
    "module": "paging-common",
    "version": "3.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common.klib",
          "url": "paging-common-macosarm64-3.3.0-alpha01.klib",
          "size": 288256,
          "sha512": "9989272fa84b857aa213e369d54f4545f9dfa06c04d78065cf8a8897c8f1f74123935498c75e282c28e27a1a80d58a6d4da5dcbe4be50157ae695fc7974cfba5",
          "sha256": "0da83a40e6ee751128229df0ca18c0aa8a39e04120d24beec975fe4906aed51a",
          "sha1": "471a5c7d09af2048cbf26d9c350e18dac9705459",
          "md5": "024047dd81b07a0cec6a5172658be39b"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "paging-common-macosarm64-3.3.0-alpha01-sources.jar",
          "url": "paging-common-macosarm64-3.3.0-alpha01-sources.jar",
          "size": 101027,
          "sha512": "4ac02274e90241e6484463edfd78eddd9edd59cd466d9d51dd6ab2887e6cdf9b84986adf697d3a36eb703056c82f13cb147268bd50f58cc311ef15c368b18d5d",
          "sha256": "86da96adbab3b4b6e09a9c85a890a7aaf0efc418490f4b27ef038466abd71f16",
          "sha1": "ecef3b23fbb84e4115a8fec26a7c27a4df741361",
          "md5": "fc41720dbec262c9a6e871e7333f088f"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-macosarm64-3.3.0-alpha01-metadata.jar",
          "url": "paging-common-macosarm64-3.3.0-alpha01-metadata.jar",
          "size": 8605,
          "sha512": "c077912d1d9b1e857f24a5875e111e2e5d8992cc6a27bcc6f7c7baf8e427c91bf6b05335e6a747da8d3256f526340cad898a5a9783b76ac5c60cde1bdcdecd2c",
          "sha256": "fd2dc9fec43b51ed742b48da1cc93d5d4b329f8086436873496c1e710eede67c",
          "sha1": "43528d6132c3bb71ca28a5641929e186da5c8606",
          "md5": "ef11e0b53e8ffa732a7795003fc7ee68"
        }
      ]
    }
  ]
}