{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-foundation-samples",
    "version": "1.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compose-foundation-samples-1.3.0-alpha06.aar",
          "url": "compose-foundation-samples-1.3.0-alpha06.aar",
          "size": 282191,
          "sha512": "43c0e46297613574ef963e4baa111b8d67aa3e58b0bb7ee46eb8d06d0ad30f1ef6ace474866aa3aae7b21122ea4af306540c430cbf87101fd3f042072926e58c",
          "sha256": "567a9dabca44b1e24cd28384266d0cbe1b22d884d902ad41e5b68162d5ee0d4a",
          "sha1": "253fc20d148c4ecedb1d08499a91542fbe237157",
          "md5": "d5f63848de291a42d822ef69dc5c7d87"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "compose-foundation-samples-1.3.0-alpha06.aar",
          "url": "compose-foundation-samples-1.3.0-alpha06.aar",
          "size": 282191,
          "sha512": "43c0e46297613574ef963e4baa111b8d67aa3e58b0bb7ee46eb8d06d0ad30f1ef6ace474866aa3aae7b21122ea4af306540c430cbf87101fd3f042072926e58c",
          "sha256": "567a9dabca44b1e24cd28384266d0cbe1b22d884d902ad41e5b68162d5ee0d4a",
          "sha1": "253fc20d148c4ecedb1d08499a91542fbe237157",
          "md5": "d5f63848de291a42d822ef69dc5c7d87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-foundation-samples-1.3.0-alpha06-sources.jar",
          "url": "compose-foundation-samples-1.3.0-alpha06-sources.jar",
          "size": 11577,
          "sha512": "ef7788b00bac24b58745711f135cb1531a1a51e70ec99cfb1b152628ad47491baa51f7c93cdbb965fd0830905e74d9aaf7723f76463c278413d7a93950451893",
          "sha256": "cd433dac8893ffbfdf1fa3a1c35de81e92e11fac1734a103f81a727e9cf7bece",
          "sha1": "19eb5bced32ccad5384f913607af81c843f9d552",
          "md5": "c95c50a712bc1e787fe875705f986f54"
        }
      ]
    }
  ]
}