{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-navigation-compose",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-compose-1.1.0-beta01.aar",
          "url": "hilt-navigation-compose-1.1.0-beta01.aar",
          "size": 4850,
          "sha512": "93c4fca62da9a774a4f96164c404e820d981f7a237532e46d31c3b5bfacb9a1225422675306305fe3783716ee9e2dc9bd715a964cbabba50dbe25e00f860abca",
          "sha256": "c1db649d8a1b48a2ec26a0f48e7d382d21b0f3c21cc23b5e3fc7f33e772acc6b",
          "sha1": "98f6931ca50b32cf0e26ec22dc096db7cc638941",
          "md5": "f1cfa8aa7055e5a33b1d3634750191d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-compose-1.1.0-beta01.aar",
          "url": "hilt-navigation-compose-1.1.0-beta01.aar",
          "size": 4850,
          "sha512": "93c4fca62da9a774a4f96164c404e820d981f7a237532e46d31c3b5bfacb9a1225422675306305fe3783716ee9e2dc9bd715a964cbabba50dbe25e00f860abca",
          "sha256": "c1db649d8a1b48a2ec26a0f48e7d382d21b0f3c21cc23b5e3fc7f33e772acc6b",
          "sha1": "98f6931ca50b32cf0e26ec22dc096db7cc638941",
          "md5": "f1cfa8aa7055e5a33b1d3634750191d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-navigation-compose-1.1.0-beta01-sources.jar",
          "url": "hilt-navigation-compose-1.1.0-beta01-sources.jar",
          "size": 1939,
          "sha512": "4ee3d72e2c5749983e264b391f4700f701e4c943a87451126a12eda7158e57a41540b6cbc35c2600bd113af371f5dd1bac85d42d46a758ebbc892a174d7f4f5f",
          "sha256": "be7ed1988e3852617ff26bf70caa10d1f50cca29da10913bac9508738645ad46",
          "sha1": "e7893e7c368282bbe28f1cf07846a645e6bfa8b1",
          "md5": "1427c47dcf1e6b4c5d79db482bdbe097"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "hilt-navigation-compose-1.1.0-beta01-versionMetadata.json",
          "url": "hilt-navigation-compose-1.1.0-beta01-versionMetadata.json",
          "size": 396,
          "sha512": "11207a4b88d32a772ea55f832a000fda113be10a1985ae2d29d7992c019d731b2da460d69128bae44ccc06d7d17905095b5a44486ec4e1ecb0b34d3b76e31a5d",
          "sha256": "259eb2d185d7a477c5a811ac8befd8d80262f5b6377a4536c8f622995a43cb52",
          "sha1": "d34422ef58ba160f6ab2b4601e7aaedad717c134",
          "md5": "00a128bba48bb600c50ab0b6ccd47c2c"
        }
      ]
    }
  ]
}