{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation/1.6.0-alpha06-topping02/animation-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.animation",
    "module": "animation",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation.klib",
          "url": "animation-iossimulatorarm64-1.6.0-alpha06-topping02.klib",
          "size": 209278,
          "sha512": "06897e2c39ac839c5bffc6b36ae7b6852ce586ed498fdd0f311d995a9cebcb156be67e5a6ccd3f18bdb0b276f62ca3a856572d5e8da2a364fa74488f1acb3fff",
          "sha256": "0c99c54cdecde9d0bc0bf83b3e19bf694fc3a47276f89d121d3738199631ff6b",
          "sha1": "c897c34e68bcb9b9394ecdfcd0d56772d0700405",
          "md5": "3274295e6aae571865d4b3bf095acb2f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "animation-iossimulatorarm64-1.6.0-alpha06-topping02-sources.jar",
          "url": "animation-iossimulatorarm64-1.6.0-alpha06-topping02-sources.jar",
          "size": 47874,
          "sha512": "56790bc88bb6e3001ded79383ccbe69a5dd15e1a9b66d30bd5dfd0921123b030c4a903d1d8d0249709c9804309ff65bb9239fa033e56df55d3f4ad9de4f2e853",
          "sha256": "a88625ddb3bf7a5c25ce47a76199bae4e89fd91d97c01e9412a8458bef63c6c9",
          "sha1": "e2f7093ab240689daabd14706889bfb59d34599f",
          "md5": "5a5cbbb0d23be967235b04c929f151d7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation-iossimulatorarm64-1.6.0-alpha06-topping02-metadata.jar",
          "url": "animation-iossimulatorarm64-1.6.0-alpha06-topping02-metadata.jar",
          "size": 4601,
          "sha512": "9717c50807eab9de6fb46d891485b274edc608d722225b3ea6fa7c2f2abc85d93bac2f4e23897b11bdcc67a056e772e12d61d1bbbebed348b32db86e1c068f83",
          "sha256": "4b1fca660511a5de1d7a4b42c648adef5c98360c9bc6399cd369cb253a39e076",
          "sha1": "a4a3d895bcc4657ac5037086aff167b838d4d696",
          "md5": "763686ad26202147182bf6eb31515f1e"
        }
      ]
    }
  ]
}