{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-geometry/1.6.0-alpha06-topping02/ui-geometry-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.ui",
    "module": "ui-geometry",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-geometry-desktop-1.6.0-alpha06-topping02.jar",
          "url": "ui-geometry-desktop-1.6.0-alpha06-topping02.jar",
          "size": 37750,
          "sha512": "0c4d341d8cbb5f1d507cfb04d2cf0c07d7e524c52b877b195a3d601fa0eabfa6c16caa585623d433ff84d71196dab78681231f78214541e710ee5f7925c3bffa",
          "sha256": "a464636481e6851e72f53080a32cdc4588c66358b6173d83eecbff50c135d7e7",
          "sha1": "645c8574b87a75991c8ff72bf1572302b7be36b5",
          "md5": "b6d60658727f953657669b0974927027"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-desktop-1.6.0-alpha06-topping02.jar",
          "url": "ui-geometry-desktop-1.6.0-alpha06-topping02.jar",
          "size": 37750,
          "sha512": "0c4d341d8cbb5f1d507cfb04d2cf0c07d7e524c52b877b195a3d601fa0eabfa6c16caa585623d433ff84d71196dab78681231f78214541e710ee5f7925c3bffa",
          "sha256": "a464636481e6851e72f53080a32cdc4588c66358b6173d83eecbff50c135d7e7",
          "sha1": "645c8574b87a75991c8ff72bf1572302b7be36b5",
          "md5": "b6d60658727f953657669b0974927027"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ui-geometry-desktop-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-geometry-desktop-1.6.0-alpha06-topping02-sources.jar",
          "size": 18278,
          "sha512": "9ea87e8be182c050396a1db751a23fd5e1aebede9e8ecfbc812801a831aa9f5106ce9a2a751eb2714b03e60fceffd2b55d5cbea57d83c58e1f0530d36b04c8d6",
          "sha256": "1cdb444bb73105531a91ef3b12098ada9392653e9ffc3d8d79ded19caa19253e",
          "sha1": "52669a9505a8bbcfa60523b6c52000050e3000d9",
          "md5": "13d5ab5d38f1f14f28c5ac635ebdccb5"
        }
      ]
    }
  ]
}