{
  "formatVersion": "1.1",
  "component": {
    "url": "../../paging-testing/3.3.0-alpha01/paging-testing-3.3.0-alpha01.module",
    "group": "androidx.paging",
    "module": "paging-testing",
    "version": "3.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "paging-testing-release.aar",
          "url": "paging-testing-android-3.3.0-alpha01.aar",
          "size": 78355,
          "sha512": "1e7f22cbbc2518519a929ef3549217d0f1b6418062db63d154235730c7a69eb793c09e233394efb50f6a66ccc3c807a671f5ecf2122a2428a2b033d98469caf8",
          "sha256": "edfbfe77b7b6440bed7a68b3cfc5417e0f10d7ea546137d8317dbde58103608a",
          "sha1": "d90128cd6a099a04bbc804b233180413d63bdd3f",
          "md5": "4a835d4c6be5dc5728323b5890fe00ae"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "paging-testing-release.aar",
          "url": "paging-testing-android-3.3.0-alpha01.aar",
          "size": 78355,
          "sha512": "1e7f22cbbc2518519a929ef3549217d0f1b6418062db63d154235730c7a69eb793c09e233394efb50f6a66ccc3c807a671f5ecf2122a2428a2b033d98469caf8",
          "sha256": "edfbfe77b7b6440bed7a68b3cfc5417e0f10d7ea546137d8317dbde58103608a",
          "sha1": "d90128cd6a099a04bbc804b233180413d63bdd3f",
          "md5": "4a835d4c6be5dc5728323b5890fe00ae"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "paging-testing-android-3.3.0-alpha01-sources.jar",
          "url": "paging-testing-android-3.3.0-alpha01-sources.jar",
          "size": 20636,
          "sha512": "440bbd80efbef12b31d38fe26c4e976737a3e037340c7b6b006458949f7d0d895818637ee5f66d68f0f77f1177f7d1e286a92ababc6cf2dcfc9336a64cca7674",
          "sha256": "a1c1a3f65d0245f2eddc3fbaa936a712b96cd567e584ef90d7686943acb69568",
          "sha1": "1e655e8735b3491c8a21b753ebf91b575b1fbf9d",
          "md5": "656d14f8d790e1076d184f20b3831d0d"
        }
      ]
    }
  ]
}