{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose",
    "version": "2.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.0-alpha01.aar",
          "url": "navigation-compose-2.8.0-alpha01.aar",
          "size": 1168407,
          "sha512": "078e78604b3d0edf1ff0466407a577d4d1ce92dc88e65199a2a90c0f71b44b8633b5e0e32c1b4c9ec904b7cc468991d9b36f26316333e0766fcce9ec4bd7cf7e",
          "sha256": "cce3d154e58ccbd1e62625a1d88e755752f9a8fa706bc8ddabbbcb9dcf71a836",
          "sha1": "0922efecf1aef868d0688c9d755781daf3517c65",
          "md5": "5106d9112f90f026062c3b5766f21d94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.0-alpha01.aar",
          "url": "navigation-compose-2.8.0-alpha01.aar",
          "size": 1168407,
          "sha512": "078e78604b3d0edf1ff0466407a577d4d1ce92dc88e65199a2a90c0f71b44b8633b5e0e32c1b4c9ec904b7cc468991d9b36f26316333e0766fcce9ec4bd7cf7e",
          "sha256": "cce3d154e58ccbd1e62625a1d88e755752f9a8fa706bc8ddabbbcb9dcf71a836",
          "sha1": "0922efecf1aef868d0688c9d755781daf3517c65",
          "md5": "5106d9112f90f026062c3b5766f21d94"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-compose-2.8.0-alpha01-sources.jar",
          "url": "navigation-compose-2.8.0-alpha01-sources.jar",
          "size": 14420,
          "sha512": "30f910c328d220ee4858f561fa14bd25b609fcca0d26abccde157752988785d8ed2dfc20f23c389cea121fec04de28c527f88d8abb1c9de83c79278e9f1d9ad0",
          "sha256": "61420672b653d3c4e05f99aece6c70d57e2710be1555ed76810012e135bf5f73",
          "sha1": "2808e840c7a7c40e9cd28ea178751d67344f8048",
          "md5": "84b6fd1ee7d3257e633b72bc1879f329"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "navigation-compose-2.8.0-alpha01-versionMetadata.json",
          "url": "navigation-compose-2.8.0-alpha01-versionMetadata.json",
          "size": 8353,
          "sha512": "3c11471a1ec374b0bda5fa66b496145f179b4b73dfb7fdd74ddfaa93e73fa054e467dc9202da4aa7c12025a2bdf99017993ae949ec6d0893f6947ba3b0040457",
          "sha256": "9639222017814bee96d67c4943190125ed61eaa474adb4cf5228ea0919372bc1",
          "sha1": "c56a89ebea37bc500b415af827c9aaaa1097ea46",
          "md5": "4c0a5021d58984b2d2531e24c7668c0e"
        }
      ]
    }
  ]
}