{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime",
    "version": "2.9.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.9.0-beta01.aar",
          "url": "work-runtime-2.9.0-beta01.aar",
          "size": 1838574,
          "sha512": "cef9f9e0213a5050cc60b836f4e24d564017095adee1bc6fa55c6c2fbc133901a2e27650b6206fc71fab7e136a517e562fb27e8136f3c394b94812d5f422e2c5",
          "sha256": "80b43f40f105559b2418c9a0012de9f77d13814356aa1ea8d37705255d82ea5d",
          "sha1": "cd0cc1b8c05ad34166a3cf2fa1130525a4b6380c",
          "md5": "dd1b555d486ee65e33549daa080e2bf1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.9.0-beta01.aar",
          "url": "work-runtime-2.9.0-beta01.aar",
          "size": 1838574,
          "sha512": "cef9f9e0213a5050cc60b836f4e24d564017095adee1bc6fa55c6c2fbc133901a2e27650b6206fc71fab7e136a517e562fb27e8136f3c394b94812d5f422e2c5",
          "sha256": "80b43f40f105559b2418c9a0012de9f77d13814356aa1ea8d37705255d82ea5d",
          "sha1": "cd0cc1b8c05ad34166a3cf2fa1130525a4b6380c",
          "md5": "dd1b555d486ee65e33549daa080e2bf1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-runtime-2.9.0-beta01-sources.jar",
          "url": "work-runtime-2.9.0-beta01-sources.jar",
          "size": 283940,
          "sha512": "4566ccbbe85f5d364d2858323e14e29246ffc6cca37ff7bf7a21a8799328312b3f7a948251953020e0f36be5a5c6cd2ae4671087ed164fe36ee6b1c73ffbeabf",
          "sha256": "126390739b7829758011628afd4133aff70b70326ca76ff9f9eb29e72fdae538",
          "sha1": "a1d06d250d3e0b02e6b39130481504b58e7777bc",
          "md5": "aa5a11ac86153b8671f3f44c3c5aceb3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "work-runtime-2.9.0-beta01-versionMetadata.json",
          "url": "work-runtime-2.9.0-beta01-versionMetadata.json",
          "size": 33850,
          "sha512": "acd556b415b5e9407dacdc8bc9cc69e8cf8484123a32db6139aa9cac1ecb7f7253bd2f68eab9404dd26086d421fecfddf965c21dbf1be8eb326cd41fb89fc403",
          "sha256": "1daddb1dd0351543a581b8bdf4d2a3604e58948ad9b12698cc89c4fc237e01f1",
          "sha1": "85416c7b35af5e2067e6cfb4b5969b2a3e5ef4f3",
          "md5": "b459dd1f2fbd47b5a04363833c7418bb"
        }
      ]
    }
  ]
}