{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit-samples",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-unit-samples-1.6.0-alpha06-topping01.aar",
          "url": "ui-unit-samples-1.6.0-alpha06-topping01.aar",
          "size": 10604,
          "sha512": "9800d50babfa378a95f4dc45e9609f1b082713c32fe9a1be09086e7c46997c24abd5f3eff8c68649d3ab4b47a1821893a6142b354e69d2bfa1aa0957850c6de7",
          "sha256": "fd0d616f0b088664b866e77d7b08cb5479de71a63c7ef755b4a684849272dfac",
          "sha1": "62b91f71639bba1c7f0309d093ca7d60396d08bc",
          "md5": "ccd330290af950f2b91bd24a03951868"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-samples-1.6.0-alpha06-topping01.aar",
          "url": "ui-unit-samples-1.6.0-alpha06-topping01.aar",
          "size": 10604,
          "sha512": "9800d50babfa378a95f4dc45e9609f1b082713c32fe9a1be09086e7c46997c24abd5f3eff8c68649d3ab4b47a1821893a6142b354e69d2bfa1aa0957850c6de7",
          "sha256": "fd0d616f0b088664b866e77d7b08cb5479de71a63c7ef755b4a684849272dfac",
          "sha1": "62b91f71639bba1c7f0309d093ca7d60396d08bc",
          "md5": "ccd330290af950f2b91bd24a03951868"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-samples-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-unit-samples-1.6.0-alpha06-topping01-sources.jar",
          "size": 2434,
          "sha512": "3a45878d8e38ac1c20e8cd9e80593d3a959a9d8149162417eea10f9d2fe9ba7b023e04e519dcd203a7ae8d00bd6ef655a52db78b3945809009d8022ced6e84ae",
          "sha256": "74d7bd3011c5994c91372888eaee211cea9a703511b393e64de4ddb2b43c7a29",
          "sha1": "08fb7a80854a4bbfde02b4b72fd216c225f1cadc",
          "md5": "bec4a89a0cd4bb66901afd45aa8512f9"
        }
      ]
    }
  ]
}