{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-livedata",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.6.0-alpha06-topping01.aar",
          "url": "runtime-livedata-1.6.0-alpha06-topping01.aar",
          "size": 7422,
          "sha512": "2d4065da28d07a6e908f776ec52101d78e7eda8252deca163c58ce635d46dabe8b5052c85014afe87e129bcf7d4f6533ffa8fca65ea126b9bc6e02f681fcbdee",
          "sha256": "069ea185c4c24db085707559e9ad732bcb69cca3d84ecd72b141e6fc473e5020",
          "sha1": "d2b20f358cad6ea37721eca974a7352e724185e3",
          "md5": "02ed3a7712d2590bc6aa61c283bca380"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.6.0-alpha06-topping01.aar",
          "url": "runtime-livedata-1.6.0-alpha06-topping01.aar",
          "size": 7422,
          "sha512": "2d4065da28d07a6e908f776ec52101d78e7eda8252deca163c58ce635d46dabe8b5052c85014afe87e129bcf7d4f6533ffa8fca65ea126b9bc6e02f681fcbdee",
          "sha256": "069ea185c4c24db085707559e9ad732bcb69cca3d84ecd72b141e6fc473e5020",
          "sha1": "d2b20f358cad6ea37721eca974a7352e724185e3",
          "md5": "02ed3a7712d2590bc6aa61c283bca380"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-livedata-1.6.0-alpha06-topping01-sources.jar",
          "url": "runtime-livedata-1.6.0-alpha06-topping01-sources.jar",
          "size": 1992,
          "sha512": "9a1aef66e5865f7a3b2a24d229625b37a44313e195b9816b804437dab5e7057fe292656a725ca0b2dbf569585e4b58751d29d967f38db582c8c9d8c230844c65",
          "sha256": "69c44e1bad36509f8fda98038744eda34ea38c4933e8843880a496cf98c1644f",
          "sha1": "1a4f182920dea19a06c5c52fca0e79683b09af68",
          "md5": "236f4943d08b1b73cdc32d28f018d6ab"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "runtime-livedata-1.6.0-alpha06-topping01-versionMetadata.json",
          "url": "runtime-livedata-1.6.0-alpha06-topping01-versionMetadata.json",
          "size": 284,
          "sha512": "84be62a9d5b9ae97907793a8ebc87c0e448a91f4c4ae42d67f53c45630e66205ef0d17759b22d7703349c32ea815f6a6dc6c01f469a670dc988001993ed7b109",
          "sha256": "fbac9e8cadc58948ce62b5a4f57b1700d6ac2d79c29371d346ee273f482211aa",
          "sha1": "a6cce6afecc6f4576261fe75c49484ad67558892",
          "md5": "20870ca81c05496ed1ba581d877a5745"
        }
      ]
    }
  ]
}