{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore/1.1.0-alpha05/datastore-1.1.0-alpha05.module",
    "group": "androidx.datastore",
    "module": "datastore",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore.klib",
          "url": "datastore-macosarm64-1.1.0-alpha05.klib",
          "size": 5144,
          "sha512": "0366d1f523937a92d411e019b2a308a1e0a2636d9e670ab0939b55366e239143fb3ecb7e1a8030aa462832144c86f01fd1a677b66e6d98f726889cb973e1ba9a",
          "sha256": "0f1d7ebd2a019f2ae1ba9095f38bda1c067f58c179f882063edf4aa9978a7dc1",
          "sha1": "4fb99c21e7439a2a67d447c50f3329981572b652",
          "md5": "5ef74c934f62b43179f58b076d345a62"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "datastore-macosarm64-1.1.0-alpha05-sources.jar",
          "url": "datastore-macosarm64-1.1.0-alpha05-sources.jar",
          "size": 1341,
          "sha512": "eab270f4091bd2aec5e4d32f1086186713c77bc914165c1045ac75e2f16f3470cee287e8286d7025dda724fc71158294c72abcaacdb89578713648c09841c76e",
          "sha256": "a72f12ea4109692cb5a60d961b2cbf25ffc611c3995dc645c9010f249a5db291",
          "sha1": "697a77e86cf0f0f4597fdf283224f63791cb29c3",
          "md5": "3cc4d627507697ca341bd6c1dd3ee8b4"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-macosarm64-1.1.0-alpha05-metadata.jar",
          "url": "datastore-macosarm64-1.1.0-alpha05-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}