{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto-handshake",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0-beta03.jar",
          "url": "tracing-perfetto-handshake-1.0.0-beta03.jar",
          "size": 25877,
          "sha512": "0eee32b5799551b368c87e496a04137c0133e239c508f6dbb2c50257e33024183acf55ed89badcd4f65b01ddc09cec2119421744942b91168f5eb71ed4577b04",
          "sha256": "2f2ee5c58561d72cabe9207c43669fe92d6c1386f8c1c2624489e6ab367b121e",
          "sha1": "b84cee5765fdde53d1be9be361db51951b908acd",
          "md5": "c264fe66be545db7c1804402c0a54ff1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0-beta03.jar",
          "url": "tracing-perfetto-handshake-1.0.0-beta03.jar",
          "size": 25877,
          "sha512": "0eee32b5799551b368c87e496a04137c0133e239c508f6dbb2c50257e33024183acf55ed89badcd4f65b01ddc09cec2119421744942b91168f5eb71ed4577b04",
          "sha256": "2f2ee5c58561d72cabe9207c43669fe92d6c1386f8c1c2624489e6ab367b121e",
          "sha1": "b84cee5765fdde53d1be9be361db51951b908acd",
          "md5": "c264fe66be545db7c1804402c0a54ff1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0-beta03-sources.jar",
          "url": "tracing-perfetto-handshake-1.0.0-beta03-sources.jar",
          "size": 8864,
          "sha512": "48613cfba53dd365042ca2cac7114f2131f6a4a21c9439aeca20b623e6f7635f6d7867e7d59e03b7df17d451c7ace761998edeaf02de48905c739b1858c08a42",
          "sha256": "8bd5a35f7a88a383b1fa1c6394cf3e65db7b1796f2bf8b9872977c3de2346fc9",
          "sha1": "beb02cc4aa20a8140cbdfceb15092e0ea943eeef",
          "md5": "ce5753d59ce5299b66f34234a983e09d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0-beta03-versionMetadata.json",
          "url": "tracing-perfetto-handshake-1.0.0-beta03-versionMetadata.json",
          "size": 2772,
          "sha512": "75e3470894a2f306313ba2f27aa4e4bda99f2584a5185dd2c32af3c425d1ac81dbef5e6ebb00774a36ee25c349f2180c3961a1ff76340d8359bb085e68b1ef45",
          "sha256": "da915a3807ff1b331c10d2d7c190451c769ced95781a1fcbb28c05993adea86d",
          "sha1": "066f0780664db486f8f3c477bcfa318e4dcd8379",
          "md5": "75a2b6c725d802bab6a5df9629377576"
        }
      ]
    }
  ]
}