{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "ui-tooling-1.6.0-alpha06-topping02-multiplatform-sources.jar",
          "url": "ui-tooling-1.6.0-alpha06-topping02-multiplatform-sources.jar",
          "size": 56511,
          "sha512": "aa218a8e6bf3fd1bb0c89ebe5fc3017d0e9a534677213ce448ccdb689d179d7bea896e0fe4e2d7bcde560dc7dba2a1c4b6d88f17e0da1203140b65f303763cf7",
          "sha256": "16a82cecca103ae122742295e51b04e922a1ed0c5224f789889e90e03ea9d905",
          "sha1": "fd582246b0ff2d6f90d44e99a10b595e34c79824",
          "md5": "5d93e665c99f179d44f0c387241afaff"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-tooling-1.6.0-alpha06-topping02-versionMetadata.json",
          "size": 1378,
          "sha512": "5075ed4a716a72ae814813eb582fa6dd61e0696bd44e5a1acd0a01ddf6496b40bff92f6ebdebbe8c94a5f9d6cd6289711c1ac8639875b4298475503aa5503c46",
          "sha256": "6ea2056fc132363968758e7eb177c0ab234b1732f33b498d33236da3b2e7fc9b",
          "sha1": "cdc182d031ab62627c1ee2722d9528f35c495eaa",
          "md5": "b5eee419bac3bf8fc5ca351cdc8261f6"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-metadata-1.6.0-alpha06-topping02.jar",
          "url": "ui-tooling-1.6.0-alpha06-topping02.jar",
          "size": 754,
          "sha512": "707c66d61a56bb77a685bba2b56c723d40a5d16f8229a3acda855185569ce6bd0d446ec9eeed3c036da2b73ed6946614dec3dc5844bb43f4dc55532117cbf827",
          "sha256": "8aa5917a4d40b53fa24a302c91fb2b2d7679d0e40df497cdba7c077db95447a8",
          "sha1": "0bdc84bce3c8982b7a46f17399e39e1d14d225f4",
          "md5": "0dfe4f3422a6c795f54f19c79214d06a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ui-tooling-kotlin-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-tooling-1.6.0-alpha06-topping02-sources.jar",
          "size": 4840,
          "sha512": "780eaa9ecb583c4558d7a2d41a88c1d89f5605e6843a7ea5c52c563760e9aecd0bc52600e3128227ea816677bf2f5be7943acb92d3a648ed4c51b71485a8b898",
          "sha256": "f01a0f8a40f36afd9f5d1379b4a5c691cd0ccd50a7b0b1608dbe8b4c69b0e50b",
          "sha1": "13bdf588a9201786a395784e6911b117c9393e79",
          "md5": "fb7eae97c9c776bcea3dc49fb391e887"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-tooling-android/1.6.0-alpha06-topping02/ui-tooling-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-tooling-android/1.6.0-alpha06-topping02/ui-tooling-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-tooling-android/1.6.0-alpha06-topping02/ui-tooling-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-tooling-desktop/1.6.0-alpha06-topping02/ui-tooling-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-tooling-desktop/1.6.0-alpha06-topping02/ui-tooling-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-tooling-desktop/1.6.0-alpha06-topping02/ui-tooling-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    }
  ]
}