{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-graphics/1.6.0-alpha06-topping01/animation-graphics-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.animation",
    "module": "animation-graphics",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics.klib",
          "url": "animation-graphics-iosx64-1.6.0-alpha06-topping01.klib",
          "size": 63687,
          "sha512": "2b8cbc9f2a5bccf4791cebd0236aed5ba09123968b866820b1ea4b3297d583460e521919c463918e64caa43b57fd126b0fc2862eb35732e729d242e8f1b4bc8b",
          "sha256": "65959d88945ec1758905db8188cc2c90f2ba2dbeb03a3a338fb44bf39e40e12a",
          "sha1": "bca41a57e888bce386f4f55a4e2e5bbb900bc0b2",
          "md5": "8157ba1d6276733f12f7da9774787dae"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "animation-graphics-iosx64-1.6.0-alpha06-topping01-sources.jar",
          "url": "animation-graphics-iosx64-1.6.0-alpha06-topping01-sources.jar",
          "size": 9732,
          "sha512": "bd328e229119895064294437871b229ca1a9600c010c6681567db24fbaa9a30766de126b31a03f8b4a7b684e8d897e1d6a846048d3bf03bacec198517a2ea705",
          "sha256": "4b5199c1daeac34210b5129c35b0053e2f749b5925953566c7db3847238e4697",
          "sha1": "c40b1403d7e7531da6cede16d594869aec78384d",
          "md5": "b950d4108d2dee3e861b4a916e5be96b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-iosx64-1.6.0-alpha06-topping01-metadata.jar",
          "url": "animation-graphics-iosx64-1.6.0-alpha06-topping01-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}