{
  "formatVersion": "1.1",
  "component": {
    "url": "../../paging-testing/3.3.0-alpha01/paging-testing-3.3.0-alpha01.module",
    "group": "androidx.paging",
    "module": "paging-testing",
    "version": "3.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "paging-testing.klib",
          "url": "paging-testing-iossimulatorarm64-3.3.0-alpha01.klib",
          "size": 56959,
          "sha512": "17102cec7391c683de352de3b4c08786fbb579af1c630243979893041fd8979587f2e4976c0ada9d6785d942687234a28a86e0bf7c26a6bd661a6f880516bf16",
          "sha256": "d6cf106f360ddcd386843b9ea3016c83082e4c35582376f6e1c54d92b97ca51e",
          "sha1": "bae9ed668efb881e986e176d0acc61c64acdf090",
          "md5": "27b3174181b02480dfe524a189848e2d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "paging-testing-iossimulatorarm64-3.3.0-alpha01-sources.jar",
          "url": "paging-testing-iossimulatorarm64-3.3.0-alpha01-sources.jar",
          "size": 20857,
          "sha512": "1849b31d059219af1252771a803089cb7f38892d8412349f10c6d8e1a0431898ba302e04034b8e58c3bb74b818a9adee893b468d434ceea7e27055fca079eb46",
          "sha256": "01543df4ca85f7b9e972b397a71ae900f42dc1eb5fa37a196e6b9bc4ee93476a",
          "sha1": "af8e9148471ff6e09760187bf645e8db7f6d05e7",
          "md5": "fc4c2fd66f512e17b99cba1f8b1a8636"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "paging-testing-iossimulatorarm64-3.3.0-alpha01-metadata.jar",
          "url": "paging-testing-iossimulatorarm64-3.3.0-alpha01-metadata.jar",
          "size": 4515,
          "sha512": "376292735ee5ccd9ced85b84b0ef25f7f470cbf5878c0ed4e1ed2cb4cae4d70112d1287a2360601bc1788a1ba699c8adb50d1fd8c77a548414d74b73bc720365",
          "sha256": "c0326a4341bb4cde41dd132028b4d2ead93da1fab428583a464d2541e961285c",
          "sha1": "ea8d360354e86dac87913f084e254e5ee70fb482",
          "md5": "34da84fe8c9d5f695f8fd793e65edaff"
        }
      ]
    }
  ]
}