{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation-layout/1.6.0-alpha06-topping01/foundation-layout-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-release.aar",
          "url": "foundation-layout-android-1.6.0-alpha06-topping01.aar",
          "size": 526149,
          "sha512": "aba7f1442a86fe3b05b16ee0584862d31addf1a0524ccbed47b6f5f2a243c959db2c4ecaee57542e6abff3d6bd6a7b8223df95e38e6ec060f2c55e12168ef675",
          "sha256": "2ddbdeb7510ed1da36b9b09929ddad43f883907d9e527571727f643a7237f10d",
          "sha1": "b8af5017b6c55276c645bfb2e19ba7afa156befc",
          "md5": "321c019328efe707a46ac74813c9043c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "foundation-layout-release.aar",
          "url": "foundation-layout-android-1.6.0-alpha06-topping01.aar",
          "size": 526149,
          "sha512": "aba7f1442a86fe3b05b16ee0584862d31addf1a0524ccbed47b6f5f2a243c959db2c4ecaee57542e6abff3d6bd6a7b8223df95e38e6ec060f2c55e12168ef675",
          "sha256": "2ddbdeb7510ed1da36b9b09929ddad43f883907d9e527571727f643a7237f10d",
          "sha1": "b8af5017b6c55276c645bfb2e19ba7afa156befc",
          "md5": "321c019328efe707a46ac74813c9043c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "foundation-layout-android-1.6.0-alpha06-topping01-sources.jar",
          "url": "foundation-layout-android-1.6.0-alpha06-topping01-sources.jar",
          "size": 78395,
          "sha512": "355df6739e82272578ead0c4470a385032aaff1e609e23f02b8796b1330f070583c441097c01824a6d8c68bea8859e1532a6222af396cccacfe8823af0369aa4",
          "sha256": "2311443121690ab47e4e54c451cc865b674f311cfdac10321af46fbdfecb9178",
          "sha1": "3890786bd417735921cc630ef792d736017193fe",
          "md5": "d5fd2fef14fab1fd822f3f84512e0e4e"
        }
      ]
    }
  ]
}