{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "material-icons-core-1.6.0-alpha06-topping02-multiplatform-sources.jar",
          "url": "material-icons-core-1.6.0-alpha06-topping02-multiplatform-sources.jar",
          "size": 557119,
          "sha512": "d538cfdb699d966d9c505af8cc8d8fbc328061df71d4a097c79ce6d2492e9dd0da83bbbbea52dc9ee523242bc3d08c8976021b939d804a0965ac0d7a2fd94bde",
          "sha256": "a352d0a0917b79c08bbd8b67157d78bdbe4b4cb27b93873c476420373a5afbde",
          "sha1": "a56d1edf0a047abadc22f56ecabd60e23159d0a4",
          "md5": "e0269feadeb9a5d604f26f09b8ad1384"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material-icons-core-1.6.0-alpha06-topping02-versionMetadata.json",
          "size": 60913,
          "sha512": "0e4af971ab53e478b39cd99e5aeff2b37753d8994f3df3c8952b7457cd2da2121ea46492e5dcb9f1c8dff780fa3896c5a17c9dc15e42c54fa0b61fa6d4a69dac",
          "sha256": "1933d0dfca7d5ffa9f68044483e45076ff8e872af9aadce2e423677b20195c6f",
          "sha1": "714ff9d654e02a70b03073823623cbca269feada",
          "md5": "84a674aeeb848d70e1d6195abeca87c5"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-metadata-1.6.0-alpha06-topping02.jar",
          "url": "material-icons-core-1.6.0-alpha06-topping02.jar",
          "size": 21395,
          "sha512": "5652ce668c1c7d4608210e1985d6fb2d373d3a576c10906c44192317bcaba672db5a0ff7c1c1730d8f04756c5ab5f9e857afa6d64996c2d7f0d90ad692ab0ca5",
          "sha256": "ab4c083e7c79cbab179c2026850928f5c15404eb09a7402ec434ca9a346e4245",
          "sha1": "413d3df12c5b575b5585e7b57aca4cb3dbb69aaf",
          "md5": "3602ea8faf2c37411e29a148b7d680db"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material-icons-core-kotlin-1.6.0-alpha06-topping02-sources.jar",
          "url": "material-icons-core-1.6.0-alpha06-topping02-sources.jar",
          "size": 283974,
          "sha512": "02d465292fe52dead7601c1ee5f5823f267fb2aeff6e6252c86e42f68a4810fd00cede92c047182a475041f1ef077358bbdfa9ed13a1fe3cce5d7713a485c704",
          "sha256": "38663dc3908f433c7704b02fe77e26179319d9a36a632df238fa5bbdfbe07710",
          "sha1": "f6d8ca49ccaa1ac695f9156ffc6a4e43b8b221b2",
          "md5": "f034303c181015a75e68965be14aca8e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-icons-core-android/1.6.0-alpha06-topping02/material-icons-core-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-icons-core-android/1.6.0-alpha06-topping02/material-icons-core-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-icons-core-android/1.6.0-alpha06-topping02/material-icons-core-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-icons-core-desktop/1.6.0-alpha06-topping02/material-icons-core-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-icons-core-desktop/1.6.0-alpha06-topping02/material-icons-core-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-icons-core-desktop/1.6.0-alpha06-topping02/material-icons-core-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-iosarm64/1.6.0-alpha06-topping02/material-icons-core-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-iosarm64/1.6.0-alpha06-topping02/material-icons-core-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-iosarm64/1.6.0-alpha06-topping02/material-icons-core-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-iossimulatorarm64/1.6.0-alpha06-topping02/material-icons-core-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-iossimulatorarm64/1.6.0-alpha06-topping02/material-icons-core-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-iossimulatorarm64/1.6.0-alpha06-topping02/material-icons-core-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-iosx64/1.6.0-alpha06-topping02/material-icons-core-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-iosx64/1.6.0-alpha06-topping02/material-icons-core-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-iosx64/1.6.0-alpha06-topping02/material-icons-core-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    }
  ]
}