{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "ui-unit-1.6.0-alpha06-topping01-multiplatform-sources.jar",
          "url": "ui-unit-1.6.0-alpha06-topping01-multiplatform-sources.jar",
          "size": 50636,
          "sha512": "fe11fdff49936ec9443de7ea9e8bb2d2652b2551d523490266c9b36b7afaa03f80e4393aeee8ced23f55a13e799870febd0cfb1dd7fdf24a7106c8a0d958b7e1",
          "sha256": "f061e6d23c564579a8b2c86cc95070dfeffad60188a69f4e11778b16b273e650",
          "sha1": "b9c0d3d586bcbb149c77a97cbd92453283e8de6e",
          "md5": "ad638d5b99f486f7d4478f2dfeba722a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-unit-1.6.0-alpha06-topping01-versionMetadata.json",
          "size": 16509,
          "sha512": "c11d4e8f5a3eca3aad6cd1d773b283282b391c50a5d1d30ac5053ad81c77418907ceb1ce127cd269a44f699da8f60deced17a6246589951ceaaced2ad574d3c1",
          "sha256": "b0be2033a382e5d11627f2eb3c3a53107e4a665096d44cbe90637f92b7ef1452",
          "sha1": "436839be41bb26083eeaef2f07811133d0bdcae7",
          "md5": "a5ba840b6e61e9bcb1225a2464ae2eff"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-metadata-1.6.0-alpha06-topping01.jar",
          "url": "ui-unit-1.6.0-alpha06-topping01.jar",
          "size": 9563,
          "sha512": "4d7ccb5d24c9469b7bb930ca49df67e56cf3e7d13680f0d599a7caeded16c6c51dcdba8edc5c4c4e1a345ce3e3bf34a35d8f3990a3036a09f5e95685741ea103",
          "sha256": "c461c3c0587302ecdc425213e88a13456720337317bc38276fd3f81547fb61e1",
          "sha1": "0c36729b498942ba7ffd2c8efe78ed48ae7129d2",
          "md5": "30684957754818c51d703a00efc774c1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ui-unit-kotlin-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-unit-1.6.0-alpha06-topping01-sources.jar",
          "size": 38240,
          "sha512": "2ef02aaa3d9cb94c5f3b27836ffb7a27e7b3ba175b62b67da3895abce475cca1025dc2c773babc79fe9de0de17bc61fb8c3e3de50034a7a271b5e782fb9fa45f",
          "sha256": "9e7b05d201bce91c2bab2cc381a50a77da716c0ad9d7f6489a7d1820db12981f",
          "sha1": "8a55a910bd03b3c0f751956d96c21a57fd757a87",
          "md5": "831184b296155ffc171bf3989afa303d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-unit-android/1.6.0-alpha06-topping01/ui-unit-android-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-android",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-unit-android/1.6.0-alpha06-topping01/ui-unit-android-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-android",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-unit-android/1.6.0-alpha06-topping01/ui-unit-android-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-android",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-unit-desktop/1.6.0-alpha06-topping01/ui-unit-desktop-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-desktop",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-unit-desktop/1.6.0-alpha06-topping01/ui-unit-desktop-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-desktop",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-unit-desktop/1.6.0-alpha06-topping01/ui-unit-desktop-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-desktop",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-unit-iosarm64/1.6.0-alpha06-topping01/ui-unit-iosarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-iosarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-unit-iosarm64/1.6.0-alpha06-topping01/ui-unit-iosarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-iosarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-unit-iosarm64/1.6.0-alpha06-topping01/ui-unit-iosarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-iosarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-unit-iossimulatorarm64/1.6.0-alpha06-topping01/ui-unit-iossimulatorarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-unit-iossimulatorarm64/1.6.0-alpha06-topping01/ui-unit-iossimulatorarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-unit-iossimulatorarm64/1.6.0-alpha06-topping01/ui-unit-iossimulatorarm64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-unit-iosx64/1.6.0-alpha06-topping01/ui-unit-iosx64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-iosx64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-unit-iosx64/1.6.0-alpha06-topping01/ui-unit-iosx64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-iosx64",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-unit-iosx64/1.6.0-alpha06-topping01/ui-unit-iosx64-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.ui",
        "module": "ui-unit-iosx64",
        "version": "1.6.0-alpha06-topping01"
      }
    }
  ]
}