{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "1.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tracing-1.3.0-alpha02.aar",
          "url": "tracing-1.3.0-alpha02.aar",
          "size": 6094,
          "sha512": "d91911dd81a69f71f1713822b1b61897b12309cd39d912ed1848cf1fa8cd5428eea44270c84ec24474f3a10cd909004238b4702f0d459fe47c8b0da4a193becf",
          "sha256": "166b43833a58c77af54bef1d09cfd98e7cf0153f7fe6cf2cb110b8cdbe0ab3e2",
          "sha1": "bb407dd2a161d40168c611d5a99e41c2f71586b9",
          "md5": "cd91ffaee0186f3a28d7a3e3422096e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-1.3.0-alpha02.aar",
          "url": "tracing-1.3.0-alpha02.aar",
          "size": 6094,
          "sha512": "d91911dd81a69f71f1713822b1b61897b12309cd39d912ed1848cf1fa8cd5428eea44270c84ec24474f3a10cd909004238b4702f0d459fe47c8b0da4a193becf",
          "sha256": "166b43833a58c77af54bef1d09cfd98e7cf0153f7fe6cf2cb110b8cdbe0ab3e2",
          "sha1": "bb407dd2a161d40168c611d5a99e41c2f71586b9",
          "md5": "cd91ffaee0186f3a28d7a3e3422096e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracing-1.3.0-alpha02-sources.jar",
          "url": "tracing-1.3.0-alpha02-sources.jar",
          "size": 6669,
          "sha512": "9cab150e14d849a582bcc5438d666140a83c40d33515fd4b351f3d06e0a5705f99b708d5704ef956adf5ecd0468478a810dd5c4e5ec995baace06038cf54d5c7",
          "sha256": "cd07d09b3bfe9c030f4e011f466abb5c9dcdebc5b733e1720001d9061ef6c5cd",
          "sha1": "834420765f3dd56e0ef9bf7f161d994fb1a3b9aa",
          "md5": "ee8300d6f3fded5df4b4f92228fe72d0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "tracing-1.3.0-alpha02-versionMetadata.json",
          "url": "tracing-1.3.0-alpha02-versionMetadata.json",
          "size": 486,
          "sha512": "79982aae27cb4810b2a3ec60ba72d8cf90826fcf05a249a1fdb8d2e4178535335d51ee6c70c8741eb9cc910014f79685caa3ba72e14d34dbbdb69bd4d9e6b871",
          "sha256": "158b9e371bff484ef0cde9d03e02896a3c31b380024948a45f881ec24407d1da",
          "sha1": "43c9aca539d72d33534f759e73179b2d8274fbf8",
          "md5": "e556b0f2b9f36f0bf0066524a73d390e"
        }
      ]
    }
  ]
}