{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-navigation",
    "version": "1.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "compose-navigation-1.3.0-alpha06.aar",
          "url": "compose-navigation-1.3.0-alpha06.aar",
          "size": 48882,
          "sha512": "137741ba4bc9596e8aaa67e57e3a779a6a23559aad591717ad7884530b5fb5888183a014319a23eb9051299896768b71632018db3c8441abc5afd0c3dfd76b13",
          "sha256": "3e3f3dbd664614584ae4003a8a73c4631453f822c540b6540885219dfa267229",
          "sha1": "a4f4eaf02379ca5bd6d49cb4e6d4d1a88f2ac200",
          "md5": "592faedc92530e3a8387dc7502a103fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "compose-navigation-1.3.0-alpha06.aar",
          "url": "compose-navigation-1.3.0-alpha06.aar",
          "size": 48882,
          "sha512": "137741ba4bc9596e8aaa67e57e3a779a6a23559aad591717ad7884530b5fb5888183a014319a23eb9051299896768b71632018db3c8441abc5afd0c3dfd76b13",
          "sha256": "3e3f3dbd664614584ae4003a8a73c4631453f822c540b6540885219dfa267229",
          "sha1": "a4f4eaf02379ca5bd6d49cb4e6d4d1a88f2ac200",
          "md5": "592faedc92530e3a8387dc7502a103fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-navigation-1.3.0-alpha06-sources.jar",
          "url": "compose-navigation-1.3.0-alpha06-sources.jar",
          "size": 7938,
          "sha512": "16291d7afe047faa90351f1a2a3274bb9780b738a1663cb769da00febd775341535bd4d65ce2e468ffc37ab1a5d55133171be0001791e8a579cd512045d1a963",
          "sha256": "9aee62b235f69cc4dbd838a583d57c3a0fe62ee27107ab2dcc37c2e31770d9e9",
          "sha1": "c9563beceaee03c513195da3603dd51be7d2950d",
          "md5": "890a91d3fa7f37bb712c621545c05b99"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "compose-navigation-1.3.0-alpha06-versionMetadata.json",
          "url": "compose-navigation-1.3.0-alpha06-versionMetadata.json",
          "size": 3368,
          "sha512": "f5a9b97fdbdd6df98c2aba76b9ad9a6560f220e2de68d78575eebdab8d36c00a9805f370b3eadb42449ed643a996f01958daff4654733acebc04b9a194b59a2a",
          "sha256": "aae15ee65209425859fc8fd8bf1dd613c0bb2b34b2d28a2937783f6059352280",
          "sha1": "3f43dea0c049b3733e17c3fda9018a045e585bcb",
          "md5": "b17b615bb2a1655eb7ae4a451e05471a"
        }
      ]
    }
  ]
}