{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit-samples",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-unit-samples-1.6.0-alpha06-topping02.aar",
          "url": "ui-unit-samples-1.6.0-alpha06-topping02.aar",
          "size": 10604,
          "sha512": "bc6e149f521b36125d8d86f3dd8e4a3e6cdc698ad50fb6ab7cf9f36f772ae1d3bb3abaa965ce46f7bc0fac5504bd3711f12cbf5f8a55702b9bf31e9d30ec7f8a",
          "sha256": "764e809db9b4459031989a4f540959ee82d586cd99e50f9abf13b4d9a557c854",
          "sha1": "254a326f9ef26cb86219106759f995bbbb6f7133",
          "md5": "22884b35965f31277f44b37d0c216967"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-samples-1.6.0-alpha06-topping02.aar",
          "url": "ui-unit-samples-1.6.0-alpha06-topping02.aar",
          "size": 10604,
          "sha512": "bc6e149f521b36125d8d86f3dd8e4a3e6cdc698ad50fb6ab7cf9f36f772ae1d3bb3abaa965ce46f7bc0fac5504bd3711f12cbf5f8a55702b9bf31e9d30ec7f8a",
          "sha256": "764e809db9b4459031989a4f540959ee82d586cd99e50f9abf13b4d9a557c854",
          "sha1": "254a326f9ef26cb86219106759f995bbbb6f7133",
          "md5": "22884b35965f31277f44b37d0c216967"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-samples-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-unit-samples-1.6.0-alpha06-topping02-sources.jar",
          "size": 2434,
          "sha512": "3a45878d8e38ac1c20e8cd9e80593d3a959a9d8149162417eea10f9d2fe9ba7b023e04e519dcd203a7ae8d00bd6ef655a52db78b3945809009d8022ced6e84ae",
          "sha256": "74d7bd3011c5994c91372888eaee211cea9a703511b393e64de4ddb2b43c7a29",
          "sha1": "08fb7a80854a4bbfde02b4b72fd216c225f1cadc",
          "md5": "bec4a89a0cd4bb66901afd45aa8512f9"
        }
      ]
    }
  ]
}