{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.4.0-alpha01/collection-1.4.0-alpha01.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "collection.klib",
          "url": "collection-iossimulatorarm64-1.4.0-alpha01.klib",
          "size": 763808,
          "sha512": "f42e58142f5f1b0f5126e3cda8ceb9b80778e58f4d0b200504574b8c035a600aa9da2bd910dbd69a25529f335fedead8136bbc3b26013c01b2d02a63baab9ddb",
          "sha256": "7ce780d77d3129d80be1e44fe67249b890797af889def8b871b2ea2d0c021b7b",
          "sha1": "840aa22cb7dd97924a1ee2283116d307d4e73cd1",
          "md5": "aa8ee8de23688f9211c84e6e33115f7b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "collection-iossimulatorarm64-1.4.0-alpha01-sources.jar",
          "url": "collection-iossimulatorarm64-1.4.0-alpha01-sources.jar",
          "size": 224252,
          "sha512": "6654417d0d951598295f6c257977e86a32d90d2caad281df84bc37a83bbe5fb2e1ef62ccfa71a8755e34063bdd58a5a800ededde076cd15caf91925409429ee2",
          "sha256": "edce797935c456b7c61872b27d6fe6db2617f041b9d45141e10bb79162c84e58",
          "sha1": "c7ada6e24c33d4d876c5bb4657b91911558ab9f3",
          "md5": "d147ca64d6e182c23bc3de657f636ef3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "collection-iossimulatorarm64-1.4.0-alpha01-metadata.jar",
          "url": "collection-iossimulatorarm64-1.4.0-alpha01-metadata.jar",
          "size": 9721,
          "sha512": "569dc2841b2710f43effaa56df8f1972427fba6fee35563e2292077134c05b0f9335cd7a0f95ab6932c0ed9cba655f1a0c6adf5467f9f3eda67b095744d1396a",
          "sha256": "fc79952ef5da5aa6dd703db4d4361e3b6e138f5faaeedee2f3eb15bf3c60bb1b",
          "sha1": "4e8938832b7873b5c15ad449436b732300ec97b2",
          "md5": "86adc707dd8c178925fd32114636e5c2"
        }
      ]
    }
  ]
}