{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-util/1.6.0-alpha06-topping02/ui-util-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util.klib",
          "url": "ui-util-iosarm64-1.6.0-alpha06-topping02.klib",
          "size": 297248,
          "sha512": "0c097ac2e98b1ce20fe6d10b1eb6b741acba518451ffdb986f08c9b2be15011692fd6bf012d94d04d9d38b9c4a0e61c75ca5c833996f421bb81c80719adcf7f9",
          "sha256": "19e94a2780bbdc6e12e7ef6be30dd8dce7bb16bbdd5f5d3568e589a4d3891e35",
          "sha1": "0712c1e5b5c6adda22b7252027c5ed446d460a01",
          "md5": "122e2e4802bc2c4ac9b746adb6fdfa72"
        },
        {
          "name": "ui-util-cinterop-Topping.klib",
          "url": "ui-util-iosarm64-1.6.0-alpha06-topping02-cinterop-Topping.klib",
          "size": 516274,
          "sha512": "3caa49f5dc21f213ec9ebcda51658dc73721905c6d921ffe3ed0e52a5367504a530bce9aec40f50a3248ff643405c4fb0b7852de9d8c3a8ac4b2f31f7cc0b86e",
          "sha256": "e3b79ac5ea60aa1bc80e6d26e6a21085050d007d7d4a908f21c2fbd832343d4b",
          "sha1": "1deff7b7b62b04d12d8a4d5764ea8314c383d28c",
          "md5": "aaf499a3bc9e8ad2e0d7ad6b07576eb2"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-util-iosarm64-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-util-iosarm64-1.6.0-alpha06-topping02-sources.jar",
          "size": 49437,
          "sha512": "0c7c8ac4fd8cedec0c4c481c79271dd45d3d42f467114ccf914454cbd82b15762f581c66b99f2ecd19ae3429ff05d13b9ed32e2328804f9130cbad47087d4e17",
          "sha256": "53604cf7632425556d06d35e081724f43b45e95acc7c1d08b8674ebe6dffa286",
          "sha1": "e38013e6193f863df96034694cb7e497110078dd",
          "md5": "37f03c04a674baec1f158a315ff405be"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-iosarm64-1.6.0-alpha06-topping02-metadata.jar",
          "url": "ui-util-iosarm64-1.6.0-alpha06-topping02-metadata.jar",
          "size": 440988,
          "sha512": "3166e321a7fa4477760f82fa296c6562831e26dbbb65a65f23803f6b2773fe1c43eee1ab47d13c275ce424655f091d770fe00a8f6e755a2e262f425129dcc96b",
          "sha256": "f7e89988de86eb1634d43310c3678760473c26fff35e8f13c613cd554df88037",
          "sha1": "1721d5bc347137a89306a2ead4a86b9296cbe97c",
          "md5": "1dbf496650be31e5355f429f39885567"
        }
      ]
    }
  ]
}