{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-core-okio/1.1.0-alpha05/datastore-core-okio-1.1.0-alpha05.module",
    "group": "androidx.datastore",
    "module": "datastore-core-okio",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio.klib",
          "url": "datastore-core-okio-macosarm64-1.1.0-alpha05.klib",
          "size": 22617,
          "sha512": "1344b7cc753c661f5c46b4001cd4f8ce79dd88609e99a9b4003baa69c165dec384598345fd721d132dd30adeeecc238db16e4fd28b34a6b52d2cac96e126eb96",
          "sha256": "9ec82080428d42a81c78c0ec807d0c077a14528d5f517bf121cc6c27cad607a2",
          "sha1": "2849e7b4ade6c3db869e0480211942828f1ae29f",
          "md5": "c13a5a41affec808f68fbac1c580fffe"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "datastore-core-okio-macosarm64-1.1.0-alpha05-sources.jar",
          "url": "datastore-core-okio-macosarm64-1.1.0-alpha05-sources.jar",
          "size": 6713,
          "sha512": "bb6715ac20bc0b1f1cc23285c2b6aff110d21ca977ac517d50f147f551ee82678bfa4f2c7ac35f1ae2082863c4f072fe07935c859d7ae0b1c13e9f6b3e534c11",
          "sha256": "a3ece0a07b062b2807ebdd6e7008a8814f32960309cb72c170228ee57e23090f",
          "sha1": "2e33b29e05c3f49f2a09e3540a1e83bd0e8acef9",
          "md5": "801cbb3011ef9caa44b3f50e72a68cf0"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-macosarm64-1.1.0-alpha05-metadata.jar",
          "url": "datastore-core-okio-macosarm64-1.1.0-alpha05-metadata.jar",
          "size": 4559,
          "sha512": "30438014eafbdf3945bccf7ea3bedd90330d2dcfe1d0b8eff09de93ac1911f1728fc7eac8ee45754ed5f71ddcfeb347fb66960a1e831e7c351f0d1bf928e43b7",
          "sha256": "b8def86be262058708cccf246139bae71e81a58312503e334a03f175b12aa076",
          "sha1": "66eaf1b058ac14df14594be944dda0b7c322c87e",
          "md5": "c28f882a3a483f1bea921c1c2d8d329f"
        }
      ]
    }
  ]
}