{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate-ktx",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-alpha01.aar",
          "url": "savedstate-ktx-1.3.0-alpha01.aar",
          "size": 2962,
          "sha512": "ae9266f673dbd0c1df93cc887b054f6906c531944041d53c0bd89bc18a256eb5084dc0061ea8db140b2d6fc206eb2761be4f139870e0a53edf1f247faf4bf2dc",
          "sha256": "8214af9d11f0eb5f1f467251d66defc095408433d6418480a82105ab675b43de",
          "sha1": "f9580b2f169bf939e9312d49136f49be30f1c245",
          "md5": "02ddbfd642fc6dbeeb9d945591a6c612"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-alpha01.aar",
          "url": "savedstate-ktx-1.3.0-alpha01.aar",
          "size": 2962,
          "sha512": "ae9266f673dbd0c1df93cc887b054f6906c531944041d53c0bd89bc18a256eb5084dc0061ea8db140b2d6fc206eb2761be4f139870e0a53edf1f247faf4bf2dc",
          "sha256": "8214af9d11f0eb5f1f467251d66defc095408433d6418480a82105ab675b43de",
          "sha1": "f9580b2f169bf939e9312d49136f49be30f1c245",
          "md5": "02ddbfd642fc6dbeeb9d945591a6c612"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-alpha01-sources.jar",
          "url": "savedstate-ktx-1.3.0-alpha01-sources.jar",
          "size": 1225,
          "sha512": "d812ea33eec5f78bf8ed100cc6bf380eba622431c31bdf1a75a9cf76fde4ee6d182b8802ccc0a372802da84374aaea1610a13f6dff5af79e7714a0593dc1988f",
          "sha256": "e7358cf9632e601c29d474a74a60e92d7dd8db2c9af9b61cc4aa1272c3fa8945",
          "sha1": "0d783d773dc93c5dce787027d00f5c07cfa5cf84",
          "md5": "c4f06a5e164522c946f7a8fea8675246"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-alpha01-versionMetadata.json",
          "url": "savedstate-ktx-1.3.0-alpha01-versionMetadata.json",
          "size": 191,
          "sha512": "225072cf1e54fc7479700f5339019ceafe1f9e4d514a8893a626190d42dfb31b35804c73597292ee864e5f3034bc73b4c5806109ed130eb268c531948a4be4b7",
          "sha256": "ff1847220d3c526a133e4f76baed2060de09a72ac96f5b8e1fef2ab1d21ba85e",
          "sha1": "a1a2692ed79fa0caa20fafeb33e56bd48993f6de",
          "md5": "57c4eed7a9c15485d30d344fdc944a0a"
        }
      ]
    }
  ]
}