{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling-data/1.6.0-alpha06-topping01/ui-tooling-data-1.6.0-alpha06-topping01.module",
    "group": "androidx.compose.ui",
    "module": "ui-tooling-data",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-data-release.aar",
          "url": "ui-tooling-data-android-1.6.0-alpha06-topping01.aar",
          "size": 36861,
          "sha512": "6802d0d1a395177d768d58e0ad7de09ee1103280f6cfc2f25f5f4421afc8367110cf355ac0f6b35732e7af40683cf9e91db357f9bd61d6e50022664c723584a2",
          "sha256": "d2b1e74376ea5fc9107f7e1ce7007b5ccc986110e51f481b5a40a8fffeed821b",
          "sha1": "465e3e02aca16c989294b9ce5411b94e02c908e9",
          "md5": "30c299dc2e01ffa27bd97273ad92b9b9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ui-tooling-data-release.aar",
          "url": "ui-tooling-data-android-1.6.0-alpha06-topping01.aar",
          "size": 36861,
          "sha512": "6802d0d1a395177d768d58e0ad7de09ee1103280f6cfc2f25f5f4421afc8367110cf355ac0f6b35732e7af40683cf9e91db357f9bd61d6e50022664c723584a2",
          "sha256": "d2b1e74376ea5fc9107f7e1ce7007b5ccc986110e51f481b5a40a8fffeed821b",
          "sha1": "465e3e02aca16c989294b9ce5411b94e02c908e9",
          "md5": "30c299dc2e01ffa27bd97273ad92b9b9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ui-tooling-data-android-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-tooling-data-android-1.6.0-alpha06-topping01-sources.jar",
          "size": 9037,
          "sha512": "0a4d519fa714f9311404ea2ffe58136eb17719a373fee54bfabfd47dd84ac03a3fa3838e022e24a677f51c78b6bdcdba681f9c810cc26248ca4d7845d10b2e84",
          "sha256": "d030df2ebc4b8ade5437227186fc7f32b60fc2d1e0c697415f2ad2004e81047b",
          "sha1": "faa62ec7c94b6b0025dd79225da9590361036ef7",
          "md5": "61cbd844518e19f91c0c46e31534697a"
        }
      ]
    }
  ]
}