{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-core/1.1.0-alpha05/datastore-core-1.1.0-alpha05.module",
    "group": "androidx.datastore",
    "module": "datastore-core",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-core.klib",
          "url": "datastore-core-macosx64-1.1.0-alpha05.klib",
          "size": 57000,
          "sha512": "1974995b118a42da9277e2e01d2a621bcbe7ed045f700a181be2577749f47e59552dd363ce56f8c81c40c929d6b540bfb486273f5cb258660a2fde8a2ff0c47e",
          "sha256": "0ae339d8609c465301f2f8073ee13ed030fe5c7d64011395ab39202c36140ea9",
          "sha1": "e62d4149c1bde75ed7a21b3900a5ed6e09fb1bc7",
          "md5": "1724d638a7f07896e94a0441aa79cb7e"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "datastore-core-macosx64-1.1.0-alpha05-sources.jar",
          "url": "datastore-core-macosx64-1.1.0-alpha05-sources.jar",
          "size": 33635,
          "sha512": "89a9fae35aca5677651779bf13ba095716ec7fc4f4cf5b9ad3fe2ba612a34cfb42f04393ebe28d86b19df15549fb5e01f3a5d10856c4a52df3c10c3e6db65ee6",
          "sha256": "2a206ad8deb0f03246bb1e69dc759aae07f6db3b1fdb174d36a9c7ed6d562660",
          "sha1": "1b87fb86f075cc68ea5f0cd0211109014fd47bd7",
          "md5": "3622d18701162367658b62a56d4bb4c8"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-core-macosx64-1.1.0-alpha05-metadata.jar",
          "url": "datastore-core-macosx64-1.1.0-alpha05-metadata.jar",
          "size": 5429,
          "sha512": "1c199e1df3a1df5add7128ba16352f371d8b373adb196015e23b0d477a08cd21ee4e48f61e6892e2ee1d6cea8e5206965c25c6f714d0e9a32302beeb6fe433ef",
          "sha256": "090b10214eec87eb605c41b9dd30cb6887861d9ad22f54673462e0cdf57fff1a",
          "sha1": "9b14b7025f0fda214c21d3c7252d1ec20782ee89",
          "md5": "d7545e064d84fc3d2ee0e4633a84e5ed"
        }
      ]
    }
  ]
}