{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.7.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.7.0-alpha02.aar",
          "url": "lifecycle-runtime-ktx-2.7.0-alpha02.aar",
          "size": 60555,
          "sha512": "fe3793bfcf9d1fa4df547d0bf8bb564f4c7a38d36b2b3f5722e100e93093be32bbe463c2e638420a676ee6894c051cdc54a979e5b5457d9462eead940b99acc7",
          "sha256": "e25af84fc102e2acbbe0aa00494c9691d0deed1b5f90bc7416418f8a74607df5",
          "sha1": "ecb85dade65471e7fc03182aa25e5d09400c61d5",
          "md5": "9970d6b8fe0d92b77ebf5cfd89381087"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.7.0-alpha02.aar",
          "url": "lifecycle-runtime-ktx-2.7.0-alpha02.aar",
          "size": 60555,
          "sha512": "fe3793bfcf9d1fa4df547d0bf8bb564f4c7a38d36b2b3f5722e100e93093be32bbe463c2e638420a676ee6894c051cdc54a979e5b5457d9462eead940b99acc7",
          "sha256": "e25af84fc102e2acbbe0aa00494c9691d0deed1b5f90bc7416418f8a74607df5",
          "sha1": "ecb85dade65471e7fc03182aa25e5d09400c61d5",
          "md5": "9970d6b8fe0d92b77ebf5cfd89381087"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.7.0-alpha02-sources.jar",
          "url": "lifecycle-runtime-ktx-2.7.0-alpha02-sources.jar",
          "size": 7212,
          "sha512": "a120028a6cfcf9d3b246b15248b07e3a72f343e5666fa155bf683e0f118ceb4e50231571f0529333c860f974cbd399dc1f9b68ba82c90e7a44ef7c7c8f6f7df8",
          "sha256": "166770a5ac5146d6c81f1c49b699e1b5dfa70389098e7b1de1f088a38a78d605",
          "sha1": "1c78b6d8a908dfe6b2e6374680eefb81c858ad9b",
          "md5": "18b3517e511dc9dec5baf67800c44aa4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.7.0-alpha02-versionMetadata.json",
          "url": "lifecycle-runtime-ktx-2.7.0-alpha02-versionMetadata.json",
          "size": 5626,
          "sha512": "242d65cd5f1722e8fdc7e93ba2b8e5ff9fafe9f177121cba3396c4ac88b960e3965e14f216abe88c1c477442bc575903d999e8425d720aa1a24d98dc463def8b",
          "sha256": "662fd0b56b32374f67e4c4f601336adc631351273931be028a95caf4325de113",
          "sha1": "9fc09f10cb45d0f8cbb38b77c9ff0a17aca0721c",
          "md5": "b8b42a5c729f517783da7216e4e31ab7"
        }
      ]
    }
  ]
}