{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-core/1.1.0-alpha05/datastore-core-1.1.0-alpha05.module",
    "group": "androidx.datastore",
    "module": "datastore-core",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-core-release.aar",
          "url": "datastore-core-android-1.1.0-alpha05.aar",
          "size": 182819,
          "sha512": "d4865ce41e693a49ac9697f9d1981f1f1d6c98b52979152b98ed950c8825507a5faec2d0a08d33b66f0d39d85cd253e3e03316a85767163ea3928a27d173b286",
          "sha256": "92614b1d1c8096ff5984282772104089c4a1a77d5926b19ff64a943730c6efc3",
          "sha1": "e7a38c85e6592671b46cc17b51cb00ed4421add0",
          "md5": "3202284e09d7eb0b700466efda533138"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "datastore-core-release.aar",
          "url": "datastore-core-android-1.1.0-alpha05.aar",
          "size": 182819,
          "sha512": "d4865ce41e693a49ac9697f9d1981f1f1d6c98b52979152b98ed950c8825507a5faec2d0a08d33b66f0d39d85cd253e3e03316a85767163ea3928a27d173b286",
          "sha256": "92614b1d1c8096ff5984282772104089c4a1a77d5926b19ff64a943730c6efc3",
          "sha1": "e7a38c85e6592671b46cc17b51cb00ed4421add0",
          "md5": "3202284e09d7eb0b700466efda533138"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "datastore-core-android-1.1.0-alpha05-sources.jar",
          "url": "datastore-core-android-1.1.0-alpha05-sources.jar",
          "size": 47513,
          "sha512": "00ec82aa66a2c0515d071caf66afccdab107754a22eb525c8743ad12537c468de8299d23e78be2c52f6ce25dd0c265bdfb5473817b12e4e8140a12082f6adfa4",
          "sha256": "d503e0f501f9f469ff62eab056260a3323db2b579127de41898082f1a1ea8b3e",
          "sha1": "36946f0c6ac2f3acb1280f0529119722c1a56e2b",
          "md5": "6acb96550d318017e7ed57e3e9739a6a"
        }
      ]
    }
  ]
}