{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window.extensions.core",
    "module": "core",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.1.0-alpha01.aar",
          "url": "core-1.1.0-alpha01.aar",
          "size": 3771,
          "sha512": "c6b55b27d1f07d010951379bd1e7e94d2ba992f2a780016e633d5b1cf955b61cb043de7d550072e94232ee8089f94b671fe06f58873b8974745c84ca11ad4f44",
          "sha256": "d9a7ff6219cfebbf7c6d703183bf1e028c6d8bc63641501533f479fd862d6efe",
          "sha1": "47c762977968430073a100044c26f7e93cb28a7a",
          "md5": "5a1d6452f6582fd2c3aead0ab5e2e970"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.1.0-alpha01.aar",
          "url": "core-1.1.0-alpha01.aar",
          "size": 3771,
          "sha512": "c6b55b27d1f07d010951379bd1e7e94d2ba992f2a780016e633d5b1cf955b61cb043de7d550072e94232ee8089f94b671fe06f58873b8974745c84ca11ad4f44",
          "sha256": "d9a7ff6219cfebbf7c6d703183bf1e028c6d8bc63641501533f479fd862d6efe",
          "sha1": "47c762977968430073a100044c26f7e93cb28a7a",
          "md5": "5a1d6452f6582fd2c3aead0ab5e2e970"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.1.0-alpha01-sources.jar",
          "url": "core-1.1.0-alpha01-sources.jar",
          "size": 3620,
          "sha512": "0b489f58642fb2837ff017dc34d1c1c1aa8b3494642f844afed0a327db741791fc447335ab37c558360dc6b5f92e370e7b20d4b7f1ec272a515a622ba155524f",
          "sha256": "2b813f2bf87717a263c3b8edf6ddf70f1b211078728a660689a0b810bc67567d",
          "sha1": "25808e871b7b8a0be367bb9d180f8de6e8b7579f",
          "md5": "45f8d4c031529cb37bc2f8c643e13e02"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.1.0-alpha01-versionMetadata.json",
          "url": "core-1.1.0-alpha01-versionMetadata.json",
          "size": 449,
          "sha512": "5886cb5b31c6b6d316ed2eb88504f82ac0cf6ba5189ed701db0ec5889c06b6811b217731147c2754debe27e5d72eecc1e72c5409eda8bd5f2968a2214808e916",
          "sha256": "fddaf725f11c8bf2dafbd4bbe45e58a02ef79ca131cf91df37a6018f7f143053",
          "sha1": "c649362b3fe78c53f334d69a2ccf458339d51879",
          "md5": "cda58c7a6f2372c63a5a58ba6b155706"
        }
      ]
    }
  ]
}