{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime-ktx",
    "version": "2.9.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.9.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.9.0-beta01.aar",
          "url": "work-runtime-ktx-2.9.0-beta01.aar",
          "size": 2505,
          "sha512": "6a9a2abd26fe4ad48bf8e498aae1560cf9b585fe73115cc304e6fee8ccd4e5af29e29949ffd9b4f52d9b9254fe10dad927bdac3c8313d60d80780f2b3b1f7942",
          "sha256": "60a65cd2b90f69e9e0967729578c58d40d85b77a5a75ce8ee75648401fab0fed",
          "sha1": "3af960d99f95df0e37510723bba87c336bfadc0a",
          "md5": "d7aae8d9f1de6cad07997dd934580045"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.9.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.9.0-beta01.aar",
          "url": "work-runtime-ktx-2.9.0-beta01.aar",
          "size": 2505,
          "sha512": "6a9a2abd26fe4ad48bf8e498aae1560cf9b585fe73115cc304e6fee8ccd4e5af29e29949ffd9b4f52d9b9254fe10dad927bdac3c8313d60d80780f2b3b1f7942",
          "sha256": "60a65cd2b90f69e9e0967729578c58d40d85b77a5a75ce8ee75648401fab0fed",
          "sha1": "3af960d99f95df0e37510723bba87c336bfadc0a",
          "md5": "d7aae8d9f1de6cad07997dd934580045"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-runtime-ktx-2.9.0-beta01-sources.jar",
          "url": "work-runtime-ktx-2.9.0-beta01-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "work-runtime-ktx-2.9.0-beta01-versionMetadata.json",
          "url": "work-runtime-ktx-2.9.0-beta01-versionMetadata.json",
          "size": 3007,
          "sha512": "2935c1bd7b2309f87bd8036a40b99dd68820d73edcfdcc0acbda49f5d2e0f459f63d0a051e4aad216c46ffb7a80df7fe1d1684475e2b587abb2b3b468203f5f3",
          "sha256": "6125d9ef70538992093ff3f92bbcddb533fb23bff67c831c10dc8396261bfa01",
          "sha1": "21a8d647b22f503ec8017801435e34752ae38c81",
          "md5": "bb6d1d3239f9b605383142a5eee656e5"
        }
      ]
    }
  ]
}