{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-android-stubs",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-android-stubs-1.6.0-alpha06-topping02.aar",
          "url": "ui-android-stubs-1.6.0-alpha06-topping02.aar",
          "size": 4613,
          "sha512": "2bda9107a854925611f0d0a48fe4c68546ac80b13d9ff6983759ca941781dbefe7be29b09790dc6a9a4961ab0f22fe4501e2951bdc9715e89edf040dc1564e27",
          "sha256": "a39078a91e778a7f243a04d1f1653aff2e685e5bab7f54f1b1da434687248adb",
          "sha1": "aed0432af946edb1ad3a5af3dd16baaa10d8bcb5",
          "md5": "3a4140e2fbe0ac197f22c0b17d7dd298"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-android-stubs-1.6.0-alpha06-topping02.aar",
          "url": "ui-android-stubs-1.6.0-alpha06-topping02.aar",
          "size": 4613,
          "sha512": "2bda9107a854925611f0d0a48fe4c68546ac80b13d9ff6983759ca941781dbefe7be29b09790dc6a9a4961ab0f22fe4501e2951bdc9715e89edf040dc1564e27",
          "sha256": "a39078a91e778a7f243a04d1f1653aff2e685e5bab7f54f1b1da434687248adb",
          "sha1": "aed0432af946edb1ad3a5af3dd16baaa10d8bcb5",
          "md5": "3a4140e2fbe0ac197f22c0b17d7dd298"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-android-stubs-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-android-stubs-1.6.0-alpha06-topping02-sources.jar",
          "size": 2642,
          "sha512": "93cbc39477efacc9dfc72ae1adeaf60447aad075f5fc64e3d408208cb624e7c0e0374e45d6b0f3307903796367b0e2e139a16a74ffef83f22a1ff9db9372357c",
          "sha256": "f75c2c5b7c66e66cdbd22236e611421c514a9d1f9c480fa8198eb63c6a6c9a2a",
          "sha1": "47dabe83a4ae897aaf0c363f969e1590786905ff",
          "md5": "e4b91402299d4feed215391ba73d50d7"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "ui-android-stubs-1.6.0-alpha06-topping02-versionMetadata.json",
          "url": "ui-android-stubs-1.6.0-alpha06-topping02-versionMetadata.json",
          "size": 3749,
          "sha512": "f83ba0ad5ca6d3d0ebba94d83e8d2669a2cb9d6d620a51ae17e81a5e98bceb94bb08af703a1da004c54534015f52a9862194b276c357e3e6fdd28c5ad4cfa4c8",
          "sha256": "884df986e0f7983a8606e5b2200873b6aea166f9cb1d8972770be47a3174d28c",
          "sha1": "290137103b4ab12503dd47eb4446e9b6adf9037b",
          "md5": "faffdc5650a9996df97aa17aff4ce4d5"
        }
      ]
    }
  ]
}