{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-navigation/1.6.0-alpha06-topping02/ui-navigation-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.ui",
    "module": "ui-navigation",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lifecycle",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-navigation.klib",
          "url": "ui-navigation-iosarm64-1.6.0-alpha06-topping02.klib",
          "size": 470681,
          "sha512": "fe831c61b6b0e1fe52c181ea54517cb41c1910973b71c50ab9edf7aad190e0e6a5076cb3328f91b424642685bb1adbd2868117a6155fa970ca0f928204a13c58",
          "sha256": "23fc757d16ee6fc05323235c144f8b63cada3ed447e801e31e595b8ffef0b5b4",
          "sha1": "c7393f71142630a0b6bf8443ac54a009cd3e7165",
          "md5": "72e56a742b15fa9d27f9fe0a1b5925f7"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "ui-navigation-iosarm64-1.6.0-alpha06-topping02-sources.jar",
          "url": "ui-navigation-iosarm64-1.6.0-alpha06-topping02-sources.jar",
          "size": 104837,
          "sha512": "6bac96149fd54a268d0688b7b2e239c39a46e17bf049780b5df0f19389cf91963299556e048a6443769a1d0089d85f50069ff0b705f11dff430eedc40203e73d",
          "sha256": "0ac43eb203c9ad7fc91d0107baecf6852e1f6063e40e4d7589829af24345523d",
          "sha1": "f505f37e3375b390c8f46887571438864d4b9433",
          "md5": "b52165bb7ebcb1f0e551bf58ff5770a3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lifecycle",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-navigation-iosarm64-1.6.0-alpha06-topping02-metadata.jar",
          "url": "ui-navigation-iosarm64-1.6.0-alpha06-topping02-metadata.jar",
          "size": 21793,
          "sha512": "c4d89182bb101dc29a56811edfcfb10c15a9cc37ea8a416f056e537e0212980844e255c55122df88405b820a7e5cf539be3b941b81d59a086be94ff406c9d41e",
          "sha256": "2f0bfffa08bd9294d1a3afea5bae6af8e2c04af17a757af8466db236972c94b3",
          "sha1": "528c3df2b4074725812db5545f21aa64ad3ce001",
          "md5": "b58a1b44f368d7831a70acb4a6ceceec"
        }
      ]
    }
  ]
}