{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics-samples",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-samples-1.6.0-alpha06-topping01.aar",
          "url": "ui-graphics-samples-1.6.0-alpha06-topping01.aar",
          "size": 36479,
          "sha512": "4ea1a0824d2c08812221b007f781f82079d4363920d2672100a38e07c1ebdf5b53cbcdc04409f319a80472a5bbb7237aa718ac4d9f2763e60e3a56ac8d9bf35a",
          "sha256": "0e74e537c425005260de8d90a7f92ecf858beb3ee7d9b659da015ef90f81cdb8",
          "sha1": "6181787077ce7f8770d152b77bfac9c93ba4e9c0",
          "md5": "9a2c7becc7a6704897b9ce6e4c374956"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha06-topping01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-samples-1.6.0-alpha06-topping01.aar",
          "url": "ui-graphics-samples-1.6.0-alpha06-topping01.aar",
          "size": 36479,
          "sha512": "4ea1a0824d2c08812221b007f781f82079d4363920d2672100a38e07c1ebdf5b53cbcdc04409f319a80472a5bbb7237aa718ac4d9f2763e60e3a56ac8d9bf35a",
          "sha256": "0e74e537c425005260de8d90a7f92ecf858beb3ee7d9b659da015ef90f81cdb8",
          "sha1": "6181787077ce7f8770d152b77bfac9c93ba4e9c0",
          "md5": "9a2c7becc7a6704897b9ce6e4c374956"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-graphics-samples-1.6.0-alpha06-topping01-sources.jar",
          "url": "ui-graphics-samples-1.6.0-alpha06-topping01-sources.jar",
          "size": 6689,
          "sha512": "566d6d6e1c34abf7593f9d6b55974760d6a7a812f74a30381cee3f902076a0a86006f14543ee9040a52d72ef5d58fe7b19f89491c0d692e13e44229df9cd05d6",
          "sha256": "6c9136127a61fb6fdf5057fa969706801167d3fa4db18113dcc4c2cf8149c192",
          "sha1": "1bc26cfae5fc42ebd10d3ebaf966ba4cf5edf04c",
          "md5": "df491ef0e37bc7e29ccd296fcf7cc505"
        }
      ]
    }
  ]
}