{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "runtime-saveable-1.6.0-alpha06-topping02-multiplatform-sources.jar",
          "url": "runtime-saveable-1.6.0-alpha06-topping02-multiplatform-sources.jar",
          "size": 11899,
          "sha512": "259fc709f41f1fc8302d275b303d5e87542d6c536b85fdd321697868e12311015a6652dae14ef9315a9298ee17cf5c7ae5797f2414854a671eb7b88c63d02e55",
          "sha256": "4279270d355351632f74de2d30e32bff2d401db55ab8e6355ac233ee45ac7350",
          "sha1": "6b80d30499048fe45aebfb06dbadb13cefa6efcf",
          "md5": "21ab1378d022b8034fbd391af76e0ed2"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "runtime-saveable-1.6.0-alpha06-topping02-versionMetadata.json",
          "size": 3405,
          "sha512": "44994ff2de449c13516ea4c1ce34b41a9ce342c1450f80e6b29f35c743f18d697fe8beb96f2274bb43aa28aab41da942067c8ada96f42cc441c7eedd9b69795a",
          "sha256": "0a8d078a85cf98ea13d1496ff413d8ea8997a0221141bfdf48b9d3312122d942",
          "sha1": "c52e7ceaaeea18cc935ef5c4b66b32872cfb86b1",
          "md5": "08869e3c20c7b1f5825058e90bfe0e12"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha06-topping02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-metadata-1.6.0-alpha06-topping02.jar",
          "url": "runtime-saveable-1.6.0-alpha06-topping02.jar",
          "size": 6304,
          "sha512": "05eb0fdb4cacf3ff7c5c3b203454daf34788ecf7e4f6ba061d831191b1c7d4a703414055494a6030b515c293529584f431e70c28f87069edf5e4c7d686f095b1",
          "sha256": "6d4979ce30df7311abcbeb1d562350e2138e0f53f5dc86896c0e9308a73beb66",
          "sha1": "7ff2c524fb1c1095391bdbd69ecce62ee5b216b1",
          "md5": "57bbd925724644f6ddd8427b73ff311c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "runtime-saveable-kotlin-1.6.0-alpha06-topping02-sources.jar",
          "url": "runtime-saveable-1.6.0-alpha06-topping02-sources.jar",
          "size": 11533,
          "sha512": "f83659f1298dd8837cf5a0d7345e9704aaa6998191efb1602e9cd3ddd746f9f33dc34b86dfe1c2663ab7ee79e94b3536279ee5624c60bcd8d8b4368f78e7c595",
          "sha256": "d957fd3d4f67875cc990daa62c15ac1beebf0220c090c93db8ae04fad64bdafa",
          "sha1": "abf68b835dfdf24a970b8444c5067ffda33a37ca",
          "md5": "32c68128cbc35f49d91a14546b3d744c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-android/1.6.0-alpha06-topping02/runtime-saveable-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-android/1.6.0-alpha06-topping02/runtime-saveable-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-android/1.6.0-alpha06-topping02/runtime-saveable-android-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-android",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-desktop/1.6.0-alpha06-topping02/runtime-saveable-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-desktop/1.6.0-alpha06-topping02/runtime-saveable-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-saveable-desktop/1.6.0-alpha06-topping02/runtime-saveable-desktop-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-desktop",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-saveable-iosarm64/1.6.0-alpha06-topping02/runtime-saveable-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-saveable-iosarm64/1.6.0-alpha06-topping02/runtime-saveable-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-saveable-iosarm64/1.6.0-alpha06-topping02/runtime-saveable-iosarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-iosarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-saveable-iossimulatorarm64/1.6.0-alpha06-topping02/runtime-saveable-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-saveable-iossimulatorarm64/1.6.0-alpha06-topping02/runtime-saveable-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-saveable-iossimulatorarm64/1.6.0-alpha06-topping02/runtime-saveable-iossimulatorarm64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-iossimulatorarm64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-saveable-iosx64/1.6.0-alpha06-topping02/runtime-saveable-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-saveable-iosx64/1.6.0-alpha06-topping02/runtime-saveable-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../runtime-saveable-iosx64/1.6.0-alpha06-topping02/runtime-saveable-iosx64-1.6.0-alpha06-topping02.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-saveable-iosx64",
        "version": "1.6.0-alpha06-topping02"
      }
    }
  ]
}