{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.6.0-alpha06-topping02/runtime-1.6.0-alpha06-topping02.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.6.0-alpha06-topping02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-release.aar",
          "url": "runtime-android-1.6.0-alpha06-topping02.aar",
          "size": 2335585,
          "sha512": "ed4f8e66eccf91be6047e775b38d9925a400d7a1db4f5e7ca3bc974951944762de51cbd17a7bac6e598c01161802d251b2f1ba7d42c8ed0db9c35352cfac54a4",
          "sha256": "72a0fe0375f8a821165f6c943ef7c57142ca3e4a65ddce9fea1e9ba331af9cb1",
          "sha1": "f226323d9d5aa46b9ec53119610b087a050f65b2",
          "md5": "b9a38550daeda6f9060a2a422a55c3ba"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-release.aar",
          "url": "runtime-android-1.6.0-alpha06-topping02.aar",
          "size": 2335585,
          "sha512": "ed4f8e66eccf91be6047e775b38d9925a400d7a1db4f5e7ca3bc974951944762de51cbd17a7bac6e598c01161802d251b2f1ba7d42c8ed0db9c35352cfac54a4",
          "sha256": "72a0fe0375f8a821165f6c943ef7c57142ca3e4a65ddce9fea1e9ba331af9cb1",
          "sha1": "f226323d9d5aa46b9ec53119610b087a050f65b2",
          "md5": "b9a38550daeda6f9060a2a422a55c3ba"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "runtime-android-1.6.0-alpha06-topping02-sources.jar",
          "url": "runtime-android-1.6.0-alpha06-topping02-sources.jar",
          "size": 368041,
          "sha512": "4cc897f9ef7402254f5f2cc6e627d0f8e0f7b2eae1c5fd8375635b0ce115b6c057cd711df0b2039d0d0b09b8639b5b188daa975f18ff7e61b91bd79e4285b13a",
          "sha256": "7811f5febcd95d0d88ee46a067d5d911ab7f475531efbbcfba6e0d7ae7dcb138",
          "sha1": "f8806b43b4582330b79c7a66a3c60d6fe8cb090f",
          "md5": "d56b6f27afc9372cfaa422ccdfa2d645"
        }
      ]
    }
  ]
}