{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.resourceinspection",
    "module": "resourceinspection-annotation",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "resourceinspection-annotation-1.1.0-alpha01.jar",
          "url": "resourceinspection-annotation-1.1.0-alpha01.jar",
          "size": 2333,
          "sha512": "67551253eb8071a5035bf1772d736ac13c10208617b6359ab8c8d3ae8726d2f328b44fe224238f62f4ec24cda6744c99feec1145fc7b78a2edba5becd56b6119",
          "sha256": "8871925dfe4d96d30c9fe271d4d04c3820251a6904c0624889978818214ec707",
          "sha1": "19be37667420aac372cc4282f1f1c5c8a4f72f42",
          "md5": "98ef277692be933f3a22c4144b89b211"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "resourceinspection-annotation-1.1.0-alpha01.jar",
          "url": "resourceinspection-annotation-1.1.0-alpha01.jar",
          "size": 2333,
          "sha512": "67551253eb8071a5035bf1772d736ac13c10208617b6359ab8c8d3ae8726d2f328b44fe224238f62f4ec24cda6744c99feec1145fc7b78a2edba5becd56b6119",
          "sha256": "8871925dfe4d96d30c9fe271d4d04c3820251a6904c0624889978818214ec707",
          "sha1": "19be37667420aac372cc4282f1f1c5c8a4f72f42",
          "md5": "98ef277692be933f3a22c4144b89b211"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceinspection-annotation-1.1.0-alpha01-sources.jar",
          "url": "resourceinspection-annotation-1.1.0-alpha01-sources.jar",
          "size": 5232,
          "sha512": "07a5bc90bae446f6fe0b975b5125bdc535c20dfa0fd288d17012661d8e9930f65d70a6d9e7ef44ccb2f801d9bda151bd0a06febf03abfd2a83070f1d3bbb7697",
          "sha256": "b522eeadb5ce01dcd82015e8909a7eb086f664aeeb34d0aaa41c77cf99dad436",
          "sha1": "575a52f4015b03a22e67ec7d12712c928d6dd140",
          "md5": "27263131cfda0af23b13510c8e995087"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "resourceinspection-annotation-1.1.0-alpha01-versionMetadata.json",
          "url": "resourceinspection-annotation-1.1.0-alpha01-versionMetadata.json",
          "size": 412,
          "sha512": "a578b7cedb63ece4221be24decea6f59925a971c62bc1f37a46d45b5d023a7a547c5bda14ec9e5693b85fa6b139f02d07ae5d150a1f90842085bc1a9e46248b1",
          "sha256": "4d8347306b2a73bb94a6c3955302dcd9802ba004a2b6e709258ff9d41e4012fa",
          "sha1": "1e71da45852f9b80ec113200501a1e84c5c15e46",
          "md5": "ada7d1a331a96bcee7aefc261c67139a"
        }
      ]
    }
  ]
}