{
  "formatVersion": "1.1",
  "component": {
    "url": "../../internal-testutils-paging/unspecified/internal-testutils-paging-unspecified.module",
    "group": "androidx",
    "module": "internal-testutils-paging",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "internal-testutils-paging.klib",
          "url": "internal-testutils-paging-iossimulatorarm64-unspecified.klib",
          "size": 27626,
          "sha512": "83b6d00ff8c9ded5a44821d433c87267a4e9abc1980b75693f852b852767e8db1922374806c6a9b5cb38e18841fba2f228c5967f255368d516806b7444c98548",
          "sha256": "a6f650d29a8199f5a40872e7aecf06c971540d8b5f590f07387531cc2a0fdb6c",
          "sha1": "fe63f3e3da9a59fe72a636a2985057a9ea87abdf",
          "md5": "071a49de49526b866881961334ece195"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "internal-testutils-paging-iossimulatorarm64-sources.jar",
          "url": "internal-testutils-paging-iossimulatorarm64-unspecified-sources.jar",
          "size": 6810,
          "sha512": "c778af08f46297219fd9a9adbeba17984c64f100ba0f16277a5c4448d7e12480af7e96cc9618474ebb48a1281b348151d67d3f34df405ece5e399ad79a4ea8c4",
          "sha256": "108189f5e8ee0f633d32745178dad93771a746f9c5163dbc1bffbab20c18d574",
          "sha1": "af245c416605d47f65c83286705ff2b7d0a8232d",
          "md5": "937437a8da6ca80b1c890f9aefce8b32"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "internal-testutils-paging-iossimulatorarm64-metadata.jar",
          "url": "internal-testutils-paging-iossimulatorarm64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
