{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore/1.1.0-alpha05/datastore-1.1.0-alpha05.module",
    "group": "androidx.datastore",
    "module": "datastore",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore.klib",
          "url": "datastore-macosx64-1.1.0-alpha05.klib",
          "size": 5127,
          "sha512": "c8b3694c3d1272d20921891afbc65e5a4bb847f7ea82e46af91f97db651ae21d12e3c7ea9fb26322727cde7172388a028b29ec4965c5663d60766ed30e559720",
          "sha256": "53b1b354aef7b2d6495d6e2ae1e05002fd39377f3d6b44c432b13e3dd23443bd",
          "sha1": "7ebdb92576df2fef794a44ea09cc92b6d08bfac2",
          "md5": "ec82eb26c93ccd8d2edb60abd3916edc"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "datastore-macosx64-1.1.0-alpha05-sources.jar",
          "url": "datastore-macosx64-1.1.0-alpha05-sources.jar",
          "size": 1341,
          "sha512": "eab270f4091bd2aec5e4d32f1086186713c77bc914165c1045ac75e2f16f3470cee287e8286d7025dda724fc71158294c72abcaacdb89578713648c09841c76e",
          "sha256": "a72f12ea4109692cb5a60d961b2cbf25ffc611c3995dc645c9010f249a5db291",
          "sha1": "697a77e86cf0f0f4597fdf283224f63791cb29c3",
          "md5": "3cc4d627507697ca341bd6c1dd3ee8b4"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-macosx64-1.1.0-alpha05-metadata.jar",
          "url": "datastore-macosx64-1.1.0-alpha05-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}