{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.desktop",
    "module": "desktop-samples",
    "version": "1.6.0-alpha06-topping01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "desktop-samples-metadata-1.6.0-alpha06-topping01.jar",
          "url": "desktop-samples-1.6.0-alpha06-topping01.jar",
          "size": 647,
          "sha512": "f9c081b46244233787a52aabb776722b019e9521c3a89a6b4e55a669be9cfee3411764e79d1de9563bc03c6e61e4fe541deee4b30affd96a14de6dd2fdca1dc9",
          "sha256": "089e24417bf9f6c34eec5720eebb2cbcc82ea2855ecef90133eb17e1079d5868",
          "sha1": "28cbbd267e2cdbea0a637d71db8f57b788a419c0",
          "md5": "ba0b1a9fde0b67f9902aec928b1936fb"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "desktop-samples-kotlin-1.6.0-alpha06-topping01-sources.jar",
          "url": "desktop-samples-1.6.0-alpha06-topping01-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../desktop-samples-jvm/1.6.0-alpha06-topping01/desktop-samples-jvm-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.desktop",
        "module": "desktop-samples-jvm",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../desktop-samples-jvm/1.6.0-alpha06-topping01/desktop-samples-jvm-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.desktop",
        "module": "desktop-samples-jvm",
        "version": "1.6.0-alpha06-topping01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../desktop-samples-jvm/1.6.0-alpha06-topping01/desktop-samples-jvm-1.6.0-alpha06-topping01.module",
        "group": "androidx.compose.desktop",
        "module": "desktop-samples-jvm",
        "version": "1.6.0-alpha06-topping01"
      }
    }
  ]
}
