{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "collection-metadata-1.4.0-alpha01.jar",
          "url": "collection-1.4.0-alpha01.jar",
          "size": 27195,
          "sha512": "ed6c46670b53c0e141a7ec384714d16c5804fbde2b23cd1c4e5cce72015fd356b0c7e275861234422b09a4a14418169229124d7e771e09748bb8ee64843d440d",
          "sha256": "c160886334b838aeec1fe41f8c850e8a7b2bd0bef5c754fea750a063944f8260",
          "sha1": "0d1705b96567fbeae59a7b3067565849adb1e54b",
          "md5": "360a48e8f6a5e684e338757726a6c958"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "collection-kotlin-1.4.0-alpha01-sources.jar",
          "url": "collection-1.4.0-alpha01-sources.jar",
          "size": 224252,
          "sha512": "c7b66d91d3190d7a5517e25c0484ec701e613596db44af66a302e61b84c9a2514d23e472168995e149d97cd6be90b42e0789902769375551ce59f0c6465cc680",
          "sha256": "3d2c46e2cf6d9f7370cd360e5e68f084b50041b50e3d8abd1b2a6b03684aceff",
          "sha1": "483e9f34d8aee39697a93e4c285e61beae35498f",
          "md5": "07feeb968f51dc4b1e5933eb430705b0"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosarm64/1.4.0-alpha01/collection-iosarm64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-iosarm64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosarm64/1.4.0-alpha01/collection-iosarm64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-iosarm64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosarm64/1.4.0-alpha01/collection-iosarm64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-iosarm64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iossimulatorarm64/1.4.0-alpha01/collection-iossimulatorarm64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-iossimulatorarm64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iossimulatorarm64/1.4.0-alpha01/collection-iossimulatorarm64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-iossimulatorarm64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iossimulatorarm64/1.4.0-alpha01/collection-iossimulatorarm64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-iossimulatorarm64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosx64/1.4.0-alpha01/collection-iosx64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-iosx64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosx64/1.4.0-alpha01/collection-iosx64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-iosx64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosx64/1.4.0-alpha01/collection-iosx64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-iosx64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../collection-jvm/1.4.0-alpha01/collection-jvm-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-jvm",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../collection-jvm/1.4.0-alpha01/collection-jvm-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-jvm",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../collection-jvm/1.4.0-alpha01/collection-jvm-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-jvm",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosarm64/1.4.0-alpha01/collection-macosarm64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-macosarm64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosarm64/1.4.0-alpha01/collection-macosarm64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-macosarm64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosarm64/1.4.0-alpha01/collection-macosarm64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-macosarm64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosx64/1.4.0-alpha01/collection-macosx64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-macosx64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosx64/1.4.0-alpha01/collection-macosx64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-macosx64",
        "version": "1.4.0-alpha01"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosx64/1.4.0-alpha01/collection-macosx64-1.4.0-alpha01.module",
        "group": "androidx.collection",
        "module": "collection-macosx64",
        "version": "1.4.0-alpha01"
      }
    }
  ]
}